{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-gvt",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-gvt-1.2.1.jar",
          "url": "echosvg-gvt-1.2.1.jar",
          "size": 193859,
          "sha512": "18c28ab12c998b293914833a27b5d89fb10f2719070f6a19889870918b5bb92ebf5bd7fd9a2a63861230ab1e6601dbb668b4845daf4d10861bdca47c5a82c2c7",
          "sha256": "fe3bc71a4c656371f85f4fd3ae33dc6e30efa02be00752d8fb6508dbd82c3b4f",
          "sha1": "0f209944ac8c6d8b1dd52679ce1f9f69942aab9b",
          "md5": "9e43d05c7127e0c659177e400eb750e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-gvt-1.2.1.jar",
          "url": "echosvg-gvt-1.2.1.jar",
          "size": 193859,
          "sha512": "18c28ab12c998b293914833a27b5d89fb10f2719070f6a19889870918b5bb92ebf5bd7fd9a2a63861230ab1e6601dbb668b4845daf4d10861bdca47c5a82c2c7",
          "sha256": "fe3bc71a4c656371f85f4fd3ae33dc6e30efa02be00752d8fb6508dbd82c3b4f",
          "sha1": "0f209944ac8c6d8b1dd52679ce1f9f69942aab9b",
          "md5": "9e43d05c7127e0c659177e400eb750e3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-gvt-1.2.1-sources.jar",
          "url": "echosvg-gvt-1.2.1-sources.jar",
          "size": 200035,
          "sha512": "6e7d4095b40edc8d254b4f20de02351f5be30507e8cd25e50f074fe7d325e5a5b613dea992d389899d303c13ba6aff6ab53adf69cbdfc78ded482112df2512db",
          "sha256": "51bfae527e7c1f0f9cba1faea092987051ad7c5402a0d71b520e731ff1f21b13",
          "sha1": "002a4ff13dd1d8b140b0893d6a628a38fe1b3531",
          "md5": "91cc13e7a2a0c941fe7906ddf4c91ce0"
        }
      ]
    }
  ]
}
