{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-slideshow",
    "version": "0.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gvt",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-slideshow-0.3.3.jar",
          "url": "echosvg-slideshow-0.3.3.jar",
          "size": 16183,
          "sha512": "15a95e07c5600b5625359a6da240081f1e350a051252500538de6352a60558af21cc06b58ee0665d8de6e2367b41434662e38a65f4dec13c9ef5b3690321ebca",
          "sha256": "35bc913dbe2470e45287a5d1f9caec61a48e2672a957367aed8484f4aaedb206",
          "sha1": "da8f9f2a512d083c048c42a5d3420789f4f942f9",
          "md5": "721f664667d7e6fa009fd88391a05f9f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gvt",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-slideshow-0.3.3.jar",
          "url": "echosvg-slideshow-0.3.3.jar",
          "size": 16183,
          "sha512": "15a95e07c5600b5625359a6da240081f1e350a051252500538de6352a60558af21cc06b58ee0665d8de6e2367b41434662e38a65f4dec13c9ef5b3690321ebca",
          "sha256": "35bc913dbe2470e45287a5d1f9caec61a48e2672a957367aed8484f4aaedb206",
          "sha1": "da8f9f2a512d083c048c42a5d3420789f4f942f9",
          "md5": "721f664667d7e6fa009fd88391a05f9f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-slideshow-0.3.3-sources.jar",
          "url": "echosvg-slideshow-0.3.3-sources.jar",
          "size": 9967,
          "sha512": "96d2a842436b3dfaa88287ddd827d483e94ac45d1d5d25e9a0b8fe2c224aba1881164a9f71001f22c7397cca2965d7e1a1f0334db4ca75a072bdbd50656f5e1e",
          "sha256": "ed0c52130a205e566b4f17193bf6e072c64bf289e2c49fe0a003448f920a0675",
          "sha1": "ac3be5ee51a609da87839da00462a5b82f5a5d05",
          "md5": "be0363ce8de851b1b4a520e744e7856f"
        }
      ]
    }
  ]
}
