{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-gui-util",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-gui-util-0.2.1.jar",
          "url": "echosvg-gui-util-0.2.1.jar",
          "size": 176326,
          "sha512": "5233c68cb1ac3d7defa738ead1166d20deadb537f35998ed089562b6a2dfacb6fdc998cdc39930926b574eff19c7008a4c755c578f585cfaabcc5e03ac967d98",
          "sha256": "bda484e23824373303fe350087bf921b48f952cac8598f2e59ba0b1f0821aee9",
          "sha1": "a69ac54173225b2f2dfee9153292d995a2e893c8",
          "md5": "bdc3c9f8db015a5e07d566a2dd85d750"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-gui-util-0.2.1.jar",
          "url": "echosvg-gui-util-0.2.1.jar",
          "size": 176326,
          "sha512": "5233c68cb1ac3d7defa738ead1166d20deadb537f35998ed089562b6a2dfacb6fdc998cdc39930926b574eff19c7008a4c755c578f585cfaabcc5e03ac967d98",
          "sha256": "bda484e23824373303fe350087bf921b48f952cac8598f2e59ba0b1f0821aee9",
          "sha1": "a69ac54173225b2f2dfee9153292d995a2e893c8",
          "md5": "bdc3c9f8db015a5e07d566a2dd85d750"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-gui-util-0.2.1-sources.jar",
          "url": "echosvg-gui-util-0.2.1-sources.jar",
          "size": 120245,
          "sha512": "a70e30e2a28ec24903f404b76e608caa9b89de0155ec4d25b3ae48aa155d4377b3c07396e2a2d3f0d8dc887e292bf4aaa0b2fe63900cc32c973b6a2a7eaf3f07",
          "sha256": "7db72505876dd8efdcdfed6cd531305cc281f0dc30283ad6fc1cf93e24b205b7",
          "sha1": "ff5203fabe001b060c3c25bbed47934e4933ac15",
          "md5": "0a0aee89fa9414eb3f80532caedbe405"
        }
      ]
    }
  ]
}
