{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-test",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-swing",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-test-1.1.1.jar",
          "url": "echosvg-test-1.1.1.jar",
          "size": 53474,
          "sha512": "d0995072f2f723a0d462d66097093dfc1c6880153c396aa3be85b34ba96354614211b667e4abb5b171efa0ee28982fbd39c476076c6f272459aab327b0a74297",
          "sha256": "fd9df046e7f43ad381ce6e4c10a1dee0366adceb80921ee13c2bc4cbcdb95f9e",
          "sha1": "0b3fdc0c0188985c15cf76924e3841211436ef4c",
          "md5": "2d296320ff6a56b8caa5233df6aa76ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-extension",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.jclf",
          "module": "jclf-text",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-codec",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-swing",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-test-1.1.1.jar",
          "url": "echosvg-test-1.1.1.jar",
          "size": 53474,
          "sha512": "d0995072f2f723a0d462d66097093dfc1c6880153c396aa3be85b34ba96354614211b667e4abb5b171efa0ee28982fbd39c476076c6f272459aab327b0a74297",
          "sha256": "fd9df046e7f43ad381ce6e4c10a1dee0366adceb80921ee13c2bc4cbcdb95f9e",
          "sha1": "0b3fdc0c0188985c15cf76924e3841211436ef4c",
          "md5": "2d296320ff6a56b8caa5233df6aa76ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-test-1.1.1-sources.jar",
          "url": "echosvg-test-1.1.1-sources.jar",
          "size": 35651,
          "sha512": "c847402d94555ab98211d28cc308fa6a27626713db98003dc9370072ad70b7575a4562bb190ef8d906d60c02342bb97300401d65a1eaa47d55ef2f3456e19ea3",
          "sha256": "4c7ad5d3dd04daaa4693fbf0fa2915c7e372853b9a8f6838623dec10a22b5c50",
          "sha1": "0d4687afc95845a2093588fa2857086d76b0e5f0",
          "md5": "57bb6122b9eb9932c3ed61de55db860a"
        }
      ]
    }
  ]
}
