{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-script",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "0.3"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.7.14"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-script-0.3.jar",
          "url": "echosvg-script-0.3.jar",
          "size": 26848,
          "sha512": "0940847e909d4e2056a41171fd9d5ed7eb03886ef1890858471ace8f0a1ad2d6c795257b5688fd8c22a694ca1e6fac8972c022845e6d057e6269c6e3da556bae",
          "sha256": "0080a46cc888c2f532e27db74676258cd0cd3ec13ad0d8eb8e3d78df56768497",
          "sha1": "5548b6ca0282a99a557b8378d1293b17b47b8fcf",
          "md5": "252348fa7550fa035caab82849a78d25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "xml-apis",
          "module": "xml-apis",
          "version": {
            "requires": "1.4.01"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "0.3"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.7.14"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-script-0.3.jar",
          "url": "echosvg-script-0.3.jar",
          "size": 26848,
          "sha512": "0940847e909d4e2056a41171fd9d5ed7eb03886ef1890858471ace8f0a1ad2d6c795257b5688fd8c22a694ca1e6fac8972c022845e6d057e6269c6e3da556bae",
          "sha256": "0080a46cc888c2f532e27db74676258cd0cd3ec13ad0d8eb8e3d78df56768497",
          "sha1": "5548b6ca0282a99a557b8378d1293b17b47b8fcf",
          "md5": "252348fa7550fa035caab82849a78d25"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-script-0.3-sources.jar",
          "url": "echosvg-script-0.3-sources.jar",
          "size": 29429,
          "sha512": "d27561e76c853c5c2ba8dcdbc7f8d084ecbc04d15a13f6a9a80643206537f0cabfa8d438ec2e3743f6cd794ff484fae22d0938f609736c97b8fb6c8d7612e75b",
          "sha256": "2fdf2ddc141aacc3744eb4c961c8c236fefcb16fd83af4decc855e9e65ed1526",
          "sha1": "163f7f6d7824cc1197629609e046da17b1b284f6",
          "md5": "2117e944a659687bf1afeb678dca919d"
        }
      ]
    }
  ]
}
