{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "svgom-api",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "smil-api",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "svgom-api-1.0.jar",
          "url": "svgom-api-1.0.jar",
          "size": 69773,
          "sha512": "2b2e2d12eae792f93ab83f5f17c757c9426a0f38f9836ce91d63e3f048b992d556a322cad386e04c415c6277bd52573b5bfd46da45530bcc555b2b1d53baeab9",
          "sha256": "3f58abeac08e151ae61df8a69bbd4dc8b514a7ea903a52ad5a3831e700e898c1",
          "sha1": "114142943de4e05500359272c39ac1fc09b5dd3d",
          "md5": "f515df3e245f36ad9c4ea8d313372da7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "smil-api",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "svgom-api-1.0.jar",
          "url": "svgom-api-1.0.jar",
          "size": 69773,
          "sha512": "2b2e2d12eae792f93ab83f5f17c757c9426a0f38f9836ce91d63e3f048b992d556a322cad386e04c415c6277bd52573b5bfd46da45530bcc555b2b1d53baeab9",
          "sha256": "3f58abeac08e151ae61df8a69bbd4dc8b514a7ea903a52ad5a3831e700e898c1",
          "sha1": "114142943de4e05500359272c39ac1fc09b5dd3d",
          "md5": "f515df3e245f36ad9c4ea8d313372da7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "svgom-api-1.0-sources.jar",
          "url": "svgom-api-1.0-sources.jar",
          "size": 112308,
          "sha512": "178a6572b74246dd97449af8eba6f700b7e4cbffea95b824c9be7945fcd367fe60156d9b8f5c5249da6ec92e5c630f720d9f39e4d6b1f7359eba37e07ddaf90d",
          "sha256": "0fa846172254f0359f499cdb97b7807ed3b1bb1f69037a689eeaf78d20418b3d",
          "sha1": "d5dcfd3b97d5f1f62fabb3ba3766bd50fe5e9624",
          "md5": "25e7e1acd48836e1c1f8568de771a3ad"
        }
      ]
    }
  ]
}
