{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-all",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-extension",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-swing",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-slideshow",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgpp",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ttf2svg",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgrasterizer",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-all-0.2.jar",
          "url": "echosvg-all-0.2.jar",
          "size": 5348,
          "sha512": "eca9b66ed377015c3e9567d0a3159cfa3cd562f1906c7f741e94da20cf0e2ed4f19bf13fcb11f617a6606892a17962b30e3e970f95181ecd37f270dfe592d4ba",
          "sha256": "2a350119043d8ba96bf7c805f266eba9bc268e0c08b012f450d07ad998fdae24",
          "sha1": "99449e060febb127757d50c4f61ee230da0af78f",
          "md5": "45593a7144d0232bc4f6226828d5c153"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-extension",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-swing",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-slideshow",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgpp",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ttf2svg",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgrasterizer",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-all-0.2.jar",
          "url": "echosvg-all-0.2.jar",
          "size": 5348,
          "sha512": "eca9b66ed377015c3e9567d0a3159cfa3cd562f1906c7f741e94da20cf0e2ed4f19bf13fcb11f617a6606892a17962b30e3e970f95181ecd37f270dfe592d4ba",
          "sha256": "2a350119043d8ba96bf7c805f266eba9bc268e0c08b012f450d07ad998fdae24",
          "sha1": "99449e060febb127757d50c4f61ee230da0af78f",
          "md5": "45593a7144d0232bc4f6226828d5c153"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-all-0.2-sources.jar",
          "url": "echosvg-all-0.2-sources.jar",
          "size": 5510,
          "sha512": "48d9c6b91026c828f2c3e1c588a9594a09e5ca28f20674eb4386a645ae5e300960f5329c261784402d47d9fe17cb3017113382ac9faae9a0db221e41dcc8f67a",
          "sha256": "245b803863b3df06d2cb9a8613adf9683aed109c7c3660fe541c6f68be59f950",
          "sha1": "14303d6a5ccc01b9bb7896631f6399a54583cfd7",
          "md5": "8f054cc6f19e1fd88b12d15b7737bac3"
        }
      ]
    }
  ]
}
