{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-transcoder-api",
    "version": "2.0-pre1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "echosvg-transcoder-api-2.0-pre1.jar",
          "url": "echosvg-transcoder-api-2.0-pre1.jar",
          "size": 23971,
          "sha512": "898c6b440522071d32ad31726dcddccb0bd9e4d4acc746660a7ffdcc893d632250b74758727f2cafa4ab0eccf7f9c3cede58d31ce23f51ec220a833a54b72ede",
          "sha256": "1e939b4971f3d2834d999425a96dd86b5cd0497ac3a2acfbe97ab4321265b5af",
          "sha1": "7e9cfb427ec41c2b4f906f270fcb77137bb1dfcf",
          "md5": "97e0789c24ba0d16b9d7c656aaa59d04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "2.0-pre1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-transcoder-api-2.0-pre1.jar",
          "url": "echosvg-transcoder-api-2.0-pre1.jar",
          "size": 23971,
          "sha512": "898c6b440522071d32ad31726dcddccb0bd9e4d4acc746660a7ffdcc893d632250b74758727f2cafa4ab0eccf7f9c3cede58d31ce23f51ec220a833a54b72ede",
          "sha256": "1e939b4971f3d2834d999425a96dd86b5cd0497ac3a2acfbe97ab4321265b5af",
          "sha1": "7e9cfb427ec41c2b4f906f270fcb77137bb1dfcf",
          "md5": "97e0789c24ba0d16b9d7c656aaa59d04"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-transcoder-api-2.0-pre1-sources.jar",
          "url": "echosvg-transcoder-api-2.0-pre1-sources.jar",
          "size": 32853,
          "sha512": "0d31195e5f86cf34c802c8efe888f45ced1c2828daa636adc8b627ea897daa730fb6a077443d1e3a64805e05d1f9fa5340ef9cebea3d5ee1ef233a093db0aaaa",
          "sha256": "b112fa9a797c8d9ec8effe00c259e7c6b999336b9fb1a2f94d71e5557f9f319a",
          "sha1": "962302fa2770158d9e1374f0f30e24c622a69e66",
          "md5": "bc980eb7de4cc107dc88afe523889411"
        }
      ]
    }
  ]
}
