{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "carte-util",
    "version": "3.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "carte-util-3.5.1.jar",
          "url": "carte-util-3.5.1.jar",
          "size": 5243,
          "sha512": "703f4f2df2c5d913dc8648bf58a3bd1e72be886ed0f048435f4d561226a57a64b1af81d93753e29a80da2e80885abe66c17dedc0c9d0a3a92ec1eebb5e1fa2a7",
          "sha256": "26030e4fa54eb1766a2749c3c42f1e930152ced7353d309ec8f811d1482ce7af",
          "sha1": "9b3f515b4c3ff7d29d41b872dc2e51e337ba9ea0",
          "md5": "9d37d844a56003df9b14f5c34aa85bca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "carte-util-3.5.1.jar",
          "url": "carte-util-3.5.1.jar",
          "size": 5243,
          "sha512": "703f4f2df2c5d913dc8648bf58a3bd1e72be886ed0f048435f4d561226a57a64b1af81d93753e29a80da2e80885abe66c17dedc0c9d0a3a92ec1eebb5e1fa2a7",
          "sha256": "26030e4fa54eb1766a2749c3c42f1e930152ced7353d309ec8f811d1482ce7af",
          "sha1": "9b3f515b4c3ff7d29d41b872dc2e51e337ba9ea0",
          "md5": "9d37d844a56003df9b14f5c34aa85bca"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "carte-util-3.5.1-javadoc.jar",
          "url": "carte-util-3.5.1-javadoc.jar",
          "size": 127049,
          "sha512": "e65435f12d71db30c985f66a1108dd9611b43595c5c56f96156dcdf77ba3a14d195e50fc4a06a56be66c371390c25c093ae2f3e6b6b3fa8ffd26859335d82631",
          "sha256": "0be462efc9e37b0de5ce91f69f0206b9c6086f24403f0f435fb2512b28b1c81e",
          "sha1": "e764096ea0d193cc75280f2c70e21c63c7add8c9",
          "md5": "c76925718e733d2508b1f62d7fdf8917"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "carte-util-3.5.1-sources.jar",
          "url": "carte-util-3.5.1-sources.jar",
          "size": 6544,
          "sha512": "8c4b715f92bed50e12a02a2ea833bd924e3f090216cddf22bcffc3bcd07daf720dd4cc52895bed70112043b75da1257b9a04c639d52177be6e0b85ff5798a2b7",
          "sha256": "72b23969ac85c3be890c357366a7081c5747e3ff357c11955e29fa150811bf57",
          "sha1": "d5726b2ace1efdc436750f0e441a69167b5e03ba",
          "md5": "60b49765b1820cfa13e6c36b65b4c10d"
        }
      ]
    }
  ]
}
