{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-slideshow",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gvt",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-slideshow-0.1.jar",
          "url": "echosvg-slideshow-0.1.jar",
          "size": 16388,
          "sha512": "b5edd6b9b20f8cc0ea8a90b7aecf805945998496974c51f2c60335f195165986fc39e30af33f7d1fc0c70a0883f56e9b9dffd395f1a5542028674128e9ffa2b5",
          "sha256": "9d010abe5d2e0d78186a7f980fe71c8e6cfee247841ba85a5720a4ce0c1d9949",
          "sha1": "d6f4139785969b40021794435eaadc5d9cdec72e",
          "md5": "9c4d83f1f0aa4fcdb58358d25a4e6f88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gvt",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-slideshow-0.1.jar",
          "url": "echosvg-slideshow-0.1.jar",
          "size": 16388,
          "sha512": "b5edd6b9b20f8cc0ea8a90b7aecf805945998496974c51f2c60335f195165986fc39e30af33f7d1fc0c70a0883f56e9b9dffd395f1a5542028674128e9ffa2b5",
          "sha256": "9d010abe5d2e0d78186a7f980fe71c8e6cfee247841ba85a5720a4ce0c1d9949",
          "sha1": "d6f4139785969b40021794435eaadc5d9cdec72e",
          "md5": "9c4d83f1f0aa4fcdb58358d25a4e6f88"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-slideshow-0.1-sources.jar",
          "url": "echosvg-slideshow-0.1-sources.jar",
          "size": 9900,
          "sha512": "1f3beca35404c4d10aa1bcc236aa9bc2a39e872ca81231daf47469415639932e18277601d9098f080554e977c5a4ba73cf9f675b145a66b02d1ce89002a8aed2",
          "sha256": "3ae455fdc9fa5ead94cf1bfd81d3e1b24d4c8c5bebe036de96c0ebff95ac44b1",
          "sha1": "9d60bc63518bbb755f32fac15eb0e14996b8c385",
          "md5": "f117c3d698105e317ba27905e882823a"
        }
      ]
    }
  ]
}
