{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-slideshow",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gvt",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-slideshow-0.2.1.jar",
          "url": "echosvg-slideshow-0.2.1.jar",
          "size": 16098,
          "sha512": "86d156093e44dc9ea5a8bc79025dca70ac85499400463e673003e2eff8a4d463fe7b5ad8111f9c01b8a07cac373bad76c9bc8b646ae02d8608fa58174a5ad0b9",
          "sha256": "bb925e88badeba1700c3b5f6898bc0d27de7ec344f27d49b09576a59d733ed5c",
          "sha1": "17c3683032b7c24f0789d32a5e0ccb028ab435a3",
          "md5": "57c1d24799e11c40f47cc4519d06bf52"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gvt",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-slideshow-0.2.1.jar",
          "url": "echosvg-slideshow-0.2.1.jar",
          "size": 16098,
          "sha512": "86d156093e44dc9ea5a8bc79025dca70ac85499400463e673003e2eff8a4d463fe7b5ad8111f9c01b8a07cac373bad76c9bc8b646ae02d8608fa58174a5ad0b9",
          "sha256": "bb925e88badeba1700c3b5f6898bc0d27de7ec344f27d49b09576a59d733ed5c",
          "sha1": "17c3683032b7c24f0789d32a5e0ccb028ab435a3",
          "md5": "57c1d24799e11c40f47cc4519d06bf52"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-slideshow-0.2.1-sources.jar",
          "url": "echosvg-slideshow-0.2.1-sources.jar",
          "size": 9970,
          "sha512": "3e8caccd7dded658df3809c5fd0aab4faba61cab5d9bbeca7d24b54a9f93a8e2aecf7519af3ca3f9a6e8ee14f8513e0153c48ed25dbc08cb8ebb133e411ee124",
          "sha256": "3ebedb5ae2194cc1e1cc2c272425b0bc2d603e4b924d6577b1979323e131d008",
          "sha1": "fbd2949fc35f356bf2f1e921e820f97489d43f57",
          "md5": "6a5c984d4a52baf8a021c9f25efa8f08"
        }
      ]
    }
  ]
}
