{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-i18n",
    "version": "2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "echosvg-i18n-2.5.jar",
          "url": "echosvg-i18n-2.5.jar",
          "size": 10532,
          "sha512": "52d13cde20585f1f5bdd54b81876be3d6bc1b09a1fd87fbdd7df349446a35dcb1c53d77f2884b8758172266a5d57224816d6378c03eb96998c50bd20c66f11e1",
          "sha256": "7c03cc306360b96b0d1136152a51aa8ae30766beea3d5b3b4b06e1e9f31847b3",
          "sha1": "71a159dc1c94e0cfe8c850dbbd1c118ee4d855f5",
          "md5": "16b89f106c7f6fd9624f6935fb39a89d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-i18n-2.5.jar",
          "url": "echosvg-i18n-2.5.jar",
          "size": 10532,
          "sha512": "52d13cde20585f1f5bdd54b81876be3d6bc1b09a1fd87fbdd7df349446a35dcb1c53d77f2884b8758172266a5d57224816d6378c03eb96998c50bd20c66f11e1",
          "sha256": "7c03cc306360b96b0d1136152a51aa8ae30766beea3d5b3b4b06e1e9f31847b3",
          "sha1": "71a159dc1c94e0cfe8c850dbbd1c118ee4d855f5",
          "md5": "16b89f106c7f6fd9624f6935fb39a89d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-i18n-2.5-sources.jar",
          "url": "echosvg-i18n-2.5-sources.jar",
          "size": 12742,
          "sha512": "51a85118cb47f8f6c56d81f582aba6e06901fa8758fa7610d30353b40385e9770db538c45e7df9c43d79b7cbfce542a73caf05ec0d9930f625a784f962359992",
          "sha256": "837495f15946a51c2c6614c6854b79b71d9c6ed2a8b48511bd8adc4c2e5f33d3",
          "sha1": "1846586cf993b47105e9c0c5e18d7c00e8f1ab17",
          "md5": "8ea3e84a649f1b97fbc65470eff39a06"
        }
      ]
    }
  ]
}
