{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-css",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "xml-apis",
          "module": "xml-apis-ext",
          "version": {
            "requires": "1.3.04"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "css4j",
          "version": {
            "requires": "3.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-css-0.1.jar",
          "url": "echosvg-css-0.1.jar",
          "size": 293177,
          "sha512": "11017bc465ade0f63d9c4c33dec26e32dba830d6a2d809e13232a78e07d64cdbd7e083e6ca73184bd6dc648d0bff563c2f64c2af8c76373b06680e7da2b29808",
          "sha256": "30ce701498e9bce8521c570f961ec8e0b13a9da617c5670d8090b5dac34f4f87",
          "sha1": "e27c53cb883ee9b334ffae46ba1501880ddd3c44",
          "md5": "6876e46e4558eb52247349018d3bccd2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "xml-apis",
          "module": "xml-apis-ext",
          "version": {
            "requires": "1.3.04"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "css4j",
          "version": {
            "requires": "3.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-css-0.1.jar",
          "url": "echosvg-css-0.1.jar",
          "size": 293177,
          "sha512": "11017bc465ade0f63d9c4c33dec26e32dba830d6a2d809e13232a78e07d64cdbd7e083e6ca73184bd6dc648d0bff563c2f64c2af8c76373b06680e7da2b29808",
          "sha256": "30ce701498e9bce8521c570f961ec8e0b13a9da617c5670d8090b5dac34f4f87",
          "sha1": "e27c53cb883ee9b334ffae46ba1501880ddd3c44",
          "md5": "6876e46e4558eb52247349018d3bccd2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-css-0.1-sources.jar",
          "url": "echosvg-css-0.1-sources.jar",
          "size": 208740,
          "sha512": "72bccaaf1f17767e11a832f5309a759b483d1d704b32cc741bfe0dc309a41161e095410f7d05a5a47bef2f0728f9879c1384dbef01110455c905f12375b7ac6f",
          "sha256": "fc8d1fdeff7afd9cb3d7503a60a3fc03f5d9b8fce07a760c15933f2427084efb",
          "sha1": "3ba51d2024bde83d19492a427099543b2a266d24",
          "md5": "41ec92495b5aebe3007aeb2972a8313e"
        }
      ]
    }
  ]
}
