{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-css",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "css4j",
          "version": {
            "requires": "3.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-css-0.1.jar",
          "url": "echosvg-css-0.1.jar",
          "size": 293184,
          "sha512": "d21b804ba5aef2946556e913e3241b55f5c9d8ebc97e4e5578b493a1f555128a2dbb5f3720bb972b2738010f7bd735b8db623f38fefdc66afdeb492d0a7206ef",
          "sha256": "d9bcc00edeb046f11811be2778ef1233770723413118bacbada98ca3faa891ac",
          "sha1": "5219851b840b2cd27ce2167af81fce99d1c0368a",
          "md5": "9a84aaa11daf1ced3d5ffd47bc0a4395"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "css4j",
          "version": {
            "requires": "3.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-css-0.1.jar",
          "url": "echosvg-css-0.1.jar",
          "size": 293184,
          "sha512": "d21b804ba5aef2946556e913e3241b55f5c9d8ebc97e4e5578b493a1f555128a2dbb5f3720bb972b2738010f7bd735b8db623f38fefdc66afdeb492d0a7206ef",
          "sha256": "d9bcc00edeb046f11811be2778ef1233770723413118bacbada98ca3faa891ac",
          "sha1": "5219851b840b2cd27ce2167af81fce99d1c0368a",
          "md5": "9a84aaa11daf1ced3d5ffd47bc0a4395"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-css-0.1-sources.jar",
          "url": "echosvg-css-0.1-sources.jar",
          "size": 208786,
          "sha512": "38462d957382cd700a74d3a6f3098fad47cc4d0fe02e3d87555de8e8d671ba62adef133cb851e5babf8d97d04e11a798c9431de7938e59ee71c809c238063903",
          "sha256": "3059c4f63d10611d39976f3a0f16179fb8493c2b40d9bb09156f6beae86df6c6",
          "sha1": "9f88792a23ed427815b809b4955ed7adec35f5a7",
          "md5": "05908a823fdc294987759d7b276fd609"
        }
      ]
    }
  ]
}
