{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-i18n",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "echosvg-i18n-1.2.jar",
          "url": "echosvg-i18n-1.2.jar",
          "size": 10188,
          "sha512": "23aafb9d468ebbd6c24e2739bfe6d0e51766892a27296398e70b9736e17b946d695658dd783604329d580ad89ba80bc8b3c59b18c389ff30ac735565087318c0",
          "sha256": "284c17a5f98c8462ecb9ba02ae761909183fc1e853656b7d672d9abbab5a21c3",
          "sha1": "b525bdf3cbc6b7900252f61ccede193e0a7535fd",
          "md5": "2cbc7f3ccb5e936010d7fa3214d8b0f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-i18n-1.2.jar",
          "url": "echosvg-i18n-1.2.jar",
          "size": 10188,
          "sha512": "23aafb9d468ebbd6c24e2739bfe6d0e51766892a27296398e70b9736e17b946d695658dd783604329d580ad89ba80bc8b3c59b18c389ff30ac735565087318c0",
          "sha256": "284c17a5f98c8462ecb9ba02ae761909183fc1e853656b7d672d9abbab5a21c3",
          "sha1": "b525bdf3cbc6b7900252f61ccede193e0a7535fd",
          "md5": "2cbc7f3ccb5e936010d7fa3214d8b0f5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-i18n-1.2-sources.jar",
          "url": "echosvg-i18n-1.2-sources.jar",
          "size": 12492,
          "sha512": "960301cfc43beb15cd1371688e5225c9ea17a478d486f4654a23d52600e3fde5f2f99625bbcd382cf3419457cccb2ac4cb43dfc4167f6f59dcf6661157b79119",
          "sha256": "723b1dcd505da1d6b5d0952055eb1ba449397a29774d8c088fc237dbf5ee17cf",
          "sha1": "67ba71ed89aad34463eca5ec81b89423c841875b",
          "md5": "70ce8ae183a9394387af2a55775e1f28"
        }
      ]
    }
  ]
}
