{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-dom",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-css",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "xalan",
          "module": "xalan",
          "version": {
            "requires": "2.7.2"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.4"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-dom-0.1.jar",
          "url": "echosvg-dom-0.1.jar",
          "size": 188656,
          "sha512": "5b8da25268f78d76898956999f701e0ba7da42f41ca45d91a172922990fd080322ac28c17aa1e7f94b2e0c87b0ed40004efcb50587bfe40a56cad661be300a1e",
          "sha256": "7477733f7f5306d8f5404bdb2194504876fcca32fe2a827e99c182aed2ab8eeb",
          "sha1": "90e54bffa3291dbe1c50d6a4dfd135ddb642a5f4",
          "md5": "9239810fff9ebf6a0de72a085e0d5b6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-css",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "xalan",
          "module": "xalan",
          "version": {
            "requires": "2.7.2"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.4"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-dom-0.1.jar",
          "url": "echosvg-dom-0.1.jar",
          "size": 188656,
          "sha512": "5b8da25268f78d76898956999f701e0ba7da42f41ca45d91a172922990fd080322ac28c17aa1e7f94b2e0c87b0ed40004efcb50587bfe40a56cad661be300a1e",
          "sha256": "7477733f7f5306d8f5404bdb2194504876fcca32fe2a827e99c182aed2ab8eeb",
          "sha1": "90e54bffa3291dbe1c50d6a4dfd135ddb642a5f4",
          "md5": "9239810fff9ebf6a0de72a085e0d5b6a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-dom-0.1-sources.jar",
          "url": "echosvg-dom-0.1-sources.jar",
          "size": 158867,
          "sha512": "0caf7c77be5299861df48717ead39bec50c796d3946294548ce15ba5f8e5a58fa9c9950f5476c4478be28d116261223f70c35515d100cf29d95c1d596629b945",
          "sha256": "7d969693cd5e50e028bef089bbaccf20b1cbfe6188a767e66197eb0800aa7214",
          "sha1": "8c94471409077cc7e07d32d1ca298875489d0551",
          "md5": "23adbcae0b9449c26f8d5573a7b4e3d3"
        }
      ]
    }
  ]
}
