{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-dom",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-css",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "xalan",
          "module": "xalan",
          "version": {
            "requires": "2.7.2"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.4"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-dom-0.1.jar",
          "url": "echosvg-dom-0.1.jar",
          "size": 188667,
          "sha512": "19b35610f2d941ffab4facc87f6e5c76f667b0f5c2f673044ab1d1caf7160faca82eb75b7ac4a9f080e4ed6fa6b83638c72a16a4176c561bd1b0933a03648f82",
          "sha256": "26e1ec3f4170d5d0c6a01b0c56f2af9e707a3a5e65f0e21af2a20cb922ef099b",
          "sha1": "f94c6bb848f04b9deeb0a1494ba932b3c8ea913a",
          "md5": "eab9792fde994c8a33d94842b7b4e073"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-css",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "xalan",
          "module": "xalan",
          "version": {
            "requires": "2.7.2"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.4"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-dom-0.1.jar",
          "url": "echosvg-dom-0.1.jar",
          "size": 188667,
          "sha512": "19b35610f2d941ffab4facc87f6e5c76f667b0f5c2f673044ab1d1caf7160faca82eb75b7ac4a9f080e4ed6fa6b83638c72a16a4176c561bd1b0933a03648f82",
          "sha256": "26e1ec3f4170d5d0c6a01b0c56f2af9e707a3a5e65f0e21af2a20cb922ef099b",
          "sha1": "f94c6bb848f04b9deeb0a1494ba932b3c8ea913a",
          "md5": "eab9792fde994c8a33d94842b7b4e073"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-dom-0.1-sources.jar",
          "url": "echosvg-dom-0.1-sources.jar",
          "size": 158867,
          "sha512": "5e01a45fdde257043b20ec4f3b443fbb6be467c6b1448269d77c92a003fb87c975521e6369ee090916b27e1b1bfd7589de3cc9cc1ed583e81a84ba198be4c960",
          "sha256": "54de63e24d03a67792da06f468ed1568c319a3e661a00f23c877900db1c7c9b0",
          "sha1": "b251614ee5eff0fad764a6454166eaea146f71ac",
          "md5": "2578ba10ccec73122342529a4f3cd7bd"
        }
      ]
    }
  ]
}
