{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-svggen",
    "version": "1.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "1.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svggen-1.2.5.jar",
          "url": "echosvg-svggen-1.2.5.jar",
          "size": 235328,
          "sha512": "a888e3e21a5b35305733ac77dca65544aa956c1e46a9a1734198faf0865e4abfa7cb6416e389a0f387c4e00bb9cfc52b435d9e0163901aec3e20702d3505ea96",
          "sha256": "52d328dcc81dc1333f925411cbb1dd3a65b0de5a975ac7578db764a538d04ea3",
          "sha1": "d4ff18766b3a155afd3bf8eac88ef4879dd5a0c8",
          "md5": "fab664b3dee9101e76608a0555357505"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-codec",
          "version": {
            "requires": "1.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svggen-1.2.5.jar",
          "url": "echosvg-svggen-1.2.5.jar",
          "size": 235328,
          "sha512": "a888e3e21a5b35305733ac77dca65544aa956c1e46a9a1734198faf0865e4abfa7cb6416e389a0f387c4e00bb9cfc52b435d9e0163901aec3e20702d3505ea96",
          "sha256": "52d328dcc81dc1333f925411cbb1dd3a65b0de5a975ac7578db764a538d04ea3",
          "sha1": "d4ff18766b3a155afd3bf8eac88ef4879dd5a0c8",
          "md5": "fab664b3dee9101e76608a0555357505"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-svggen-1.2.5-sources.jar",
          "url": "echosvg-svggen-1.2.5-sources.jar",
          "size": 243646,
          "sha512": "b798fe4a7ad345bd573cef5dc521441efdb152427ee23f1ca45ae3932909b3705b538316ef10e38ab2bc168f7b2f5fe82b5092b5dcb98c8d2e486cae513ab095",
          "sha256": "732a86e5d18d9239f99340888cf37763930aa80f7d1c66bb432c2afd43b5ec7d",
          "sha1": "1df0bb1890d33a3fd6931c2af56f53a549a8c278",
          "md5": "53a521fb61df6bceaa2a8a377b2766ab"
        }
      ]
    }
  ]
}
