{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-slideshow",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-slideshow-1.1.1.jar",
          "url": "echosvg-slideshow-1.1.1.jar",
          "size": 16431,
          "sha512": "dced4ad465918d7532da5b9137fd610a841cddfe001816bcfcd7e45b25fc4799503f8e53bc3a3bf7da7c4cb97919cb1d53f8bda3224ed4de18d2c06c747a3b61",
          "sha256": "6abb4f48b4b0afb03b7afdb1dca1d8fa63d0f8b8be8f744dc551c6b8c407c780",
          "sha1": "12405b8ce43c136d01207ee87baa32f1f7047ce0",
          "md5": "03bd25547c9730a78af7ea47a5b54126"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-slideshow-1.1.1.jar",
          "url": "echosvg-slideshow-1.1.1.jar",
          "size": 16431,
          "sha512": "dced4ad465918d7532da5b9137fd610a841cddfe001816bcfcd7e45b25fc4799503f8e53bc3a3bf7da7c4cb97919cb1d53f8bda3224ed4de18d2c06c747a3b61",
          "sha256": "6abb4f48b4b0afb03b7afdb1dca1d8fa63d0f8b8be8f744dc551c6b8c407c780",
          "sha1": "12405b8ce43c136d01207ee87baa32f1f7047ce0",
          "md5": "03bd25547c9730a78af7ea47a5b54126"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-slideshow-1.1.1-sources.jar",
          "url": "echosvg-slideshow-1.1.1-sources.jar",
          "size": 10119,
          "sha512": "a8931eaab89d51ba0357ec51ee8fada217943fb0ac115b630fb286cb666474b9cbb0db17b1d289ac08ffe6901d9115faea75c41e4e3bba05fb7280dca217a915",
          "sha256": "d0a5f462aa34a7c7f75eec6189b18ee98e48dc7a1c0005aa44dbf613566f02ea",
          "sha1": "49a359b880a65994ec6604ebe1bfc3180bcf6245",
          "md5": "c9511ccefa2cc19ef2d8b2504ca91a99"
        }
      ]
    }
  ]
}
