{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-transcoder",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svggen",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-transcoder-0.1.jar",
          "url": "echosvg-transcoder-0.1.jar",
          "size": 237933,
          "sha512": "160178593be34682aad421f9fe667412aed66e2aacf2b132d9af13e8602ef98ab42a2c24fbc20d73d371ba522128f4b674049e56a9cfba1fd3ebd7d5b5b69b08",
          "sha256": "4f68a5673762c3247cde12b2950ba5d04491ff4bed0d3bbaf22a16d1a7965af8",
          "sha1": "9db2c85267ad7018137d53a9a53653ca90bca176",
          "md5": "ef902bb1ed481bcf71097848d6eff2ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svggen",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-transcoder-0.1.jar",
          "url": "echosvg-transcoder-0.1.jar",
          "size": 237933,
          "sha512": "160178593be34682aad421f9fe667412aed66e2aacf2b132d9af13e8602ef98ab42a2c24fbc20d73d371ba522128f4b674049e56a9cfba1fd3ebd7d5b5b69b08",
          "sha256": "4f68a5673762c3247cde12b2950ba5d04491ff4bed0d3bbaf22a16d1a7965af8",
          "sha1": "9db2c85267ad7018137d53a9a53653ca90bca176",
          "md5": "ef902bb1ed481bcf71097848d6eff2ae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-transcoder-0.1-sources.jar",
          "url": "echosvg-transcoder-0.1-sources.jar",
          "size": 203570,
          "sha512": "afee03bdd3f5f9cd48ecf93df4ff69ba6565783f563eb6e7884b26e321e6ea901ce2fa85696d00c59331ec8e792e2cfb04329aafa39b35d7cbb0902179bf0fe5",
          "sha256": "c9dea3267a2b7bc5c65dc785477cb88168f95ddec5b2a9816bc49817ec31e76e",
          "sha1": "eb59f03278272be28e1b041233fdf6a095726121",
          "md5": "fdbab948c6a52292c83cfbb8f583dc6d"
        }
      ]
    }
  ]
}
