{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-svgpp",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svgpp-0.1.jar",
          "url": "echosvg-svgpp-0.1.jar",
          "size": 18464,
          "sha512": "61d00a8434f54b660e06de14fe3bd85be7e7957173286e4295b946b0aeffd8c443a89850a9d7dedff115c02719a540d4591e05b3d8e5040a958145f7017bcac8",
          "sha256": "91802f65002a1af417f8e4f1e3d48cb17d6807c14ed9e91a62db4af2f12f4dc4",
          "sha1": "addb798e9ccd122d069ee4f1a78c4231122865d2",
          "md5": "0a0119ebc59f0bb8893c6f2497282b65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svgpp-0.1.jar",
          "url": "echosvg-svgpp-0.1.jar",
          "size": 18464,
          "sha512": "61d00a8434f54b660e06de14fe3bd85be7e7957173286e4295b946b0aeffd8c443a89850a9d7dedff115c02719a540d4591e05b3d8e5040a958145f7017bcac8",
          "sha256": "91802f65002a1af417f8e4f1e3d48cb17d6807c14ed9e91a62db4af2f12f4dc4",
          "sha1": "addb798e9ccd122d069ee4f1a78c4231122865d2",
          "md5": "0a0119ebc59f0bb8893c6f2497282b65"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-svgpp-0.1-sources.jar",
          "url": "echosvg-svgpp-0.1-sources.jar",
          "size": 9510,
          "sha512": "198cac1602cfa1337c111305236851eff4569578b4c50b77257e82a294c6820e2e516804fdf264015f06d9de2e9d45f4346c1a0354d0aaf1f74ec10d0d2b5c1f",
          "sha256": "cc2e4bf1dfe2ace936efcfe3f4e64a8e470ce2e2707af66d5c33c4d1e6169eb9",
          "sha1": "1156e8338b3d75aa09278ad2f8eca0993f761f31",
          "md5": "9516e4bf6d6116719f49b97644c1fb5a"
        }
      ]
    }
  ]
}
