{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-transcoder-tosvg",
    "version": "2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-api",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svggen",
          "version": {
            "requires": "2.3"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-transcoder-tosvg-2.3.jar",
          "url": "echosvg-transcoder-tosvg-2.3.jar",
          "size": 61099,
          "sha512": "eb7a1c20b55e4a72ff7ca18b4467a4c6003955d4ad37125755444d7c403b8090ec648358f28da534367325148643f59ce52c46239c989c4034a4f6a7bd555ba6",
          "sha256": "6dcd4b2cbc93b9a9a706f9d5b155b4f27fa2a0a3c441d0b1e32c78934c5f307e",
          "sha1": "7f1ffd8d0781c818bd5e76040fa8498501be4329",
          "md5": "db8b70d02292c49a9759dad1df81c998"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-api",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svggen",
          "version": {
            "requires": "2.3"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-transcoder-tosvg-2.3.jar",
          "url": "echosvg-transcoder-tosvg-2.3.jar",
          "size": 61099,
          "sha512": "eb7a1c20b55e4a72ff7ca18b4467a4c6003955d4ad37125755444d7c403b8090ec648358f28da534367325148643f59ce52c46239c989c4034a4f6a7bd555ba6",
          "sha256": "6dcd4b2cbc93b9a9a706f9d5b155b4f27fa2a0a3c441d0b1e32c78934c5f307e",
          "sha1": "7f1ffd8d0781c818bd5e76040fa8498501be4329",
          "md5": "db8b70d02292c49a9759dad1df81c998"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-transcoder-tosvg-2.3-sources.jar",
          "url": "echosvg-transcoder-tosvg-2.3-sources.jar",
          "size": 50012,
          "sha512": "80e6c9c2cbf110b1c45db85b5b6d9344819f80128ac73a2f91484dad7bf14d564fe84c5aeedbcd714389048c27b848bfec8b2e0b39c584b19207ce2e78d62201",
          "sha256": "845d0fad1282f19014ea393e4a1ef8fd8281f4a4b90871189438393251f5ab17",
          "sha1": "b6dcb296baadec0ef306b7a05465f5d7d891eab7",
          "md5": "15644133894e7640ca7d50319088ff54"
        }
      ]
    }
  ]
}
