{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-swing",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-swing-1.1.1.jar",
          "url": "echosvg-swing-1.1.1.jar",
          "size": 196714,
          "sha512": "55aeb03ff42008b5acd8f6d039eee5dc213dd3572ba8c48c6451a4e97e5897f8b746fa807dfeabdd3e8724e2d16ba41562d0966849f89ac6085026cd44ec0aa6",
          "sha256": "ebe8ee6f3035e6411aaa1e1a51554c9aee66b650f4c39f977f6bdb8610e48359",
          "sha1": "26eb9600735416ef47bf45176d620ef7314d478a",
          "md5": "fe7a26939f34dcb218e752765745926a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "xml-apis",
          "module": "xml-apis",
          "version": {
            "requires": "1.4.01"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-swing-1.1.1.jar",
          "url": "echosvg-swing-1.1.1.jar",
          "size": 196714,
          "sha512": "55aeb03ff42008b5acd8f6d039eee5dc213dd3572ba8c48c6451a4e97e5897f8b746fa807dfeabdd3e8724e2d16ba41562d0966849f89ac6085026cd44ec0aa6",
          "sha256": "ebe8ee6f3035e6411aaa1e1a51554c9aee66b650f4c39f977f6bdb8610e48359",
          "sha1": "26eb9600735416ef47bf45176d620ef7314d478a",
          "md5": "fe7a26939f34dcb218e752765745926a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-swing-1.1.1-sources.jar",
          "url": "echosvg-swing-1.1.1-sources.jar",
          "size": 100671,
          "sha512": "92aa76c6b971c5f4183e1ca83ba3cb5f573ac70358dd1cfa43ca9ea0e16520ebf0a359df7e2b4aec0a349f0d1f3b81abba9e02d7ee3ef8589f797013d679433d",
          "sha256": "366ee5cd9cdc5a255cefb9b1dc6c218ab9b3fb0b2dba9f87eb035bf1d70f8ad5",
          "sha1": "1d7c00ca11ce088fb46417a13a4a5be99a034ce5",
          "md5": "c5001c380b34b508b86676c38744d3ad"
        }
      ]
    }
  ]
}
