{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-xml",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.3"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-xml-0.3.jar",
          "url": "echosvg-xml-0.3.jar",
          "size": 32222,
          "sha512": "1ec6a37fb94c8e4e33060c1b8fd91f9c2c9a017459614a00898fd4ff54018da2c24f22c67e5add41bf01dbe98dfbffd95a3c623c8585aeb5a5911bb98f9d5da2",
          "sha256": "3a05339b14b827c36c947e0248b23897bd4445f8c3ece0ec411760ddc07cf592",
          "sha1": "5d27f032b3ddb88ddc3588a74e0a3a19aadf7373",
          "md5": "1665bb7dc99ee4c600f4562bea53cf5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.3"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-xml-0.3.jar",
          "url": "echosvg-xml-0.3.jar",
          "size": 32222,
          "sha512": "1ec6a37fb94c8e4e33060c1b8fd91f9c2c9a017459614a00898fd4ff54018da2c24f22c67e5add41bf01dbe98dfbffd95a3c623c8585aeb5a5911bb98f9d5da2",
          "sha256": "3a05339b14b827c36c947e0248b23897bd4445f8c3ece0ec411760ddc07cf592",
          "sha1": "5d27f032b3ddb88ddc3588a74e0a3a19aadf7373",
          "md5": "1665bb7dc99ee4c600f4562bea53cf5d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-xml-0.3-sources.jar",
          "url": "echosvg-xml-0.3-sources.jar",
          "size": 23298,
          "sha512": "a1bf6f981799395e2891fe3fbb5f6d59f8d8ae90dfcfec09529f06710750e31684b6cbd1162867aa247e91b31fc0f0d66d83a63b6e3b98269412a9757f828b05",
          "sha256": "40ec07363fb013995815e23fff0d30543e64856a01c1534b12a98f141ef9126e",
          "sha1": "3efa9bc2a0e0815ba728c7c3751813b9e17d6fbe",
          "md5": "9346256a14880780be2c5b6bb533d816"
        }
      ]
    }
  ]
}
