{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-gui-util",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-gui-util-0.1.jar",
          "url": "echosvg-gui-util-0.1.jar",
          "size": 178307,
          "sha512": "37cd393b23303f0142bf1c4d1a30d56076a4f2b952e1ef5653a622930ad67ccb3050d45401ce866bfbadf0d80b33b3c0b60045598940ff6f87e02c5d45350213",
          "sha256": "467298b2d7d20027f04290eb7ff12baad48ab9eb4b53d9a4f89f25afa02e982e",
          "sha1": "69acc1c4483278a81e4f3e4087f1d29daea12c60",
          "md5": "70d8f78df017948ea2dad83f25064ac3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-gui-util-0.1.jar",
          "url": "echosvg-gui-util-0.1.jar",
          "size": 178307,
          "sha512": "37cd393b23303f0142bf1c4d1a30d56076a4f2b952e1ef5653a622930ad67ccb3050d45401ce866bfbadf0d80b33b3c0b60045598940ff6f87e02c5d45350213",
          "sha256": "467298b2d7d20027f04290eb7ff12baad48ab9eb4b53d9a4f89f25afa02e982e",
          "sha1": "69acc1c4483278a81e4f3e4087f1d29daea12c60",
          "md5": "70d8f78df017948ea2dad83f25064ac3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-gui-util-0.1-sources.jar",
          "url": "echosvg-gui-util-0.1-sources.jar",
          "size": 119824,
          "sha512": "cdfef6557ef47f9eade60b1beb59d1f963750440cb59ad974384019c3d31a27e88a2bf50249304e70c4bf704a61c8eeaa96604943627b852a0e48b3fdb8bdd07",
          "sha256": "85679251518de720fc4633dd111ca065ad11e1fbc98f6f940ba739df3914f4ae",
          "sha1": "8e49d6f360bfacd7a405c207b91da71d06d7ccf1",
          "md5": "3ed93b78ca7eddd9a0491b97ba6afadf"
        }
      ]
    }
  ]
}
