{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-gui-util",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-gui-util-0.1.jar",
          "url": "echosvg-gui-util-0.1.jar",
          "size": 178305,
          "sha512": "106d4e93ec9f84e338ce5055fa4b54750d37de89bfbdfa20a904fae3314ec30e18ed423e171c077da6647e3e530dcebb58a4a6a9fe5f5706b2174b9dc8c18bf7",
          "sha256": "45b0ec08e196132c1fdfc465a23e58cd4e8b87e6aeef113d9cad830ee858bddd",
          "sha1": "001c80d6013dda9c0f73639d2014d3e014c2a03d",
          "md5": "d52307f1813bcab04c69878d6987a0fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-gui-util-0.1.jar",
          "url": "echosvg-gui-util-0.1.jar",
          "size": 178305,
          "sha512": "106d4e93ec9f84e338ce5055fa4b54750d37de89bfbdfa20a904fae3314ec30e18ed423e171c077da6647e3e530dcebb58a4a6a9fe5f5706b2174b9dc8c18bf7",
          "sha256": "45b0ec08e196132c1fdfc465a23e58cd4e8b87e6aeef113d9cad830ee858bddd",
          "sha1": "001c80d6013dda9c0f73639d2014d3e014c2a03d",
          "md5": "d52307f1813bcab04c69878d6987a0fc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-gui-util-0.1-sources.jar",
          "url": "echosvg-gui-util-0.1-sources.jar",
          "size": 119817,
          "sha512": "0ddc244c8828f95bc13e895015545e267ee016273607ddb400cf61b1e569d1ddc2d148f3006c2921a743548d9de4bb9fda6a54f3d2f5582549e94d39c8b70808",
          "sha256": "07e612d30a60576b4b677c98fe9f1b6613d28b3e2f2392a4eb4026f73a134fce",
          "sha1": "0ce3d2c2fda46fae1656f3a6d61c5825c4da5d02",
          "md5": "629226d9b595da2b8b5f00aae60804d1"
        }
      ]
    }
  ]
}
