{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-gvt",
    "version": "2.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-gvt-2.2.1.jar",
          "url": "echosvg-gvt-2.2.1.jar",
          "size": 198138,
          "sha512": "b9db3492dd0b573a601a64953a295c60002a14940e02c0c3e22fdd868fae6839469b9cfacc84b97494d4d02dcb08293ade0a785d89c9aebc7053c1a7450698b4",
          "sha256": "333f797d4c635aea01e848f21d2dcd272b2c3e37fa181f2dc37edb72a3cc8f82",
          "sha1": "6ab864ecf87c2492bf0a80e53566eb765fb1eec6",
          "md5": "af4604a41e1a4c9398dd4923b7ea094d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-gvt-2.2.1.jar",
          "url": "echosvg-gvt-2.2.1.jar",
          "size": 198138,
          "sha512": "b9db3492dd0b573a601a64953a295c60002a14940e02c0c3e22fdd868fae6839469b9cfacc84b97494d4d02dcb08293ade0a785d89c9aebc7053c1a7450698b4",
          "sha256": "333f797d4c635aea01e848f21d2dcd272b2c3e37fa181f2dc37edb72a3cc8f82",
          "sha1": "6ab864ecf87c2492bf0a80e53566eb765fb1eec6",
          "md5": "af4604a41e1a4c9398dd4923b7ea094d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-gvt-2.2.1-sources.jar",
          "url": "echosvg-gvt-2.2.1-sources.jar",
          "size": 201888,
          "sha512": "70fcb885cdfa2dfad5aa8d0d23217c2aa81e6d440822007a8bfa92e628ef2e8bd22da8f37614527c267881b3061329a0a5be1322ab05c26251ca278e1f53a926",
          "sha256": "49cb2d85b0454363f16e969205cb3e56eb979cbdeb74c433272f2f501decb287",
          "sha1": "85ecc53fbcd42d78bc0ed5f949e4752f4045cc1c",
          "md5": "7824e68809d636bb8da22694423ad553"
        }
      ]
    }
  ]
}
