{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-test",
    "version": "2.0-pre1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-swing",
          "version": {
            "requires": "2.0-pre1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-test-2.0-pre1.jar",
          "url": "echosvg-test-2.0-pre1.jar",
          "size": 31618,
          "sha512": "3c325958f1516e01b485c469ce1aa267893f6d632cea909fe90ca9cd9a846784fb5ccdd7bd509478f5abbce258e1d65de44a06440ca2e7f4d54b91a754ae80eb",
          "sha256": "f9f31b81a8e37cd91e9c2921e937d78812f8641960664bbb1a3d79fc7417de4a",
          "sha1": "2cb3bd16535b3448dc32040faf142003865fc9be",
          "md5": "f5d04c850bfb8870c529e51e6c188027"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-extension",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-test-util",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-codec",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-swing",
          "version": {
            "requires": "2.0-pre1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-test-2.0-pre1.jar",
          "url": "echosvg-test-2.0-pre1.jar",
          "size": 31618,
          "sha512": "3c325958f1516e01b485c469ce1aa267893f6d632cea909fe90ca9cd9a846784fb5ccdd7bd509478f5abbce258e1d65de44a06440ca2e7f4d54b91a754ae80eb",
          "sha256": "f9f31b81a8e37cd91e9c2921e937d78812f8641960664bbb1a3d79fc7417de4a",
          "sha1": "2cb3bd16535b3448dc32040faf142003865fc9be",
          "md5": "f5d04c850bfb8870c529e51e6c188027"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-test-2.0-pre1-sources.jar",
          "url": "echosvg-test-2.0-pre1-sources.jar",
          "size": 19695,
          "sha512": "a37f82c8acaeac0fdb1095d6f2e05cfee583a1b4a354c1f715709b800dd5ff62072aa368320bf6e93ca7a5e13f8e70a061e4e507c6cb778c08989d96ecab19f8",
          "sha256": "eb4b0b300254b023e6db05c6431275b3e2aff25c5b5111f7d29f2554a5eb5bcc",
          "sha1": "9b2d1b6936a4a7dd9bec13fe6dbc8257a067240b",
          "md5": "d9c114378ce66da8b5fbe792c60e148e"
        }
      ]
    }
  ]
}
