{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-script",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.7.15"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-script-2.0.jar",
          "url": "echosvg-script-2.0.jar",
          "size": 27214,
          "sha512": "c6ce912a53e8157a7394a853d5d3d6f5851524b8a49996a8dafed5e3df73ed61e42843ff9b564436dfc130bc98f93b3cd40ca179b89aaf75717a007ec2caec38",
          "sha256": "3b48c26c01a4f249cec8fc950c9925f927442f0eeeaaa1ffea85e0e339713aeb",
          "sha1": "da761897a3006e076d0b9f9bd0499ff69ba581fe",
          "md5": "ce2f71f86bc9a8c1f359040b7be1d938"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.7.15"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-script-2.0.jar",
          "url": "echosvg-script-2.0.jar",
          "size": 27214,
          "sha512": "c6ce912a53e8157a7394a853d5d3d6f5851524b8a49996a8dafed5e3df73ed61e42843ff9b564436dfc130bc98f93b3cd40ca179b89aaf75717a007ec2caec38",
          "sha256": "3b48c26c01a4f249cec8fc950c9925f927442f0eeeaaa1ffea85e0e339713aeb",
          "sha1": "da761897a3006e076d0b9f9bd0499ff69ba581fe",
          "md5": "ce2f71f86bc9a8c1f359040b7be1d938"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-script-2.0-sources.jar",
          "url": "echosvg-script-2.0-sources.jar",
          "size": 29811,
          "sha512": "3704598bedd0ebb6ca21c99c94f90d5c78282de228a3cacf14b3b7b08df72b5813e958959f4c4dba41b790f5fe4ec3feb581c29d57dab68a6506ce84bdffdb30",
          "sha256": "8d1a31030809c9be04736541b2d7a6e14fc421a0829e880d9ef4cadd6fda72ae",
          "sha1": "32518d487de408909b9168b259a5cc299f94a2ae",
          "md5": "4ec859d9905d4c19b51ef5489873e9d5"
        }
      ]
    }
  ]
}
