{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-constants",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "echosvg-constants-0.2.jar",
          "url": "echosvg-constants-0.2.jar",
          "size": 6870,
          "sha512": "0cbfdefe74d17617721c1e1b6d57a9ff34e604272b439e400a8965c9797096688ad564e98c10e1f2354708cf76efcabc4da86351e50053f85728be9ea4411787",
          "sha256": "7bcd75a57a4fb1459411a73d33ab2e9af48759030a0aecd0014059c8387086cb",
          "sha1": "c6bb00fbae7eb01c012bb3f3f00120534ec1205e",
          "md5": "50693b83675ce0f7154b682664d825c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-constants-0.2.jar",
          "url": "echosvg-constants-0.2.jar",
          "size": 6870,
          "sha512": "0cbfdefe74d17617721c1e1b6d57a9ff34e604272b439e400a8965c9797096688ad564e98c10e1f2354708cf76efcabc4da86351e50053f85728be9ea4411787",
          "sha256": "7bcd75a57a4fb1459411a73d33ab2e9af48759030a0aecd0014059c8387086cb",
          "sha1": "c6bb00fbae7eb01c012bb3f3f00120534ec1205e",
          "md5": "50693b83675ce0f7154b682664d825c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-constants-0.2-sources.jar",
          "url": "echosvg-constants-0.2-sources.jar",
          "size": 7276,
          "sha512": "aff145af34ed2cb494688a654c3dbb03ca5ecd7b2a83a135fb759a8ffb115898bf2609c8359cdb97307336276b86e4a7e33643a229e0c59e159f2e37f1958f4d",
          "sha256": "5d3878d6f22e512dc2273e4e6673a5a64de6597fb4c6b53dfb91aaf731c7459f",
          "sha1": "1cc82394473192a651eebfa473135e22712bd8c7",
          "md5": "75618435333f5489017be21122ea1859"
        }
      ]
    }
  ]
}
