{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-constants",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "echosvg-constants-0.1.jar",
          "url": "echosvg-constants-0.1.jar",
          "size": 6846,
          "sha512": "d85c03f305fbafa31f09ea7870eb9a9cf1ab242f4bd182e4b86b41b43768a9c839a6737574507ff1fc6ad9379d1ba20b45c5992ebfa1c6a51e20b88b9400d425",
          "sha256": "b9175462d6558dc78705f7778494f215ee5c11200e5b14f4f756aa67df66e1eb",
          "sha1": "fdfaa27c8d319ab41b47924db21f88f29d01b7f7",
          "md5": "4b795d7d699fc2f0a4455379d41bc482"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-constants-0.1.jar",
          "url": "echosvg-constants-0.1.jar",
          "size": 6846,
          "sha512": "d85c03f305fbafa31f09ea7870eb9a9cf1ab242f4bd182e4b86b41b43768a9c839a6737574507ff1fc6ad9379d1ba20b45c5992ebfa1c6a51e20b88b9400d425",
          "sha256": "b9175462d6558dc78705f7778494f215ee5c11200e5b14f4f756aa67df66e1eb",
          "sha1": "fdfaa27c8d319ab41b47924db21f88f29d01b7f7",
          "md5": "4b795d7d699fc2f0a4455379d41bc482"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-constants-0.1-sources.jar",
          "url": "echosvg-constants-0.1-sources.jar",
          "size": 7223,
          "sha512": "15ef15cacb1d46104aeec6ee1248065b3083e4cdca4e69af14ae9ff9ca263ce48a0eb823968c3c3be505b28b4b5f38059e904c0f69ce32dd2c44b0656e5aae9a",
          "sha256": "36dea53df08a067a69f415f5b2baa357b137c4a6866bfe463bdf4711130348f6",
          "sha1": "6ebb5b9e68639650e8b444201942d1b3af4965ea",
          "md5": "514848463332d83a0a71ca0bdece97b8"
        }
      ]
    }
  ]
}
