{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-svggen",
    "version": "0.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svggen-0.3.2.jar",
          "url": "echosvg-svggen-0.3.2.jar",
          "size": 231198,
          "sha512": "4986d90e968a9386c9bfc8ac9159d128de1343d5bc86bc73dbaa8a984528f7ffcc40b4eee44882e5ddac39ec772e559b8b1baf0741ad196cfb142bd60c86df4b",
          "sha256": "fe337bdd83b74b087ea6f81191c3f544e268943808c6d8478c8c47362d0bcb3d",
          "sha1": "cbfbf0f6396b48381c4d84a04d3060d4c138ec43",
          "md5": "e734c6f32062ecf5e2326591e8d6ca0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svggen-0.3.2.jar",
          "url": "echosvg-svggen-0.3.2.jar",
          "size": 231198,
          "sha512": "4986d90e968a9386c9bfc8ac9159d128de1343d5bc86bc73dbaa8a984528f7ffcc40b4eee44882e5ddac39ec772e559b8b1baf0741ad196cfb142bd60c86df4b",
          "sha256": "fe337bdd83b74b087ea6f81191c3f544e268943808c6d8478c8c47362d0bcb3d",
          "sha1": "cbfbf0f6396b48381c4d84a04d3060d4c138ec43",
          "md5": "e734c6f32062ecf5e2326591e8d6ca0b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-svggen-0.3.2-sources.jar",
          "url": "echosvg-svggen-0.3.2-sources.jar",
          "size": 240883,
          "sha512": "aa9579285243bd3cdd325e7a40809687b4ae7f720670f41747ede4db9dbde57f755ca5c6b0e7122c4ce6278a0cfbcfc93e85d2be3acc6818248d34fdb3e31e8a",
          "sha256": "58bca0b7826c5fa4ce254613945483b33a444a425dc267bf7c16b9bebfb0b651",
          "sha1": "6da05b41003941cca39ac11061adfec70807b24f",
          "md5": "8483c9dc635982d03aeb7b163cf3bd14"
        }
      ]
    }
  ]
}
