{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-xml",
    "version": "2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-xml-2.5.jar",
          "url": "echosvg-xml-2.5.jar",
          "size": 32554,
          "sha512": "9215dbde541ad174c887afcd60e61ad75d35a2a6687dd9efd5b13547dec2698346f41e9ad863625994b8bb529c2f801790d40e98b5db56082dd43796efb30ee4",
          "sha256": "bda36d29b9f5ce845d56384b3d8309184b03c3564353322ac84110497f56643e",
          "sha1": "70478c56d8ccac6ed3933f0de7eae39c815cde93",
          "md5": "319dcd2ccd4134c061ec4e4bb8f818da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-xml-2.5.jar",
          "url": "echosvg-xml-2.5.jar",
          "size": 32554,
          "sha512": "9215dbde541ad174c887afcd60e61ad75d35a2a6687dd9efd5b13547dec2698346f41e9ad863625994b8bb529c2f801790d40e98b5db56082dd43796efb30ee4",
          "sha256": "bda36d29b9f5ce845d56384b3d8309184b03c3564353322ac84110497f56643e",
          "sha1": "70478c56d8ccac6ed3933f0de7eae39c815cde93",
          "md5": "319dcd2ccd4134c061ec4e4bb8f818da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-xml-2.5-sources.jar",
          "url": "echosvg-xml-2.5-sources.jar",
          "size": 23643,
          "sha512": "3ffcb90e8388d9c89e2bbb5844c2be12945ea75465bb61a391573ee4684e4336ea9938d35f0622251ead1e834e231a47d3969b12271ef39c4f8e2d2ba3b6d1a7",
          "sha256": "41b499184065e1e29ddb61557ed44284768cbe917c714550404bef950bf01c59",
          "sha1": "21f00a13af71d5acd1c5d44f87715d75748f8dcb",
          "md5": "7d577cae3e991c966ed8598f164d460c"
        }
      ]
    }
  ]
}
