{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-svg-dom",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svg-dom-1.1.jar",
          "url": "echosvg-svg-dom-1.1.jar",
          "size": 73599,
          "sha512": "37c75434ce9d95be930936e56215c819fc08cf915053a3a4484ab8d7a7a625833ee9dd26ad97e04ed2192766b011602911ceebb0a79387e1dd468b552000ceca",
          "sha256": "18db3df155d8b6e59fe02145f5855b9eafbe367e867a1c4599aee2ff6e4911f4",
          "sha1": "d4d0d751e9d543c831e8a3406b56f15c8abe9022",
          "md5": "78e6acc1922d79c85553047a0a82c5f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "xml-apis",
          "module": "xml-apis",
          "version": {
            "requires": "1.4.01"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svg-dom-1.1.jar",
          "url": "echosvg-svg-dom-1.1.jar",
          "size": 73599,
          "sha512": "37c75434ce9d95be930936e56215c819fc08cf915053a3a4484ab8d7a7a625833ee9dd26ad97e04ed2192766b011602911ceebb0a79387e1dd468b552000ceca",
          "sha256": "18db3df155d8b6e59fe02145f5855b9eafbe367e867a1c4599aee2ff6e4911f4",
          "sha1": "d4d0d751e9d543c831e8a3406b56f15c8abe9022",
          "md5": "78e6acc1922d79c85553047a0a82c5f2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-svg-dom-1.1-sources.jar",
          "url": "echosvg-svg-dom-1.1-sources.jar",
          "size": 69465,
          "sha512": "81fd60c49f6e144a77797e61bfa7da4fa3bac0c3e4237077da40a2832080669bc7a9cb1203d27283185174e64cc91dfc0198fb76f632848b89dc8ff8a18e4e9c",
          "sha256": "46d4e8bce1d43f93dafcd3948b831cb0297ce7a4d365fd6da6e0ef4c69c473b4",
          "sha1": "781f7690684cca3ec3a7aa219d86215a9e78046c",
          "md5": "86c5a9088f46ea6094b6425c9cc58642"
        }
      ]
    }
  ]
}
