{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-ext",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "echosvg-ext-0.1.jar",
          "url": "echosvg-ext-0.1.jar",
          "size": 8780,
          "sha512": "10b4c83e25e78c2c7caf2cca87db01cead10525aed04669b764776b53e30467e4446a1af96fcfc4b097cb01ac5b4a042944bffaa012a5e9279105860bc84d9e9",
          "sha256": "647e38ada00bd5f38bbe77d7e8928c4866bf039187ef019fdb72619ca58df6c3",
          "sha1": "adf73e303f08a4eaf99c5de386e4caa28e9c4ac4",
          "md5": "b02318afefa7db0f9a9d10126a9360b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-ext-0.1.jar",
          "url": "echosvg-ext-0.1.jar",
          "size": 8780,
          "sha512": "10b4c83e25e78c2c7caf2cca87db01cead10525aed04669b764776b53e30467e4446a1af96fcfc4b097cb01ac5b4a042944bffaa012a5e9279105860bc84d9e9",
          "sha256": "647e38ada00bd5f38bbe77d7e8928c4866bf039187ef019fdb72619ca58df6c3",
          "sha1": "adf73e303f08a4eaf99c5de386e4caa28e9c4ac4",
          "md5": "b02318afefa7db0f9a9d10126a9360b0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-ext-0.1-sources.jar",
          "url": "echosvg-ext-0.1-sources.jar",
          "size": 14552,
          "sha512": "5171377da83fe6d7eb6b361b5bcc8373dbb5f8515f45efad4f58638703f70ffac0ad3e4c19993b734acf55bca144f0bd01304af0b79f8d2b5ea84e5ee76561dc",
          "sha256": "317d5cc7e7396b3c7f16629f78525b647975e12959930d91b8e78cc56dc4cf63",
          "sha1": "a86c7fd88f3f101e3bfb2ef86d771cc3d20bcd52",
          "md5": "328f0a74bb0b5e6b78a969cdc5181de3"
        }
      ]
    }
  ]
}
