{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-parser",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.4"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-parser-0.1.jar",
          "url": "echosvg-parser-0.1.jar",
          "size": 76197,
          "sha512": "4355453ddac3cbcccab9d4da5d6b3163b60f9d23cf42e7d4f06d0cd148b00a9a167e86fc792e9bb6f1838bef0c7242369e7f9bbdf70cf59eedbac75cc4676d3b",
          "sha256": "ed4202fbaf0de86d0f6bf18616631590c766ddbba3f99cf6db92c0cf02af4d76",
          "sha1": "12c1deef35381b28c2d66e0abc77b998012b9ed5",
          "md5": "42fe59075e99c5d9d4e9c9045fe8e2e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.4"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-parser-0.1.jar",
          "url": "echosvg-parser-0.1.jar",
          "size": 76197,
          "sha512": "4355453ddac3cbcccab9d4da5d6b3163b60f9d23cf42e7d4f06d0cd148b00a9a167e86fc792e9bb6f1838bef0c7242369e7f9bbdf70cf59eedbac75cc4676d3b",
          "sha256": "ed4202fbaf0de86d0f6bf18616631590c766ddbba3f99cf6db92c0cf02af4d76",
          "sha1": "12c1deef35381b28c2d66e0abc77b998012b9ed5",
          "md5": "42fe59075e99c5d9d4e9c9045fe8e2e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-parser-0.1-sources.jar",
          "url": "echosvg-parser-0.1-sources.jar",
          "size": 82395,
          "sha512": "23ffb5969cb224959c758cc3feeb093790a67b56479e3f01a4512d7a1dd8d214282050f61f872d2dd247211674cc7891f4b5daf2d7e19b80d28aafb48754f9b4",
          "sha256": "ac3bf8de962dfa4bc546ad4d86685d0cb5fd681c53361f0cbc1dc93e0cbadcd4",
          "sha1": "549825786a41d48ea016ddab844fe00b66baa8ad",
          "md5": "f04c93e7cb8e9c2809fa1cef2dfedfb5"
        }
      ]
    }
  ]
}
