{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-ext",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "echosvg-ext-0.3.1.jar",
          "url": "echosvg-ext-0.3.1.jar",
          "size": 8800,
          "sha512": "519f0b6892333ba4b0e32c71b4660db694b7d114d537e67c3077b2afa033a2686567ff6d3db44152ea13b12853ef69382068a8c82cd790740022cdd0bb76cd51",
          "sha256": "771efbc31ac85d82a38f1e71f20c61a019438cfc70c3318478800b9970764e3f",
          "sha1": "4d2fa87d1045e0ea1dcc9edc17f481e9f47d5684",
          "md5": "a403d242d5c450023af4589243c310a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-ext-0.3.1.jar",
          "url": "echosvg-ext-0.3.1.jar",
          "size": 8800,
          "sha512": "519f0b6892333ba4b0e32c71b4660db694b7d114d537e67c3077b2afa033a2686567ff6d3db44152ea13b12853ef69382068a8c82cd790740022cdd0bb76cd51",
          "sha256": "771efbc31ac85d82a38f1e71f20c61a019438cfc70c3318478800b9970764e3f",
          "sha1": "4d2fa87d1045e0ea1dcc9edc17f481e9f47d5684",
          "md5": "a403d242d5c450023af4589243c310a0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-ext-0.3.1-sources.jar",
          "url": "echosvg-ext-0.3.1-sources.jar",
          "size": 14595,
          "sha512": "99cc285b30a4806d601635b93e658bbc01e056c72edcbbf662b42738c2069c6348f34ca6fac9ae9c0b6524f0bcceda7659db2a7d2b1d01e0f23aa55daa100018",
          "sha256": "3b3e7f25febce9a119a7ae1b8e79540900bcbbbb85e4bdcdb337c1f2a4488156",
          "sha1": "1d55c72b3e327ce0a70835896efb3e4c35433a19",
          "md5": "ad98dd7e7440a36cbb8f030740d3eeb0"
        }
      ]
    }
  ]
}
