{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-svgrasterizer",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svgrasterizer-1.1.1.jar",
          "url": "echosvg-svgrasterizer-1.1.1.jar",
          "size": 59000,
          "sha512": "61c5e612b0f3232502558dd89342f36a2c724c37aa0de04716d7fffaa6369da75c66e248505f368165ebc272be57f35833f11451e18b5a4795164cdcc7973042",
          "sha256": "94f7b24ad986e09bcb3baefe71f65b0bde05efbf132ea7035cbb979a20e16624",
          "sha1": "1d9ca5dac7541e9d53c341896740509aff10e6cb",
          "md5": "f4d186210162176739e1f7152a1a5246"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svgrasterizer-1.1.1.jar",
          "url": "echosvg-svgrasterizer-1.1.1.jar",
          "size": 59000,
          "sha512": "61c5e612b0f3232502558dd89342f36a2c724c37aa0de04716d7fffaa6369da75c66e248505f368165ebc272be57f35833f11451e18b5a4795164cdcc7973042",
          "sha256": "94f7b24ad986e09bcb3baefe71f65b0bde05efbf132ea7035cbb979a20e16624",
          "sha1": "1d9ca5dac7541e9d53c341896740509aff10e6cb",
          "md5": "f4d186210162176739e1f7152a1a5246"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-svgrasterizer-1.1.1-sources.jar",
          "url": "echosvg-svgrasterizer-1.1.1-sources.jar",
          "size": 36163,
          "sha512": "be80f6c0d30b121570f19c633bbc578c52756bfaebe8ff416fb293a383c2df608c773f8c41e91d78e160d3f9589f2442a2a55d8ec400d19cef0f373095f8b673",
          "sha256": "0fc94640adb420347bd2380bd67c60dfeca040aed41babc89cbf9c3f6f3466ee",
          "sha1": "43a613e5dafdd7d49b3835d3dd786bde635dab13",
          "md5": "5e06f8269e000fa65f98c06e6902a074"
        }
      ]
    }
  ]
}
