{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-awt-util",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.4"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-awt-util-0.1.jar",
          "url": "echosvg-awt-util-0.1.jar",
          "size": 433461,
          "sha512": "cf57349a2eeb1e21b6a113cd5ee1a3a673f7761cfc1de19c0ce18ccdf154acb8710e7ccddf327f49be784d1cb814f5cf57430941c66f243f8729041b1bd927df",
          "sha256": "b9fb23ad7448f89b1218c6f4ab63251392ee8a33eca36b06d98f97c73440a87f",
          "sha1": "8b763725957ffaf5532f419da1151056087d1cb4",
          "md5": "e0b7bac54035ca2bffb088b17b8c834d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.4"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-awt-util-0.1.jar",
          "url": "echosvg-awt-util-0.1.jar",
          "size": 433461,
          "sha512": "cf57349a2eeb1e21b6a113cd5ee1a3a673f7761cfc1de19c0ce18ccdf154acb8710e7ccddf327f49be784d1cb814f5cf57430941c66f243f8729041b1bd927df",
          "sha256": "b9fb23ad7448f89b1218c6f4ab63251392ee8a33eca36b06d98f97c73440a87f",
          "sha1": "8b763725957ffaf5532f419da1151056087d1cb4",
          "md5": "e0b7bac54035ca2bffb088b17b8c834d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-awt-util-0.1-sources.jar",
          "url": "echosvg-awt-util-0.1-sources.jar",
          "size": 392743,
          "sha512": "2bb9d30d1fbe92cab74aaad67b8e6301e8a40e1e5aa47f5865665f649d53c0fb7a8fdb148b6385419a6c9e78bb4a7ffc950ba82443b5744df571c60d244c5a82",
          "sha256": "10bbcb804e0bcc6f5a7ceee1c7f085ac7a4b4f5069d917762b6c41c968d5f16b",
          "sha1": "f60accc641d1185e3868a21fba73739562f387e3",
          "md5": "721f95d31b4fa296e4cb592929389a16"
        }
      ]
    }
  ]
}
