{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-swing",
    "version": "2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-swing-2.5.jar",
          "url": "echosvg-swing-2.5.jar",
          "size": 197834,
          "sha512": "690c3766b2f852fcb1fe6ca7bb3e26bb15ba230fd3f44f3c163ab6b3857e9d68585adae27f7ce6898b94a7468f1613a8717c30cdf27c63bf8b6ef0a6049fcc99",
          "sha256": "d959abbe581e93b5608e4282b89b2d863ffa72c34e5830b577958e56ed630bcf",
          "sha1": "8ceafb12b77b61a2b76ac2be31ca4eb072840c8d",
          "md5": "e15fa9871cce035892a8da69a8201e0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-swing-2.5.jar",
          "url": "echosvg-swing-2.5.jar",
          "size": 197834,
          "sha512": "690c3766b2f852fcb1fe6ca7bb3e26bb15ba230fd3f44f3c163ab6b3857e9d68585adae27f7ce6898b94a7468f1613a8717c30cdf27c63bf8b6ef0a6049fcc99",
          "sha256": "d959abbe581e93b5608e4282b89b2d863ffa72c34e5830b577958e56ed630bcf",
          "sha1": "8ceafb12b77b61a2b76ac2be31ca4eb072840c8d",
          "md5": "e15fa9871cce035892a8da69a8201e0c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-swing-2.5-sources.jar",
          "url": "echosvg-swing-2.5-sources.jar",
          "size": 100993,
          "sha512": "1d17c5403da2ae6564cd2c9fdc04df1dbfb8f141fb5462075fe8096dce1fe0f55d0921d9bcb82a7d6a39d5d8f1684a575d8d72696f5c6df1fd78a258484d55f5",
          "sha256": "e4a9ac8e08e37d49aad13cdc4ba431e21bfa445a745add1fb7c88a351a53579f",
          "sha1": "9d0965ecd904a15f9e56cc3932e8b0fb46da376f",
          "md5": "714d33b64d57b4ec4dcec2d72d55eee3"
        }
      ]
    }
  ]
}
