{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-util",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-constants",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-util-0.3.1.jar",
          "url": "echosvg-util-0.3.1.jar",
          "size": 127927,
          "sha512": "e551b10c959a4639d83ce30fd739105ce66b8f5cd952d6d70109c188a61b18b326e1e48b662c8d15baf9320af2b99aba02cac0f8dc5a0b84fa75718b1790907a",
          "sha256": "637579a9a12ffc8a576f814a65560de39873b4b866e6399b3cb921234c404624",
          "sha1": "ca2d4087aa97fd77f5186d17aec948d953ada559",
          "md5": "577feb96b007519dec91292e7844571d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-constants",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-util-0.3.1.jar",
          "url": "echosvg-util-0.3.1.jar",
          "size": 127927,
          "sha512": "e551b10c959a4639d83ce30fd739105ce66b8f5cd952d6d70109c188a61b18b326e1e48b662c8d15baf9320af2b99aba02cac0f8dc5a0b84fa75718b1790907a",
          "sha256": "637579a9a12ffc8a576f814a65560de39873b4b866e6399b3cb921234c404624",
          "sha1": "ca2d4087aa97fd77f5186d17aec948d953ada559",
          "md5": "577feb96b007519dec91292e7844571d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-util-0.3.1-sources.jar",
          "url": "echosvg-util-0.3.1-sources.jar",
          "size": 108334,
          "sha512": "cd9965cc70c9ce1f467760b7c495110a6b3930a12b51cc8357fe30fbb588dcf0c5e253bfaf20583a689285c953d3a9b02036a826a1db1b049de29bfcca9a3e44",
          "sha256": "ccb51b2a69c0374085d91b244bcc54f65eaa0b6396a1d9540adc730c7ce5d9b1",
          "sha1": "5d919b26bc01d4abdaa7af982e278b77753935da",
          "md5": "a53d478ec1dd40ea9f6da6c96f8fa3c9"
        }
      ]
    }
  ]
}
