{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-all",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-extension",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-swing",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-slideshow",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgpp",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ttf2svg",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgrasterizer",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-all-1.2.jar",
          "url": "echosvg-all-1.2.jar",
          "size": 5473,
          "sha512": "bd8e710b698d6a6c4826c85a5c7d79f64c1d7e9f018189b3c16e37f0a7591d01cddf02c38c818446de275778e5bff05b58ef9a57e2461a378f6cecbc70aca71a",
          "sha256": "f175196dd4bdcc63bab2b8de72466030665ae5aa385cda55b21e038867636332",
          "sha1": "d9745b8b071b6ef3b10a93bef7c099cc0ae1b809",
          "md5": "e5c68121d72a0bc88fe0815820f115d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-extension",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-swing",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-slideshow",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgpp",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ttf2svg",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgrasterizer",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-all-1.2.jar",
          "url": "echosvg-all-1.2.jar",
          "size": 5473,
          "sha512": "bd8e710b698d6a6c4826c85a5c7d79f64c1d7e9f018189b3c16e37f0a7591d01cddf02c38c818446de275778e5bff05b58ef9a57e2461a378f6cecbc70aca71a",
          "sha256": "f175196dd4bdcc63bab2b8de72466030665ae5aa385cda55b21e038867636332",
          "sha1": "d9745b8b071b6ef3b10a93bef7c099cc0ae1b809",
          "md5": "e5c68121d72a0bc88fe0815820f115d3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-all-1.2-sources.jar",
          "url": "echosvg-all-1.2-sources.jar",
          "size": 5657,
          "sha512": "f2c1d929dc8e7fc6f6eef2b506112f876e92fc35739eb039b2a27b70e75bb8d91f9e5abd8303417b50e13867f0f9ee204402be49ca9669c18b7773051e7826c3",
          "sha256": "59be2c8c630d29d43201f986187a4ad8e6a2813ee5c90ea4af75a2edfc0633a1",
          "sha1": "74504b4e53f9b9144352598a9ee59cb617f90bf2",
          "md5": "36fde1ac8be7622f7aeb95647eaa9df7"
        }
      ]
    }
  ]
}
