{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-svgrasterizer",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svgrasterizer-1.2.1.jar",
          "url": "echosvg-svgrasterizer-1.2.1.jar",
          "size": 58369,
          "sha512": "b6d6660b6dcb72856d99aa0a700cf7588a685717f6d8f627b523123f46812e1216c5b8d5c77f2a4809af19115996f745d262bac7ec35bcced4c473dbc2982c80",
          "sha256": "0b4d4c5f7bd2d09898b7b4872638a50741053c5a4e1789ae27430b016895c40d",
          "sha1": "1c70a1b8cb7336be4572028f3d1cb9c9245e5147",
          "md5": "323832f976415412cb250e7b8cac5c68"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svgrasterizer-1.2.1.jar",
          "url": "echosvg-svgrasterizer-1.2.1.jar",
          "size": 58369,
          "sha512": "b6d6660b6dcb72856d99aa0a700cf7588a685717f6d8f627b523123f46812e1216c5b8d5c77f2a4809af19115996f745d262bac7ec35bcced4c473dbc2982c80",
          "sha256": "0b4d4c5f7bd2d09898b7b4872638a50741053c5a4e1789ae27430b016895c40d",
          "sha1": "1c70a1b8cb7336be4572028f3d1cb9c9245e5147",
          "md5": "323832f976415412cb250e7b8cac5c68"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-svgrasterizer-1.2.1-sources.jar",
          "url": "echosvg-svgrasterizer-1.2.1-sources.jar",
          "size": 36163,
          "sha512": "9bb4cbae9d8e7d843d7e0c47d5285b05619da1010eb19386831d38b36e393d195460cfe6eead3e1dded7c9c1146a4185b082267145fe682c0bba76bdc3aea09a",
          "sha256": "1e7bd4891ad67716e9e98a303a5bdb2bd7e99f5cd30baa69f9bb010d03287396",
          "sha1": "719cb8c558aaad9a99282de9d243c4d058e3f5ac",
          "md5": "eba3a756bbc3021760e73247ec021a30"
        }
      ]
    }
  ]
}
