{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-swing",
    "version": "2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "2.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-swing-2.1.jar",
          "url": "echosvg-swing-2.1.jar",
          "size": 197834,
          "sha512": "18b99f2db2e627eb874bd708131e779c83ec245019a9caec727d0487920b27b26c0961720d7f02dfe13a5ceb291167e6610fd4524e4eb4e54a72e014ecb27c77",
          "sha256": "ba2b1d79f81ff5cde8a2e3c4d97a908dcd673b5409f1f65bc1bbedaae727c2f6",
          "sha1": "d0248c8042b2db495238e71ec0f12f91011db521",
          "md5": "4016655433ddf67a417e78fca7322a88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "2.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-swing-2.1.jar",
          "url": "echosvg-swing-2.1.jar",
          "size": 197834,
          "sha512": "18b99f2db2e627eb874bd708131e779c83ec245019a9caec727d0487920b27b26c0961720d7f02dfe13a5ceb291167e6610fd4524e4eb4e54a72e014ecb27c77",
          "sha256": "ba2b1d79f81ff5cde8a2e3c4d97a908dcd673b5409f1f65bc1bbedaae727c2f6",
          "sha1": "d0248c8042b2db495238e71ec0f12f91011db521",
          "md5": "4016655433ddf67a417e78fca7322a88"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-swing-2.1-sources.jar",
          "url": "echosvg-swing-2.1-sources.jar",
          "size": 100993,
          "sha512": "aaceb9dc3c4e83d29bbec71dd36cc411ab664604a3a8b15c0215d23c80f7f3eec508ac280e8d54a3694206d08e3e6c0cece090ea93280051fdb5096fb7736d8b",
          "sha256": "b4ad25c9d6042fa161cda6d0599d01d0762fb8d96fc27c66445ea5a1f3b7fad5",
          "sha1": "3463ec2f96f791c386da4d9963440cb2f4bdc6d3",
          "md5": "3c782fffade76604264afb876f14b4d7"
        }
      ]
    }
  ]
}
