{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-script",
    "version": "0.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.7.14"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-script-0.3.2.jar",
          "url": "echosvg-script-0.3.2.jar",
          "size": 26840,
          "sha512": "54e28bcc3743ab06f4ec9082f449a2fa43d2434f93ad2514932b674d45bd2b26d31b248f4c389f2430891e4212ea2dd9d3e0f7f57ece5b8b03f265b19d124c23",
          "sha256": "e6aec6634ae7aa8d1e6328fd76d862dcd142522ee36bd26c41fd3a010485cd4a",
          "sha1": "12bd2a66fbb0a60d6ff676944949f3a07635e0f8",
          "md5": "9c46057a81f1b948cd40ec202d1eb158"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "xml-apis",
          "module": "xml-apis",
          "version": {
            "requires": "1.4.01"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.7.14"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-script-0.3.2.jar",
          "url": "echosvg-script-0.3.2.jar",
          "size": 26840,
          "sha512": "54e28bcc3743ab06f4ec9082f449a2fa43d2434f93ad2514932b674d45bd2b26d31b248f4c389f2430891e4212ea2dd9d3e0f7f57ece5b8b03f265b19d124c23",
          "sha256": "e6aec6634ae7aa8d1e6328fd76d862dcd142522ee36bd26c41fd3a010485cd4a",
          "sha1": "12bd2a66fbb0a60d6ff676944949f3a07635e0f8",
          "md5": "9c46057a81f1b948cd40ec202d1eb158"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-script-0.3.2-sources.jar",
          "url": "echosvg-script-0.3.2-sources.jar",
          "size": 29442,
          "sha512": "2a98c2af32141d96d2d406de27e3d92e7bae7f2453360732ff4a5d7261d2cae35aed8986f335dfa41db7778bbf8716b376ebd26c40b2276fb692ab49cfcb9e96",
          "sha256": "e0fd32987970e3d8a67eeb16c1a8664da0933d48c187589d031ab1e17c9d82f2",
          "sha1": "976bd2593a76077677f4de542b30963461a92537",
          "md5": "a0187b89ff11e9bd1986dbbbc14e90c5"
        }
      ]
    }
  ]
}
