{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-dom",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-css",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "xml-dtd",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "[2.9,)"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-dom-1.1.jar",
          "url": "echosvg-dom-1.1.jar",
          "size": 197980,
          "sha512": "97e4277996937135b17ca964fd29ad684c888589cca76959ab37277b6c0a6fa3def8ffbc7b26a96dfb19d94bfa9413acc090dcf9b64e88ce98885b0279e73b50",
          "sha256": "52832648072c86966ca8762bb1ea2f4ce0e625002738fe5caadcc1fa883d95fd",
          "sha1": "9e80857bde216f807e12db44144efa4312b145f6",
          "md5": "9f3c01053e3bb3c6ef40842d8b054acd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "xml-apis",
          "module": "xml-apis",
          "version": {
            "requires": "1.4.01"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-css",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "xml-dtd",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "[2.9,)"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-dom-1.1.jar",
          "url": "echosvg-dom-1.1.jar",
          "size": 197980,
          "sha512": "97e4277996937135b17ca964fd29ad684c888589cca76959ab37277b6c0a6fa3def8ffbc7b26a96dfb19d94bfa9413acc090dcf9b64e88ce98885b0279e73b50",
          "sha256": "52832648072c86966ca8762bb1ea2f4ce0e625002738fe5caadcc1fa883d95fd",
          "sha1": "9e80857bde216f807e12db44144efa4312b145f6",
          "md5": "9f3c01053e3bb3c6ef40842d8b054acd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-dom-1.1-sources.jar",
          "url": "echosvg-dom-1.1-sources.jar",
          "size": 171178,
          "sha512": "cf0a84348494191f42b9abe373febcdd689ece687d43a7f0199cb4a103b3da71212f2f2f9af2d2a1fa91a04f0df6b0cba95df5f815f8c672788465ee80ba7d55",
          "sha256": "b5368577ee76c7624134a5d1220bb9ba03c2afa19511aa19353eb5892d4925d6",
          "sha1": "005b41274d8292f470904450377a30c8e9f2333b",
          "md5": "c4c38bb3a0a08059e29e012b1ebc290c"
        }
      ]
    }
  ]
}
