{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-ttf2svg",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-svggen",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-ttf2svg-0.1.jar",
          "url": "echosvg-ttf2svg-0.1.jar",
          "size": 6223,
          "sha512": "9e783ec6c06c804dfce1896aeffb3adb6836e1ac8b585ae86b6d0bfd84552cb895333990a7dbafbe4a1e69f148b79005ac05e8802e4f7703b6fff91f35dce064",
          "sha256": "fc9d480fed143931e84972fc4237a7a32651b505098c502cf6055f687cfb7303",
          "sha1": "d5e8c27ec2a24e7064f0278a6856180190476de4",
          "md5": "fa413a186a23f66875a0fa9a8f4315e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-svggen",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-ttf2svg-0.1.jar",
          "url": "echosvg-ttf2svg-0.1.jar",
          "size": 6223,
          "sha512": "9e783ec6c06c804dfce1896aeffb3adb6836e1ac8b585ae86b6d0bfd84552cb895333990a7dbafbe4a1e69f148b79005ac05e8802e4f7703b6fff91f35dce064",
          "sha256": "fc9d480fed143931e84972fc4237a7a32651b505098c502cf6055f687cfb7303",
          "sha1": "d5e8c27ec2a24e7064f0278a6856180190476de4",
          "md5": "fa413a186a23f66875a0fa9a8f4315e8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-ttf2svg-0.1-sources.jar",
          "url": "echosvg-ttf2svg-0.1-sources.jar",
          "size": 6845,
          "sha512": "284d262f08f2d2604e8db8d7bf34d99ac2603a5081e4ff39adf8c2f7a744738aa8135b6497ca24a0e79eb2544208dc38e36ca7719663302a875504abbf241484",
          "sha256": "505e8937b5869484ce03bb6574d6f993ff685099c2aec741ebe5211376a32dc9",
          "sha1": "cfcd260fd7c45a193bce284aadd97fe1c98ef739",
          "md5": "618dfa0ccc4de54926211321b96e4549"
        }
      ]
    }
  ]
}
