{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-swing",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-swing-0.3.1.jar",
          "url": "echosvg-swing-0.3.1.jar",
          "size": 194493,
          "sha512": "60e5d32f0106147fbac4a6c1ddd42f64aaced2e84348c0cadf6659abf9697cec07fa45daa8366a7db34aacc15b48d503f5fd094433bbbb3bfdd45b99899c8b43",
          "sha256": "7ea3dcca16166313b5822a8613708753e7680d34db3a596440295f56138c2a17",
          "sha1": "bf52b2448829741cb79d284622369d3b300c92a2",
          "md5": "4758d6ce88f9b46e702305a9ad80f067"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "xml-apis",
          "module": "xml-apis",
          "version": {
            "requires": "1.4.01"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-swing-0.3.1.jar",
          "url": "echosvg-swing-0.3.1.jar",
          "size": 194493,
          "sha512": "60e5d32f0106147fbac4a6c1ddd42f64aaced2e84348c0cadf6659abf9697cec07fa45daa8366a7db34aacc15b48d503f5fd094433bbbb3bfdd45b99899c8b43",
          "sha256": "7ea3dcca16166313b5822a8613708753e7680d34db3a596440295f56138c2a17",
          "sha1": "bf52b2448829741cb79d284622369d3b300c92a2",
          "md5": "4758d6ce88f9b46e702305a9ad80f067"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-swing-0.3.1-sources.jar",
          "url": "echosvg-swing-0.3.1-sources.jar",
          "size": 100568,
          "sha512": "4389a62a30da2fc9999674077024f97b0117814bc69436314a3c5fb8f026b45452e6e6b8c767d9ade36c2ef2f467d5d78f1d768688ba6149929d0e59271af913",
          "sha256": "93ac8367b91a367932d49095e48602dbc0c1286011c06ac79a6d6e62db199577",
          "sha1": "e0292cb571ce7e2823f15869bc985ec803d5373c",
          "md5": "e4efa7fe0fbf841a4b814a9494ad5775"
        }
      ]
    }
  ]
}
