{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.jclf",
    "module": "jclf",
    "version": "5.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.jclf",
          "module": "jclf-linear3",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.sf.jclf",
          "module": "jclf-net",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.sf.jclf",
          "module": "jclf-util",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "jclf-5.0.1.jar",
          "url": "jclf-5.0.1.jar",
          "size": 1534,
          "sha512": "fa0550200113f92ed04efef7e0094908f964dcc8dfab8e72678def8bc6ea55eb3fc137f2733cebb41d643e445012e3744f0e159846affece082668336a2fb411",
          "sha256": "a47b1ba4f302d22ab97f2b2f1558343fa7e004a2a577d1bed5c48c384f9b2e14",
          "sha1": "de445e44db575fc4d769757d21021068e4139193",
          "md5": "752868dfbe6253d005a41e220a803796"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.jclf",
          "module": "jclf-linear3",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.sf.jclf",
          "module": "jclf-net",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "io.sf.jclf",
          "module": "jclf-util",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "jclf-5.0.1.jar",
          "url": "jclf-5.0.1.jar",
          "size": 1534,
          "sha512": "fa0550200113f92ed04efef7e0094908f964dcc8dfab8e72678def8bc6ea55eb3fc137f2733cebb41d643e445012e3744f0e159846affece082668336a2fb411",
          "sha256": "a47b1ba4f302d22ab97f2b2f1558343fa7e004a2a577d1bed5c48c384f9b2e14",
          "sha1": "de445e44db575fc4d769757d21021068e4139193",
          "md5": "752868dfbe6253d005a41e220a803796"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jclf-5.0.1-sources.jar",
          "url": "jclf-5.0.1-sources.jar",
          "size": 1582,
          "sha512": "450d119afb8a6031b9db1a5641cbac813811202cf653e20927eb9443c715ea99e63bf26b65cfacdda9fd8f803a3207487c6a172d3c872fb2bcaf46e4023380f0",
          "sha256": "2af72dfcba6f8f45367cb763bb75b22b67817efa6db5f93726312df09d7fb9de",
          "sha1": "a136fcd5ce3067c4699f6ab234234d603d99f946",
          "md5": "6980dafde1ed3eddf7d23d8f3ddc98ee"
        }
      ]
    }
  ]
}
