{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-all",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-extension",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-swing",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-slideshow",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgpp",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ttf2svg",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgrasterizer",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-all-1.1.1.jar",
          "url": "echosvg-all-1.1.1.jar",
          "size": 5473,
          "sha512": "bd8e710b698d6a6c4826c85a5c7d79f64c1d7e9f018189b3c16e37f0a7591d01cddf02c38c818446de275778e5bff05b58ef9a57e2461a378f6cecbc70aca71a",
          "sha256": "f175196dd4bdcc63bab2b8de72466030665ae5aa385cda55b21e038867636332",
          "sha1": "d9745b8b071b6ef3b10a93bef7c099cc0ae1b809",
          "md5": "e5c68121d72a0bc88fe0815820f115d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-extension",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-swing",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-slideshow",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgpp",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ttf2svg",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgrasterizer",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-all-1.1.1.jar",
          "url": "echosvg-all-1.1.1.jar",
          "size": 5473,
          "sha512": "bd8e710b698d6a6c4826c85a5c7d79f64c1d7e9f018189b3c16e37f0a7591d01cddf02c38c818446de275778e5bff05b58ef9a57e2461a378f6cecbc70aca71a",
          "sha256": "f175196dd4bdcc63bab2b8de72466030665ae5aa385cda55b21e038867636332",
          "sha1": "d9745b8b071b6ef3b10a93bef7c099cc0ae1b809",
          "md5": "e5c68121d72a0bc88fe0815820f115d3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-all-1.1.1-sources.jar",
          "url": "echosvg-all-1.1.1-sources.jar",
          "size": 5656,
          "sha512": "007ed562be28406faf004caebe4259db0399c2619015eb2e86390d5db4e1525d578885ae63d160873787b3c87660b8c7186785387e5ca7a615c46b94f5c788d4",
          "sha256": "a7bd23e512681391421b23747690d1bf845e541896acd4f1a652336264fbbaaa",
          "sha1": "cea4e4e1e06d5fa4d07df9b12e1a1dd1cbf0c550",
          "md5": "0eea728fca4b47266a88633cec29ba89"
        }
      ]
    }
  ]
}
