{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-script",
    "version": "2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.7.15"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-script-2.3.jar",
          "url": "echosvg-script-2.3.jar",
          "size": 27214,
          "sha512": "f8ebfab7897d3e2941e6580f2f9dfdb4bb9eda12311521dad3fd659fa6217e4ca6d75f60c462ff841b23f80834656ac9489ecff5b1be0c283d7e2ce2222a12c3",
          "sha256": "d0a40b1ae296a97ed35e96c397131679223b22cf7a99ac7243ecc4dd2a4f8421",
          "sha1": "519eb9be882dc15d6f7ae539ce8d25b36a21e4c1",
          "md5": "4c363d754d8b5a8f1a424944e5ff1c44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.7.15"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-script-2.3.jar",
          "url": "echosvg-script-2.3.jar",
          "size": 27214,
          "sha512": "f8ebfab7897d3e2941e6580f2f9dfdb4bb9eda12311521dad3fd659fa6217e4ca6d75f60c462ff841b23f80834656ac9489ecff5b1be0c283d7e2ce2222a12c3",
          "sha256": "d0a40b1ae296a97ed35e96c397131679223b22cf7a99ac7243ecc4dd2a4f8421",
          "sha1": "519eb9be882dc15d6f7ae539ce8d25b36a21e4c1",
          "md5": "4c363d754d8b5a8f1a424944e5ff1c44"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-script-2.3-sources.jar",
          "url": "echosvg-script-2.3-sources.jar",
          "size": 29811,
          "sha512": "3704598bedd0ebb6ca21c99c94f90d5c78282de228a3cacf14b3b7b08df72b5813e958959f4c4dba41b790f5fe4ec3feb581c29d57dab68a6506ce84bdffdb30",
          "sha256": "8d1a31030809c9be04736541b2d7a6e14fc421a0829e880d9ef4cadd6fda72ae",
          "sha1": "32518d487de408909b9168b259a5cc299f94a2ae",
          "md5": "4ec859d9905d4c19b51ef5489873e9d5"
        }
      ]
    }
  ]
}
