{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-bridge",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gvt",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "xalan",
          "module": "xalan",
          "version": {
            "requires": "2.7.2"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-bridge-0.1.jar",
          "url": "echosvg-bridge-0.1.jar",
          "size": 720856,
          "sha512": "8f7a87eeec49f8ee1065b9563d85c3097916133b036f4489ad4a070e785d635e01ff856d9d8945a49a27fbf10ef4c4ed8c3beea5567a3d5b5a9b80a2640644a1",
          "sha256": "917f95395266c46d69602b9c9c5f43c4b0c95c2358bf67a6920d39d8946e039c",
          "sha1": "13b4e915930bdb944f83a142f73322196f062bb1",
          "md5": "d8512f0f0b75037e30fc4ae19a09d5a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.7.13"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gvt",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "xalan",
          "module": "xalan",
          "version": {
            "requires": "2.7.2"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-bridge-0.1.jar",
          "url": "echosvg-bridge-0.1.jar",
          "size": 720856,
          "sha512": "8f7a87eeec49f8ee1065b9563d85c3097916133b036f4489ad4a070e785d635e01ff856d9d8945a49a27fbf10ef4c4ed8c3beea5567a3d5b5a9b80a2640644a1",
          "sha256": "917f95395266c46d69602b9c9c5f43c4b0c95c2358bf67a6920d39d8946e039c",
          "sha1": "13b4e915930bdb944f83a142f73322196f062bb1",
          "md5": "d8512f0f0b75037e30fc4ae19a09d5a3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-bridge-0.1-sources.jar",
          "url": "echosvg-bridge-0.1-sources.jar",
          "size": 484511,
          "sha512": "42c1d786175cc66486586659e904c32f601ee2cf9397c5d5b0dd20e89e9778344db94e9f95b60936454237e549324916dec31167d0c9f4d1b2033ed46b12986c",
          "sha256": "c2043dad113fa59c90d3e582995e1841550e6b47da9ec46fae1f5f0443f64b8a",
          "sha1": "250cb8d3308bbd766051d63a374af2ce5a352ffb",
          "md5": "42a074b617a222a186624f662b695d0e"
        }
      ]
    }
  ]
}
