{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-bridge",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gvt",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "xalan",
          "module": "xalan",
          "version": {
            "requires": "2.7.2"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-bridge-0.1.jar",
          "url": "echosvg-bridge-0.1.jar",
          "size": 720855,
          "sha512": "011120865ebcefb39aedefadb72efc35db3a13ec385946d814aa533091254e0b3798adae28aea40db7720e7f687b631a360de66603fc9a0d6e92c82f72a171e3",
          "sha256": "0eb2242fc167e032ad0fdb3fc36e57aea64a22c14008b12d8350c4ac1bf81f85",
          "sha1": "dd7dbd7d1a9cbd1f69f64a129a2900501bba3a52",
          "md5": "74167635a780fb37100be85b5f7f51a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.7.13"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gvt",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "xalan",
          "module": "xalan",
          "version": {
            "requires": "2.7.2"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-bridge-0.1.jar",
          "url": "echosvg-bridge-0.1.jar",
          "size": 720855,
          "sha512": "011120865ebcefb39aedefadb72efc35db3a13ec385946d814aa533091254e0b3798adae28aea40db7720e7f687b631a360de66603fc9a0d6e92c82f72a171e3",
          "sha256": "0eb2242fc167e032ad0fdb3fc36e57aea64a22c14008b12d8350c4ac1bf81f85",
          "sha1": "dd7dbd7d1a9cbd1f69f64a129a2900501bba3a52",
          "md5": "74167635a780fb37100be85b5f7f51a6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-bridge-0.1-sources.jar",
          "url": "echosvg-bridge-0.1-sources.jar",
          "size": 484497,
          "sha512": "6b4ac682b60ef5414aa67803180f40fe7071a2c9b90e947b0454dbbfdb9f1af1e9b5aa40fa61d312b270ca12dfcd94c1e0779e1f8a0bd85a2e9e825cdb3fdb17",
          "sha256": "57604cd8332f276e48687079fce0f8019790fc31ff064ab8d0a402e36990f546",
          "sha1": "90000f9d4e5da2744a34fbbe48c3c556c234d988",
          "md5": "9e9bd56db9fc812b58428a51e4ed58b9"
        }
      ]
    }
  ]
}
