{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "css4j",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "carte-util",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "tokenproducer",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.sf.jclf",
          "module": "jclf-text",
          "version": {
            "requires": "[5.0.0,)"
          }
        }
      ],
      "files": [
        {
          "name": "css4j-3.5.0.jar",
          "url": "css4j-3.5.0.jar",
          "size": 1399563,
          "sha512": "c9890e51f99a2ed9d3370ca91f15cd39593022474604d9e95426184fcb7243ea25979c10427ff767d2d92c7be0ce22ec6000efb03cb0575da090c153c107f9fb",
          "sha256": "66dd6ce8e7eb187ce4e515ce81d1bb1eea221b265f2d798849d90f4e496a012b",
          "sha1": "644944a22475adcf1a5bfd292be895c6c86656bc",
          "md5": "e45f31ede8050f4cd1fc6de55e34e3a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "xml-dtd",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "[1.7.28,)"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "carte-util",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "tokenproducer",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.sf.jclf",
          "module": "jclf-text",
          "version": {
            "requires": "[5.0.0,)"
          }
        }
      ],
      "files": [
        {
          "name": "css4j-3.5.0.jar",
          "url": "css4j-3.5.0.jar",
          "size": 1399563,
          "sha512": "c9890e51f99a2ed9d3370ca91f15cd39593022474604d9e95426184fcb7243ea25979c10427ff767d2d92c7be0ce22ec6000efb03cb0575da090c153c107f9fb",
          "sha256": "66dd6ce8e7eb187ce4e515ce81d1bb1eea221b265f2d798849d90f4e496a012b",
          "sha1": "644944a22475adcf1a5bfd292be895c6c86656bc",
          "md5": "e45f31ede8050f4cd1fc6de55e34e3a8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "css4j-3.5.0-javadoc.jar",
          "url": "css4j-3.5.0-javadoc.jar",
          "size": 1608883,
          "sha512": "8637b02f75fc4b62a4587b8898f8540918915e90a06a60d45fe1b10692c23826b9143403abd41d3c9f6b6d57b91de994e000fa713e84454f7041a02bf7f7f316",
          "sha256": "6b0e9206efb2cc1fa74da74bf90db3d98e75cb57a52aef1fc500ed71b9d028fb",
          "sha1": "ef54a702ff4d428365befe1c9576da8b6a7d4509",
          "md5": "2fdb0b8ffc5bddf260f09b08d824acaa"
        },
        {
          "name": "css4j-3.5.0-javadoc.jar",
          "url": "css4j-3.5.0-javadoc.jar",
          "size": 1608883,
          "sha512": "8637b02f75fc4b62a4587b8898f8540918915e90a06a60d45fe1b10692c23826b9143403abd41d3c9f6b6d57b91de994e000fa713e84454f7041a02bf7f7f316",
          "sha256": "6b0e9206efb2cc1fa74da74bf90db3d98e75cb57a52aef1fc500ed71b9d028fb",
          "sha1": "ef54a702ff4d428365befe1c9576da8b6a7d4509",
          "md5": "2fdb0b8ffc5bddf260f09b08d824acaa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "css4j-3.5.0-sources.jar",
          "url": "css4j-3.5.0-sources.jar",
          "size": 779494,
          "sha512": "55d131368b242ad34f92999a115c52839a828a5d0a8b8a7e244c4e44a42fce89e9284b73fd695fb53c56d9c8a14b665f8a6a90fa29b660e5a3c9567fa94ac2c8",
          "sha256": "1342dad540af15302986bcb260de7a2a142e1e412cf6f2f54e31fbb97e12ea0c",
          "sha1": "88aaab8e9786d3bbf302c2643dd5c5677ecf2978",
          "md5": "d1eb2a66d15dcfc5ce51720cfff71481"
        }
      ]
    }
  ]
}
