{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "css4j",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "carte-util",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "tokenproducer",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.jclf",
          "module": "jclf-text",
          "version": {
            "requires": "[5.0.0,)"
          }
        }
      ],
      "files": [
        {
          "name": "css4j-3.5.0.jar",
          "url": "css4j-3.5.0.jar",
          "size": 1399575,
          "sha512": "b84768b02b23befde83d5241bb9e7152fd834c2ea082ea2c84b4364d54c8f8b827ca80289a786591f3afdfbbe271d4e5a555507c6b4b1fb30e220ae5ca7d2e1b",
          "sha256": "00ac80fdc8d17d5f6c887fb752dde367aebd9a7bd734f525063b63a448a2cfe4",
          "sha1": "e2963f19018f12d8560c65cc1138208fac164fc6",
          "md5": "d2d8626784c5829670ab27e546907a52"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "xml-dtd",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "[1.7.28,)"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "carte-util",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "tokenproducer",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.jclf",
          "module": "jclf-text",
          "version": {
            "requires": "[5.0.0,)"
          }
        }
      ],
      "files": [
        {
          "name": "css4j-3.5.0.jar",
          "url": "css4j-3.5.0.jar",
          "size": 1399575,
          "sha512": "b84768b02b23befde83d5241bb9e7152fd834c2ea082ea2c84b4364d54c8f8b827ca80289a786591f3afdfbbe271d4e5a555507c6b4b1fb30e220ae5ca7d2e1b",
          "sha256": "00ac80fdc8d17d5f6c887fb752dde367aebd9a7bd734f525063b63a448a2cfe4",
          "sha1": "e2963f19018f12d8560c65cc1138208fac164fc6",
          "md5": "d2d8626784c5829670ab27e546907a52"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "css4j-3.5.0-javadoc.jar",
          "url": "css4j-3.5.0-javadoc.jar",
          "size": 1608883,
          "sha512": "4d4c26b21be5b6b77b06fe24730baa8c83518079d9f13f5cf2495120e4653e37530fb005eb20c4b2dd8a094a099558153b57b65f9fbfbc8dd0c9d72be28c3bd0",
          "sha256": "da3b52a29c6e34a5aa09e8f7fe586264a6a026968208fa88704bf9fb33949188",
          "sha1": "448c3e0fb730f70365aac0cfcd3810bc2abf50a6",
          "md5": "34cf912b1598df8abc78477b8f0cd660"
        },
        {
          "name": "css4j-3.5.0-javadoc.jar",
          "url": "css4j-3.5.0-javadoc.jar",
          "size": 1608883,
          "sha512": "4d4c26b21be5b6b77b06fe24730baa8c83518079d9f13f5cf2495120e4653e37530fb005eb20c4b2dd8a094a099558153b57b65f9fbfbc8dd0c9d72be28c3bd0",
          "sha256": "da3b52a29c6e34a5aa09e8f7fe586264a6a026968208fa88704bf9fb33949188",
          "sha1": "448c3e0fb730f70365aac0cfcd3810bc2abf50a6",
          "md5": "34cf912b1598df8abc78477b8f0cd660"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "css4j-3.5.0-sources.jar",
          "url": "css4j-3.5.0-sources.jar",
          "size": 779494,
          "sha512": "c2a242c8c54c5328cee8f2680ec58cbe6b89683690fd0f26e4be74571aeef83c0a4040775293856512ae08b0376a17c74e437c3cdbe4095b2b30b10ead59f304",
          "sha256": "e914b6c1db562b89b453cf100433d0e8c3fd8f150ae72ff929efe4ce0eeb3f06",
          "sha1": "2ca2db55520ada0ff313ba8d52fd36e92ca08129",
          "md5": "83467ff834abbf47135de62b6e2b9781"
        }
      ]
    }
  ]
}
