{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-xml",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-xml-0.1.jar",
          "url": "echosvg-xml-0.1.jar",
          "size": 32300,
          "sha512": "478187632066f66167923a7e3201b524ce8c379a35275d7bd523864bbd364696a5fabfc364f514310eba5cb071fa01ec8ced3df4f2b84b8f7ab926c3bd8536b5",
          "sha256": "71bda0b37259ecd39f81f679c80282455e0cebaaa05365618c9012e96c2b9a4b",
          "sha1": "8361a69d40ab6e2550fe6debdace9300ffe2575c",
          "md5": "9c1df60d02584e445b4d3c6565ea92ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-xml-0.1.jar",
          "url": "echosvg-xml-0.1.jar",
          "size": 32300,
          "sha512": "478187632066f66167923a7e3201b524ce8c379a35275d7bd523864bbd364696a5fabfc364f514310eba5cb071fa01ec8ced3df4f2b84b8f7ab926c3bd8536b5",
          "sha256": "71bda0b37259ecd39f81f679c80282455e0cebaaa05365618c9012e96c2b9a4b",
          "sha1": "8361a69d40ab6e2550fe6debdace9300ffe2575c",
          "md5": "9c1df60d02584e445b4d3c6565ea92ff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-xml-0.1-sources.jar",
          "url": "echosvg-xml-0.1-sources.jar",
          "size": 23269,
          "sha512": "81126061cf6b0597ea0ed82b8da242ac38d3d9388f39222e65d2f83afde08938367b4cfb6743f79b320bbd12af9bcacd31e7172aef7e74434b954b7caf95637d",
          "sha256": "39874c650d134f32f23a366485648cdda5e9776154b94421d8a030ea958190d7",
          "sha1": "d3f84cb67d9b621582fcb74d3d18ead2de683691",
          "md5": "25fe5befb2e84cf5db040ce03f636ae5"
        }
      ]
    }
  ]
}
