{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-test-util",
    "version": "2.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "echosvg-test-util-2.2.1.jar",
          "url": "echosvg-test-util-2.2.1.jar",
          "size": 30700,
          "sha512": "2a6872a307144f2a3627a8c8fa2283c97ee04236abf7276c465cdc1361e0bbb5076090ca6d5eaf18fdbd69e33469a26e7bf19c433cdc546f5cfbc031e9811643",
          "sha256": "19ab6a3149f524a4411316c7f4b1749f54eda7d9b5e407715238b6c82fc2aef9",
          "sha1": "0dcef2a71c8975e8d5d7f95523d89b7e5ed1370c",
          "md5": "cbc8d904f94a45cfad2e6721b88cc93e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.sf.jclf",
          "module": "jclf-text",
          "version": {
            "requires": "5.0.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "xml-dtd",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "carte-util",
          "version": {
            "requires": "[3.6.0,)"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-test-util-2.2.1.jar",
          "url": "echosvg-test-util-2.2.1.jar",
          "size": 30700,
          "sha512": "2a6872a307144f2a3627a8c8fa2283c97ee04236abf7276c465cdc1361e0bbb5076090ca6d5eaf18fdbd69e33469a26e7bf19c433cdc546f5cfbc031e9811643",
          "sha256": "19ab6a3149f524a4411316c7f4b1749f54eda7d9b5e407715238b6c82fc2aef9",
          "sha1": "0dcef2a71c8975e8d5d7f95523d89b7e5ed1370c",
          "md5": "cbc8d904f94a45cfad2e6721b88cc93e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-test-util-2.2.1-sources.jar",
          "url": "echosvg-test-util-2.2.1-sources.jar",
          "size": 24960,
          "sha512": "20a8bc5d2f7d346257941f2729400099abd040618fb61327b3a47c7bbf4c2a72b1de1d3295e8b642be32b48a340b4a039a89d9ee1e3a400bddb17abb70b96d5a",
          "sha256": "4bab0dcc29690164522adb247fe9582c623f08d7708d5087ca241478c7a9fb01",
          "sha1": "9baa3fdbb6ae1a4b3c93a170354a85c19b02aaa1",
          "md5": "4cc55ada30b9ccd0ddde7029e0ea9183"
        }
      ]
    }
  ]
}
