{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-extension",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-extension-0.1.jar",
          "url": "echosvg-extension-0.1.jar",
          "size": 73372,
          "sha512": "bae480ea085fbd8ddf911da3d3c2dcfe7d01521338d6c831efc0d0eeebf3793eb8c2d1c95b4e8a7fa252c33729d8c8bdc1899ca97cfee5856075c992be78d25c",
          "sha256": "be2924f00119bdcce3f0920e64a0f7598f9ef2b7275e20f45cf7664ebecb49c5",
          "sha1": "7cbcd059047af0a23b19bb0b11180d8ded75c8b5",
          "md5": "f61d736cdeda5ef5a1bb6a000fca6a59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-extension-0.1.jar",
          "url": "echosvg-extension-0.1.jar",
          "size": 73372,
          "sha512": "bae480ea085fbd8ddf911da3d3c2dcfe7d01521338d6c831efc0d0eeebf3793eb8c2d1c95b4e8a7fa252c33729d8c8bdc1899ca97cfee5856075c992be78d25c",
          "sha256": "be2924f00119bdcce3f0920e64a0f7598f9ef2b7275e20f45cf7664ebecb49c5",
          "sha1": "7cbcd059047af0a23b19bb0b11180d8ded75c8b5",
          "md5": "f61d736cdeda5ef5a1bb6a000fca6a59"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-extension-0.1-sources.jar",
          "url": "echosvg-extension-0.1-sources.jar",
          "size": 67476,
          "sha512": "222f31f16ad822a039cd426fcf2c88b45846eae081af0b622f5b3021d43d7b009d9d50e3586c0ea646d5e46d8df29e93b735a0b17d874333d59b3f81b8355661",
          "sha256": "4762547bc0d2ef7fbd238af376a3e92b31fce560e12c39ad8809d958e40e9103",
          "sha1": "ab1265f939e8e261255fa6c4adc18d69bb496355",
          "md5": "690d6935caf77e3dbc2892395829e29a"
        }
      ]
    }
  ]
}
