{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-slideshow",
    "version": "2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "2.3"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-slideshow-2.3.jar",
          "url": "echosvg-slideshow-2.3.jar",
          "size": 16628,
          "sha512": "e09ce416b14eb4897a9ae6f550358e28f40a7e106fffcf58187e49e2c63ff68ef197d3a687b9de2ad08061a594a02d331404a50e5ab1568a8a033b83da7184a5",
          "sha256": "8f8d357e797adb31f3fbaf98b8f1cd23d5df5302f7e485ddec171e2f33195912",
          "sha1": "f960d47ae0e09b362f30809ed95ac98ce79a3bfd",
          "md5": "d356a79ab0ff0036bc0cc39455575629"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "2.3"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-slideshow-2.3.jar",
          "url": "echosvg-slideshow-2.3.jar",
          "size": 16628,
          "sha512": "e09ce416b14eb4897a9ae6f550358e28f40a7e106fffcf58187e49e2c63ff68ef197d3a687b9de2ad08061a594a02d331404a50e5ab1568a8a033b83da7184a5",
          "sha256": "8f8d357e797adb31f3fbaf98b8f1cd23d5df5302f7e485ddec171e2f33195912",
          "sha1": "f960d47ae0e09b362f30809ed95ac98ce79a3bfd",
          "md5": "d356a79ab0ff0036bc0cc39455575629"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-slideshow-2.3-sources.jar",
          "url": "echosvg-slideshow-2.3-sources.jar",
          "size": 10317,
          "sha512": "68f467298ce5f02f362871572c7f37c3f3352f379783dc2a42c97ebbd3479d521097951d82e1a92fd51886e317d6e498e3b99062dae6980f64ba009e7adfaf2a",
          "sha256": "2603903f761e2f1c35dd9ac5c9f0f26a472879a781073608796a4b0492acfe3e",
          "sha1": "44838916f1ee761b3395972ddc1cca9774b5b8f3",
          "md5": "2152d496f19d09e4c90ba77593d36197"
        }
      ]
    }
  ]
}
