{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-ttf2svg",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "echosvg-ttf2svg-2.0.jar",
          "url": "echosvg-ttf2svg-2.0.jar",
          "size": 6619,
          "sha512": "70791170ea552e8665d17bc127468e1953bc5d18a39af1667f2d8da36a4ecf0b6f8b6de9e36b3bd9a8aa7d7ff7bf7460053e1b5ff396d673e4496acfa0c5aadc",
          "sha256": "17636cf0627f24df88648dd9f9f027602bed456d3bac5dd4df6fff13cba78789",
          "sha1": "a25a50ac9cc9bb413fea35d713d52429fb19398f",
          "md5": "241ac377de1668179725f03ec92fc9b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-svggen",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-ttf2svg-2.0.jar",
          "url": "echosvg-ttf2svg-2.0.jar",
          "size": 6619,
          "sha512": "70791170ea552e8665d17bc127468e1953bc5d18a39af1667f2d8da36a4ecf0b6f8b6de9e36b3bd9a8aa7d7ff7bf7460053e1b5ff396d673e4496acfa0c5aadc",
          "sha256": "17636cf0627f24df88648dd9f9f027602bed456d3bac5dd4df6fff13cba78789",
          "sha1": "a25a50ac9cc9bb413fea35d713d52429fb19398f",
          "md5": "241ac377de1668179725f03ec92fc9b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-ttf2svg-2.0-sources.jar",
          "url": "echosvg-ttf2svg-2.0-sources.jar",
          "size": 7250,
          "sha512": "e41cf66700b2f03e3def122b605b606429cb9b1b8caee8468f28a342c22f10c3767c4b2dd067e13f59b2d3f6f0f78591b71d18d75dd9cedc2580256f0cf676a0",
          "sha256": "176a7e68d8282f54f34edd4f0cd280f14b2df20d08cc5842b1e4b10ed2bfc70d",
          "sha1": "e7a10e7fc05c901205a0a35bc59fc06dbec54d66",
          "md5": "a0147f0aec87365c3f5dd897ae8d4156"
        }
      ]
    }
  ]
}
