{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-script",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-script-0.1.jar",
          "url": "echosvg-script-0.1.jar",
          "size": 22190,
          "sha512": "3b021ee5303ec0a7c87d22571575663ffc7646d78e8c97efe3947c875535a1cb83487dec4db6bc16ae8180dcf0c60f17615be181589bcd40447e7b24f5785a63",
          "sha256": "4309815585473b43f1c3e67668ec325559b87de63dc6fca5186164705b83c8c0",
          "sha1": "4579093891ab902ebacb4d4feaf4b8c6e72db20e",
          "md5": "ad006dffbb883eb9c1ec9214cb13826b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.7.13"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-script-0.1.jar",
          "url": "echosvg-script-0.1.jar",
          "size": 22190,
          "sha512": "3b021ee5303ec0a7c87d22571575663ffc7646d78e8c97efe3947c875535a1cb83487dec4db6bc16ae8180dcf0c60f17615be181589bcd40447e7b24f5785a63",
          "sha256": "4309815585473b43f1c3e67668ec325559b87de63dc6fca5186164705b83c8c0",
          "sha1": "4579093891ab902ebacb4d4feaf4b8c6e72db20e",
          "md5": "ad006dffbb883eb9c1ec9214cb13826b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-script-0.1-sources.jar",
          "url": "echosvg-script-0.1-sources.jar",
          "size": 25574,
          "sha512": "fff1092d8efbfb6666c0dd66c8821fe0ba7c7d7e017df8d2aec7cf7b2868b26d4a825c590c6916280bf2280864987dd786163cbded16f4c8b7da5dd9ccae3a32",
          "sha256": "9220fcf0de35c68c4ace1f8f9afa4dafaf2024a1514e4a13cffcd598e39794b2",
          "sha1": "2c85d73864fbfe677fee5e9050a1a47fff8c6b2e",
          "md5": "2f91e23a1064684c618866473949b15b"
        }
      ]
    }
  ]
}
