{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-svgrasterizer",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svgrasterizer-0.2.jar",
          "url": "echosvg-svgrasterizer-0.2.jar",
          "size": 58863,
          "sha512": "5747d6acec58025ba1992d9169d2d08537c12d92bd9fc95f8970d931143465e888cb19e31213c247ba9c6c6ba482bae77bb59478a29f3775627bc72f19c4dde2",
          "sha256": "deb5494682e0e53c61d3ff307d1e07c3b2dbb745b4694e49020d1ae5c0cae26a",
          "sha1": "41ff18f39bc613aaefd87352478c353788d7951e",
          "md5": "29fec39a808672297a74115945fa1294"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svgrasterizer-0.2.jar",
          "url": "echosvg-svgrasterizer-0.2.jar",
          "size": 58863,
          "sha512": "5747d6acec58025ba1992d9169d2d08537c12d92bd9fc95f8970d931143465e888cb19e31213c247ba9c6c6ba482bae77bb59478a29f3775627bc72f19c4dde2",
          "sha256": "deb5494682e0e53c61d3ff307d1e07c3b2dbb745b4694e49020d1ae5c0cae26a",
          "sha1": "41ff18f39bc613aaefd87352478c353788d7951e",
          "md5": "29fec39a808672297a74115945fa1294"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-svgrasterizer-0.2-sources.jar",
          "url": "echosvg-svgrasterizer-0.2-sources.jar",
          "size": 36243,
          "sha512": "93ecc84bb90ff68cd7f190ea070d1c981f22963a1cf79993913fd014b89a08b034b94dbef7e1815db3d8eb148c31b674a560ce2d01e2edf5b731e9217c9c891c",
          "sha256": "ba6c83b64352c883343e00dcd3d16288832f70b94b62b18c73ffda9f213a67cd",
          "sha1": "de0e61abc96b033db087ff6b8771225c2db22e52",
          "md5": "17a145aaf136687ed007d809cac0f76d"
        }
      ]
    }
  ]
}
