{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "css4j-dom4j",
    "version": "3.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "css4j",
          "version": {
            "strictly": "[3.7.1,)",
            "requires": "[3.7.1,)",
            "prefers": "3.7.2"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "[1.6.0,)",
            "prefers": "2.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "css4j-dom4j-3.7.1.jar",
          "url": "css4j-dom4j-3.7.1.jar",
          "size": 70287,
          "sha512": "33ab1fedb64efb122350bd02277ec6c4ebac6f4175d6adf9032f6b56648549c470b049639725d4eec47d62d7c53b7ecb340e040cf4b5a70a17a4ef97482a6e0c",
          "sha256": "dffac6a1acf5594c349c4ae1358f9981acebd86406c6165eec7019bb66cc2bc9",
          "sha1": "e29c0846fced2dc0468b634e1ce1e596c11ea3fb",
          "md5": "38bdc3851c8e56d539b02fa114a941d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "css4j",
          "version": {
            "strictly": "[3.7.1,)",
            "requires": "[3.7.1,)",
            "prefers": "3.7.2"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "[1.6.0,)",
            "prefers": "2.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "css4j-dom4j-3.7.1.jar",
          "url": "css4j-dom4j-3.7.1.jar",
          "size": 70287,
          "sha512": "33ab1fedb64efb122350bd02277ec6c4ebac6f4175d6adf9032f6b56648549c470b049639725d4eec47d62d7c53b7ecb340e040cf4b5a70a17a4ef97482a6e0c",
          "sha256": "dffac6a1acf5594c349c4ae1358f9981acebd86406c6165eec7019bb66cc2bc9",
          "sha1": "e29c0846fced2dc0468b634e1ce1e596c11ea3fb",
          "md5": "38bdc3851c8e56d539b02fa114a941d0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "css4j-dom4j-3.7.1-javadoc.jar",
          "url": "css4j-dom4j-3.7.1-javadoc.jar",
          "size": 177705,
          "sha512": "7765c006ec8582c6bff91abf94a9340955f7ba0dfaece1075e5c1dfc58a0afd60eff51e59773b7335ec3dd515d505f354d4517affdbc90031a4acbcf509cb775",
          "sha256": "838d8358755d82c61692a5710015fc3a22d4a21222c6e12d8ddbec0b8e7659e5",
          "sha1": "c9375b3ff72debc30f4b15d4d5960867bb8b42c1",
          "md5": "7973ad1d901ad8844ad89d294fb17442"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "css4j-dom4j-3.7.1-sources.jar",
          "url": "css4j-dom4j-3.7.1-sources.jar",
          "size": 42071,
          "sha512": "b4626c07af3b0c0fe3e443dd325b260afeecf82f7ddd88081c20ee57d4508b974eeb13001af7d3920ca2ad2d475396dfd55a353c1bd2af60dbfc2540c5dce9d7",
          "sha256": "61d3cd6e818e783b354c6d9a59b3f8489fb6773c1bde602ba29a4a38412a8d26",
          "sha1": "e7d4e5eccc89335b1e0acec09a819192f2cfc990",
          "md5": "24bf320e03fb896153a657d6061b0bba"
        }
      ]
    },
    {
      "name": "xmlpullApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "css4j-dom4j-3.7.1.jar",
          "url": "css4j-dom4j-3.7.1.jar",
          "size": 70287,
          "sha512": "33ab1fedb64efb122350bd02277ec6c4ebac6f4175d6adf9032f6b56648549c470b049639725d4eec47d62d7c53b7ecb340e040cf4b5a70a17a4ef97482a6e0c",
          "sha256": "dffac6a1acf5594c349c4ae1358f9981acebd86406c6165eec7019bb66cc2bc9",
          "sha1": "e29c0846fced2dc0468b634e1ce1e596c11ea3fb",
          "md5": "38bdc3851c8e56d539b02fa114a941d0"
        }
      ],
      "capabilities": [
        {
          "group": "io.sf.carte",
          "name": "css4j-dom4j-xmlpull",
          "version": "3.7.1"
        }
      ]
    },
    {
      "name": "xmlpullRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "xmlpull",
          "module": "xmlpull",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "xpp3",
          "module": "xpp3_min",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "css4j-dom4j-3.7.1.jar",
          "url": "css4j-dom4j-3.7.1.jar",
          "size": 70287,
          "sha512": "33ab1fedb64efb122350bd02277ec6c4ebac6f4175d6adf9032f6b56648549c470b049639725d4eec47d62d7c53b7ecb340e040cf4b5a70a17a4ef97482a6e0c",
          "sha256": "dffac6a1acf5594c349c4ae1358f9981acebd86406c6165eec7019bb66cc2bc9",
          "sha1": "e29c0846fced2dc0468b634e1ce1e596c11ea3fb",
          "md5": "38bdc3851c8e56d539b02fa114a941d0"
        }
      ],
      "capabilities": [
        {
          "group": "io.sf.carte",
          "name": "css4j-dom4j-xmlpull",
          "version": "3.7.1"
        }
      ]
    },
    {
      "name": "useragentApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "css4j-dom4j-3.7.1.jar",
          "url": "css4j-dom4j-3.7.1.jar",
          "size": 70287,
          "sha512": "33ab1fedb64efb122350bd02277ec6c4ebac6f4175d6adf9032f6b56648549c470b049639725d4eec47d62d7c53b7ecb340e040cf4b5a70a17a4ef97482a6e0c",
          "sha256": "dffac6a1acf5594c349c4ae1358f9981acebd86406c6165eec7019bb66cc2bc9",
          "sha1": "e29c0846fced2dc0468b634e1ce1e596c11ea3fb",
          "md5": "38bdc3851c8e56d539b02fa114a941d0"
        }
      ],
      "capabilities": [
        {
          "group": "io.sf.carte",
          "name": "css4j-dom4j-useragent",
          "version": "3.7.1"
        }
      ]
    },
    {
      "name": "useragentRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "css4j-agent",
          "version": {
            "strictly": "[3.4.0,)",
            "requires": "[3.4.0,)",
            "prefers": "3.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "css4j-dom4j-3.7.1.jar",
          "url": "css4j-dom4j-3.7.1.jar",
          "size": 70287,
          "sha512": "33ab1fedb64efb122350bd02277ec6c4ebac6f4175d6adf9032f6b56648549c470b049639725d4eec47d62d7c53b7ecb340e040cf4b5a70a17a4ef97482a6e0c",
          "sha256": "dffac6a1acf5594c349c4ae1358f9981acebd86406c6165eec7019bb66cc2bc9",
          "sha1": "e29c0846fced2dc0468b634e1ce1e596c11ea3fb",
          "md5": "38bdc3851c8e56d539b02fa114a941d0"
        }
      ],
      "capabilities": [
        {
          "group": "io.sf.carte",
          "name": "css4j-dom4j-useragent",
          "version": "3.7.1"
        }
      ]
    }
  ]
}
