{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-css",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "css4j",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-css-1.1.jar",
          "url": "echosvg-css-1.1.jar",
          "size": 288331,
          "sha512": "e4e392ba8a2439b9e769f72a27dad2b9aaf411f123714bcfe2786c97df93ec35dca0c5ad785bd837530cec8afe05f4d2d8d1bec3501aa39c380ded0f2d0c2f0c",
          "sha256": "b9b7b6b04cbed24dea88ccea8a3308da4823480f6c98e1102d1e72453e9c0308",
          "sha1": "c20d0a272eec2f37fedcb2e330bf99b036776316",
          "md5": "875e35c8db4d8fe0a8f6860f50eb17f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "css4j",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-css-1.1.jar",
          "url": "echosvg-css-1.1.jar",
          "size": 288331,
          "sha512": "e4e392ba8a2439b9e769f72a27dad2b9aaf411f123714bcfe2786c97df93ec35dca0c5ad785bd837530cec8afe05f4d2d8d1bec3501aa39c380ded0f2d0c2f0c",
          "sha256": "b9b7b6b04cbed24dea88ccea8a3308da4823480f6c98e1102d1e72453e9c0308",
          "sha1": "c20d0a272eec2f37fedcb2e330bf99b036776316",
          "md5": "875e35c8db4d8fe0a8f6860f50eb17f3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-css-1.1-sources.jar",
          "url": "echosvg-css-1.1-sources.jar",
          "size": 208748,
          "sha512": "8710947a67cffa6c972b8afe2d3907d432d6bb7d43467d376c461f0d72043dcfef08d1af441bce0c5ef08e8b594ceec33f07bd219c4c813cde8a6016dcf02013",
          "sha256": "7a8192c0ed6abfe5b34f9310681c44ead11e2e2d183b90b4ff37579f473d9a37",
          "sha1": "2da7a32484814d005c013312c19a7039b6f262da",
          "md5": "d1a756397e68dff06d674541b00e2b96"
        }
      ]
    }
  ]
}
