{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-transcoder",
    "version": "2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-api",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-svg",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-svg2svg",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-tosvg",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-transcoder-2.5.jar",
          "url": "echosvg-transcoder-2.5.jar",
          "size": 5453,
          "sha512": "4c57900d43d715aa51a9661929e16c8c691e72a9524962745b4b56654d967c5e078d14d271df68d5110579fcd476e8b53a5fdc28c2d771ae0d68bfa3497ed1f3",
          "sha256": "fbc1ce35fa2bd345a58eaf95638104cd67c62bb35d4f2d0facb76341c103bce4",
          "sha1": "9a2d8ba962575e8dab4e6776aa8b48a9c9fd0076",
          "md5": "5bbe121066a0df3cd60947f9689dc2f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-api",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-svg",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-svg2svg",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-tosvg",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-transcoder-2.5.jar",
          "url": "echosvg-transcoder-2.5.jar",
          "size": 5453,
          "sha512": "4c57900d43d715aa51a9661929e16c8c691e72a9524962745b4b56654d967c5e078d14d271df68d5110579fcd476e8b53a5fdc28c2d771ae0d68bfa3497ed1f3",
          "sha256": "fbc1ce35fa2bd345a58eaf95638104cd67c62bb35d4f2d0facb76341c103bce4",
          "sha1": "9a2d8ba962575e8dab4e6776aa8b48a9c9fd0076",
          "md5": "5bbe121066a0df3cd60947f9689dc2f6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-transcoder-2.5-sources.jar",
          "url": "echosvg-transcoder-2.5-sources.jar",
          "size": 5747,
          "sha512": "3f40d63ccbad72408f9ed7482540c837a8f08c99c82b4d15795fe51be198f85b0f2ff4db3518e2be0f6a2f22986b237d8ff8a378c12014d45ad1df666538529f",
          "sha256": "a03c19f827e76123caa4b3d2bbc463e429f50c7439e48cc47c9fb95d48c95899",
          "sha1": "a36bfb1d7535f6bbe8b26946c5dd861d1a9f685f",
          "md5": "1d24d07243ba82f71ab542065274836c"
        }
      ]
    }
  ]
}
