{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-codec",
    "version": "2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "2.3"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-codec-2.3.jar",
          "url": "echosvg-codec-2.3.jar",
          "size": 104580,
          "sha512": "6aa57bfe2821f906c7a341f30d938caaa00df73384e4ad3f5737f1bc29955c35d7346404ee468c95fa17eb36ed3c8f47b3bf631d6d55328715634cf14c57d9ae",
          "sha256": "0907ae17225b5cbe1320d8b7e0443a8a5db305167e0ab2cd2d70154c53436569",
          "sha1": "55e8e236692014394d22817930d56d164d5fd382",
          "md5": "6cea3b533d23c57128f1f7b20bc5fd1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "2.3"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-codec-2.3.jar",
          "url": "echosvg-codec-2.3.jar",
          "size": 104580,
          "sha512": "6aa57bfe2821f906c7a341f30d938caaa00df73384e4ad3f5737f1bc29955c35d7346404ee468c95fa17eb36ed3c8f47b3bf631d6d55328715634cf14c57d9ae",
          "sha256": "0907ae17225b5cbe1320d8b7e0443a8a5db305167e0ab2cd2d70154c53436569",
          "sha1": "55e8e236692014394d22817930d56d164d5fd382",
          "md5": "6cea3b533d23c57128f1f7b20bc5fd1e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-codec-2.3-sources.jar",
          "url": "echosvg-codec-2.3-sources.jar",
          "size": 98548,
          "sha512": "c9bd7efc8e94599f63c096da20cbad8dfb3c80329d538d5437900570ba34055696f8c34197d70731e04f040648f2e29369374f7f19971f68d699a950be8c6a9f",
          "sha256": "d094c2db659eabb83f9ba9209aebf3e400910ead565a82404cb22d8cb02fd413",
          "sha1": "43701e8356c0e9c0d1fa55bfcde45c88c225fe8e",
          "md5": "2d8b5e02aff8d5fefac3f4df8f83711f"
        }
      ]
    }
  ]
}
