{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-transcoder-svg2svg",
    "version": "2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-api",
          "version": {
            "requires": "2.4"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-transcoder-svg2svg-2.4.jar",
          "url": "echosvg-transcoder-svg2svg-2.4.jar",
          "size": 29829,
          "sha512": "eaeb9d0a91ecd7e972cff5d379c383f7233bf8eafe54c6954bb9b07571a29a1dd6779f08e9461352afda4efb213ab97cf976b25ca914dabab936eb0311727d63",
          "sha256": "7ee27e81c363074ecc635e2aa05e8982693fa9692b94352ebbeab5efd6301c03",
          "sha1": "7cf48a1fb861a23c939032f8bbb4beffbc9de93d",
          "md5": "a5194e989c16b7645544216102d42b72"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-api",
          "version": {
            "requires": "2.4"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-transcoder-svg2svg-2.4.jar",
          "url": "echosvg-transcoder-svg2svg-2.4.jar",
          "size": 29829,
          "sha512": "eaeb9d0a91ecd7e972cff5d379c383f7233bf8eafe54c6954bb9b07571a29a1dd6779f08e9461352afda4efb213ab97cf976b25ca914dabab936eb0311727d63",
          "sha256": "7ee27e81c363074ecc635e2aa05e8982693fa9692b94352ebbeab5efd6301c03",
          "sha1": "7cf48a1fb861a23c939032f8bbb4beffbc9de93d",
          "md5": "a5194e989c16b7645544216102d42b72"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-transcoder-svg2svg-2.4-sources.jar",
          "url": "echosvg-transcoder-svg2svg-2.4-sources.jar",
          "size": 18654,
          "sha512": "ff425dd9aa92823fb220e730cdcffff76747b1f6ac1fb32f1666011b9178a4d52f086b323210e011e403c51e0957b7014597075a24a52ac6724cd74cee46d423",
          "sha256": "43eef158ef57eb7b0d562c953e6a4a0e477f7ec4b2217c83858c4909baa98ec0",
          "sha1": "803389452d3b17eab048a50930334b05189d5c8b",
          "md5": "7ddfaa973975620b2fd87825d3314b35"
        }
      ]
    }
  ]
}
