{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-all",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-extension",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-swing",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-slideshow",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgpp",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ttf2svg",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgrasterizer",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-all-0.1.2.jar",
          "url": "echosvg-all-0.1.2.jar",
          "size": 5348,
          "sha512": "ed2d33863502b16fce2308be67dc3efa68f530f95e46d3a6bf4b092a16124430bc89386cad33930921ecae28485b858ad27d568a57977d7911bbb169b38c8d0b",
          "sha256": "bf9a307fbc63ded96a29c6664ab30d27268544e78e261e267d46723264195e23",
          "sha1": "84f214a98d3093d78cbc8b30a86fa12d20e70978",
          "md5": "5984a235d4aafb2ca1f604ec87a0d1e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-extension",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-swing",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-slideshow",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgpp",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ttf2svg",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgrasterizer",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-all-0.1.2.jar",
          "url": "echosvg-all-0.1.2.jar",
          "size": 5348,
          "sha512": "ed2d33863502b16fce2308be67dc3efa68f530f95e46d3a6bf4b092a16124430bc89386cad33930921ecae28485b858ad27d568a57977d7911bbb169b38c8d0b",
          "sha256": "bf9a307fbc63ded96a29c6664ab30d27268544e78e261e267d46723264195e23",
          "sha1": "84f214a98d3093d78cbc8b30a86fa12d20e70978",
          "md5": "5984a235d4aafb2ca1f604ec87a0d1e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-all-0.1.2-sources.jar",
          "url": "echosvg-all-0.1.2-sources.jar",
          "size": 5510,
          "sha512": "48d9c6b91026c828f2c3e1c588a9594a09e5ca28f20674eb4386a645ae5e300960f5329c261784402d47d9fe17cb3017113382ac9faae9a0db221e41dcc8f67a",
          "sha256": "245b803863b3df06d2cb9a8613adf9683aed109c7c3660fe541c6f68be59f950",
          "sha1": "14303d6a5ccc01b9bb7896631f6399a54583cfd7",
          "md5": "8f054cc6f19e1fd88b12d15b7737bac3"
        }
      ]
    }
  ]
}
