{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-bridge",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gvt",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "xalan",
          "module": "xalan",
          "version": {
            "requires": "2.7.2"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-bridge-0.1.2.jar",
          "url": "echosvg-bridge-0.1.2.jar",
          "size": 719244,
          "sha512": "e7d9c15789618a95808cd9ed7b021c3bd507d96b2aafda27d78e72917f10d3b3be3816e68435d6c558439ef041ad3cf715ab0ac72b5ef3b12bb594acaa186aac",
          "sha256": "c85cad17cbd49aa8c914ced2d2f22f2395a6df8b8ff3c72c775d93faea99e3be",
          "sha1": "8edb2f0e0ec127cd7318eac522fa526700d1bbf5",
          "md5": "1c3d048636e6cfdfea77cf1fe83c60d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gvt",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "xalan",
          "module": "xalan",
          "version": {
            "requires": "2.7.2"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-bridge-0.1.2.jar",
          "url": "echosvg-bridge-0.1.2.jar",
          "size": 719244,
          "sha512": "e7d9c15789618a95808cd9ed7b021c3bd507d96b2aafda27d78e72917f10d3b3be3816e68435d6c558439ef041ad3cf715ab0ac72b5ef3b12bb594acaa186aac",
          "sha256": "c85cad17cbd49aa8c914ced2d2f22f2395a6df8b8ff3c72c775d93faea99e3be",
          "sha1": "8edb2f0e0ec127cd7318eac522fa526700d1bbf5",
          "md5": "1c3d048636e6cfdfea77cf1fe83c60d2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-bridge-0.1.2-sources.jar",
          "url": "echosvg-bridge-0.1.2-sources.jar",
          "size": 491155,
          "sha512": "7577480efdf5ec6f0416af0708a4b1f14bf97490b62b4839e993e729f1a5454d90bba197ff24fa0d1754658dc9e7e996bf7bcdb59b73d3da8df8250fa4de2a0d",
          "sha256": "53a09f005907ebd61935c10cc1a25d96cb72b4e2d45b3c3eacfc97176d055b97",
          "sha1": "ef39776fc31c744495f25f70f2d1b02fd9118b13",
          "md5": "ecac06409bd70cd4229769245ec39098"
        }
      ]
    }
  ]
}
