{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-extension",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-extension-1.2.1.jar",
          "url": "echosvg-extension-1.2.1.jar",
          "size": 72639,
          "sha512": "8be54eaed157ad0e621e593a2cd038914d9e9b9afe6c73f4fd807c9782c397d72fe5600aadeb0dd5eb2b09c5905a4f08c9d0b91da99dbc5b088073603ee425bd",
          "sha256": "bca594a2cc8fee518c1def8098fad458f1f7dd0f2333ffe4523c71088ec24a9f",
          "sha1": "86611fba040125aed581c99a7e1ea9a21a300fc5",
          "md5": "592f268e9022bf44b72a93ecb7b96373"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-extension-1.2.1.jar",
          "url": "echosvg-extension-1.2.1.jar",
          "size": 72639,
          "sha512": "8be54eaed157ad0e621e593a2cd038914d9e9b9afe6c73f4fd807c9782c397d72fe5600aadeb0dd5eb2b09c5905a4f08c9d0b91da99dbc5b088073603ee425bd",
          "sha256": "bca594a2cc8fee518c1def8098fad458f1f7dd0f2333ffe4523c71088ec24a9f",
          "sha1": "86611fba040125aed581c99a7e1ea9a21a300fc5",
          "md5": "592f268e9022bf44b72a93ecb7b96373"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-extension-1.2.1-sources.jar",
          "url": "echosvg-extension-1.2.1-sources.jar",
          "size": 67504,
          "sha512": "ead890965d8a96b3f408adee9624038da247da226a04e7d8b09f2cd079d98dbbbc3ee56a2abab5f83cdedd36cc265bfffae4d453e31f41b1ed32a2483a205086",
          "sha256": "e1a9cfb1ba203a24ae6acc8fe0e2219261f8b94208eec30473ca6f17343adbcb",
          "sha1": "d1e7dd758cfde2a75de9c5f1dd65377e18e0a09c",
          "md5": "957c42a843ca5d1cb7f73469fea09ba4"
        }
      ]
    }
  ]
}
