{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-swing",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-swing-2.0.jar",
          "url": "echosvg-swing-2.0.jar",
          "size": 197834,
          "sha512": "3ab2c4c2cc868be4c9eed947014fc0c3574584e4383348215e898ad2cddfaf35ed810dc1e6a0269d778828c7e29f29aa6cc934d89f6332acb10f1c43424ed3c8",
          "sha256": "be5c7ec6107870a201c6aa535a2b2b995edf279b44ee74dbfe3d99b4fa44f92b",
          "sha1": "cedea9f3a2c1f375c9767159699c18b9233710e0",
          "md5": "85dae3125cd12387810aa30a77fa253b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-swing-2.0.jar",
          "url": "echosvg-swing-2.0.jar",
          "size": 197834,
          "sha512": "3ab2c4c2cc868be4c9eed947014fc0c3574584e4383348215e898ad2cddfaf35ed810dc1e6a0269d778828c7e29f29aa6cc934d89f6332acb10f1c43424ed3c8",
          "sha256": "be5c7ec6107870a201c6aa535a2b2b995edf279b44ee74dbfe3d99b4fa44f92b",
          "sha1": "cedea9f3a2c1f375c9767159699c18b9233710e0",
          "md5": "85dae3125cd12387810aa30a77fa253b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-swing-2.0-sources.jar",
          "url": "echosvg-swing-2.0-sources.jar",
          "size": 100993,
          "sha512": "aaceb9dc3c4e83d29bbec71dd36cc411ab664604a3a8b15c0215d23c80f7f3eec508ac280e8d54a3694206d08e3e6c0cece090ea93280051fdb5096fb7736d8b",
          "sha256": "b4ad25c9d6042fa161cda6d0599d01d0762fb8d96fc27c66445ea5a1f3b7fad5",
          "sha1": "3463ec2f96f791c386da4d9963440cb2f4bdc6d3",
          "md5": "3c782fffade76604264afb876f14b4d7"
        }
      ]
    }
  ]
}
