{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-svg-dom",
    "version": "1.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "1.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svg-dom-1.2.4.jar",
          "url": "echosvg-svg-dom-1.2.4.jar",
          "size": 75537,
          "sha512": "12ceb8241ca56679a9aa0617f289391da1adc322e58f60e715de4be0d2178c7e7380376af4c4164bf6299eb7fa3d94cec39b98827853397fcd5545febf729ebf",
          "sha256": "21f3620b217e5ad5f3d4a166b347a5c4c2ff69e7671c9b926969093069b042ed",
          "sha1": "28e152245869873930e0503843ba8de09ddee20f",
          "md5": "55bc3f39ab6e50abf279e67f45273619"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "1.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svg-dom-1.2.4.jar",
          "url": "echosvg-svg-dom-1.2.4.jar",
          "size": 75537,
          "sha512": "12ceb8241ca56679a9aa0617f289391da1adc322e58f60e715de4be0d2178c7e7380376af4c4164bf6299eb7fa3d94cec39b98827853397fcd5545febf729ebf",
          "sha256": "21f3620b217e5ad5f3d4a166b347a5c4c2ff69e7671c9b926969093069b042ed",
          "sha1": "28e152245869873930e0503843ba8de09ddee20f",
          "md5": "55bc3f39ab6e50abf279e67f45273619"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-svg-dom-1.2.4-sources.jar",
          "url": "echosvg-svg-dom-1.2.4-sources.jar",
          "size": 70136,
          "sha512": "6db00910efbd0bfea6d36114c0f6ecfe015eef5dd8cb454f5f447d65027dee14388601174eeca746076058367f2f25ee2bf420e579398f5be4773d0da3f8c8dc",
          "sha256": "e3a41354d7671cb998ae2318bdeacd312e3fe988fd070ffbadfc09faf9415d36",
          "sha1": "374111164ef1b69eaca437f60ded1dab07df5cf2",
          "md5": "43b4376efa549a139997b0494f603bee"
        }
      ]
    }
  ]
}
