{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-bridge",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gvt",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.9"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-bridge-1.0.jar",
          "url": "echosvg-bridge-1.0.jar",
          "size": 720724,
          "sha512": "a5377c0724f6b462ab8708cbdf849ed1e266b855de03337cc7094dda52cbc8c6a23ad1bb188bbab7b21b0ce9fa520c360405e072208689b896212bdab8eb72cb",
          "sha256": "e3846ba01d0b9b6ad88269d04c94b932f98703af74845dcecf9c6a923035ea06",
          "sha1": "c0a2b7cfa0a42eb47af91ca74e4a5db6d57a63b1",
          "md5": "ca2a2bc00d77f3bf5fd44775be74ba29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "xml-apis",
          "module": "xml-apis",
          "version": {
            "requires": "1.4.01"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gvt",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.9"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-bridge-1.0.jar",
          "url": "echosvg-bridge-1.0.jar",
          "size": 720724,
          "sha512": "a5377c0724f6b462ab8708cbdf849ed1e266b855de03337cc7094dda52cbc8c6a23ad1bb188bbab7b21b0ce9fa520c360405e072208689b896212bdab8eb72cb",
          "sha256": "e3846ba01d0b9b6ad88269d04c94b932f98703af74845dcecf9c6a923035ea06",
          "sha1": "c0a2b7cfa0a42eb47af91ca74e4a5db6d57a63b1",
          "md5": "ca2a2bc00d77f3bf5fd44775be74ba29"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-bridge-1.0-sources.jar",
          "url": "echosvg-bridge-1.0-sources.jar",
          "size": 488325,
          "sha512": "5681adbf45a69ecd756b4793e7c9685aaf2991a4f8499104c5770f2bbe0aee801d0d73d7b8f5187fb2db268c8861fdbb2373b6bad5b37e02e5519db010f7ea4a",
          "sha256": "813fa7d37aee9ac708ee0ed8aef27824ee99ae0e19f2d1a12907fa596ba2fa57",
          "sha1": "ba9091868068d36808339cb709bc77d7edda12f6",
          "md5": "ce04dc0f091c3cfec68719b849a81e04"
        }
      ]
    }
  ]
}
