{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-ext",
    "version": "2.0-pre1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "echosvg-ext-2.0-pre1.jar",
          "url": "echosvg-ext-2.0-pre1.jar",
          "size": 9127,
          "sha512": "7f5d308a82c7b7308a998bfb1d913344e9e779fcdc62594a12fc7d55ccaf0886d6932a8c6a5f7083d35b155ffbe8df4c066d879b776b87c76c836e7e1fa22caf",
          "sha256": "e3a0f328c33b71a0420f020d9755b42f8f34aea43d46de475203e0fbf586cbc8",
          "sha1": "de7c6560d04b9b73a60e03b4a6622dfe6783a692",
          "md5": "6900bb7abc9b486c286dae1366597022"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-ext-2.0-pre1.jar",
          "url": "echosvg-ext-2.0-pre1.jar",
          "size": 9127,
          "sha512": "7f5d308a82c7b7308a998bfb1d913344e9e779fcdc62594a12fc7d55ccaf0886d6932a8c6a5f7083d35b155ffbe8df4c066d879b776b87c76c836e7e1fa22caf",
          "sha256": "e3a0f328c33b71a0420f020d9755b42f8f34aea43d46de475203e0fbf586cbc8",
          "sha1": "de7c6560d04b9b73a60e03b4a6622dfe6783a692",
          "md5": "6900bb7abc9b486c286dae1366597022"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-ext-2.0-pre1-sources.jar",
          "url": "echosvg-ext-2.0-pre1-sources.jar",
          "size": 14952,
          "sha512": "18e92a60a0d0442663debac828695179ddd6e1aca289fc6d85bc56c83c002dcaca481e942728562e51b98d00c7ad6935440a4c627248473b5990ab7e3204061c",
          "sha256": "1ad54803aaba5eb1d74677c7e3c02a6dd95dbea6afe431ce7f594e9d5f2e9549",
          "sha1": "e4b1ff569e38fffcc5c5776aae31e266300b1d0c",
          "md5": "853467b217a38e0f07b6af663c773c4f"
        }
      ]
    }
  ]
}
