{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-svg-dom",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "0.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "0.3"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svg-dom-0.3.jar",
          "url": "echosvg-svg-dom-0.3.jar",
          "size": 73973,
          "sha512": "79962436156661c051d656e9e6275db36b1b4cd3c3a6b61402b64dfde22ba47c479b65dcd452b33985305848bfe126fc0a260cbbca97ae5a5319b0313feddd9c",
          "sha256": "76e5359793be75edd2f0d552e622ea59cfbc7423940ab678a8c6d85c102c87c2",
          "sha1": "ff740513a84ebb8693f4f35b197825c98d0ac8b1",
          "md5": "808c096397af33cfa9b15db78782aa43"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "xml-apis",
          "module": "xml-apis",
          "version": {
            "requires": "1.4.01"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "0.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "0.3"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svg-dom-0.3.jar",
          "url": "echosvg-svg-dom-0.3.jar",
          "size": 73973,
          "sha512": "79962436156661c051d656e9e6275db36b1b4cd3c3a6b61402b64dfde22ba47c479b65dcd452b33985305848bfe126fc0a260cbbca97ae5a5319b0313feddd9c",
          "sha256": "76e5359793be75edd2f0d552e622ea59cfbc7423940ab678a8c6d85c102c87c2",
          "sha1": "ff740513a84ebb8693f4f35b197825c98d0ac8b1",
          "md5": "808c096397af33cfa9b15db78782aa43"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-svg-dom-0.3-sources.jar",
          "url": "echosvg-svg-dom-0.3-sources.jar",
          "size": 69300,
          "sha512": "ab7be80d49017f97c30be426c2e9cda4f73310c9b82dc1885cb8f8ee35ed8facc33dd56224d6d302c4e585501625acb9336f88bd7c8ec4aa92c2039a7e6e8dec",
          "sha256": "d0d91a47d800f4442e338ecb6657f9f9fc41102268384b75280e3af3dee8f4b4",
          "sha1": "e95d55b445ed0276fd87989e29d2e0473842a172",
          "md5": "60c4ae9ec1989674f4f6441c23f24c26"
        }
      ]
    }
  ]
}
