{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-transcoder",
    "version": "2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-api",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-svg",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-svg2svg",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-tosvg",
          "version": {
            "requires": "2.3"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-transcoder-2.3.jar",
          "url": "echosvg-transcoder-2.3.jar",
          "size": 5452,
          "sha512": "20e21db5471cb527cf2e9e8b5d6f1bd3d8479d8956c312b547c278c50ba07aa4b63f1d4d5e958e3c811d0890db9d760bbf4ea7632465936622cbca3a89e308e4",
          "sha256": "a943048017f03551b4478df89314b1fa12ef74b55ce7f152ddf665372d5c8863",
          "sha1": "83594bc616bfe3beeb5f4cbdb28d907ac4d7f6f1",
          "md5": "e37bb878be075857c9db8622a6030572"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-api",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-svg",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-svg2svg",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-tosvg",
          "version": {
            "requires": "2.3"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-transcoder-2.3.jar",
          "url": "echosvg-transcoder-2.3.jar",
          "size": 5452,
          "sha512": "20e21db5471cb527cf2e9e8b5d6f1bd3d8479d8956c312b547c278c50ba07aa4b63f1d4d5e958e3c811d0890db9d760bbf4ea7632465936622cbca3a89e308e4",
          "sha256": "a943048017f03551b4478df89314b1fa12ef74b55ce7f152ddf665372d5c8863",
          "sha1": "83594bc616bfe3beeb5f4cbdb28d907ac4d7f6f1",
          "md5": "e37bb878be075857c9db8622a6030572"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-transcoder-2.3-sources.jar",
          "url": "echosvg-transcoder-2.3-sources.jar",
          "size": 5721,
          "sha512": "9cfb864935863280b3e38b10204a8dc8bc479a83c728b0e9ec3a7cefd91d0c55dcec8f1af7d9e974988939234f0925403aa92132a647248ba9b6960635299ce9",
          "sha256": "0c5c63b95424d72ace3e63c1b02c4974872e74849f19162e757b705794b8cc21",
          "sha1": "1a03d701f47a9ce4f71347cb757175b208b7f580",
          "md5": "a0fbe9dc2abb7492b90ee6da566042df"
        }
      ]
    }
  ]
}
