{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-xml",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-xml-0.2.jar",
          "url": "echosvg-xml-0.2.jar",
          "size": 32231,
          "sha512": "2ec8ad0cf3f56ea2d3e9885888744c3db946a89f4b77663b597a70fb584855ef7addfb19d7c4347919ab2aa9a682b8e53b7114396b3b6381ff4c6d7c0060beee",
          "sha256": "b12ab32bb6e6aec0186aab79d027b0085095efe42646519232d52016c68b1e77",
          "sha1": "709d802c5fd10ba0b3f5891fc2c6fa5c880f57f4",
          "md5": "0aa0209294ba7266b3a9d154a3c788cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-xml-0.2.jar",
          "url": "echosvg-xml-0.2.jar",
          "size": 32231,
          "sha512": "2ec8ad0cf3f56ea2d3e9885888744c3db946a89f4b77663b597a70fb584855ef7addfb19d7c4347919ab2aa9a682b8e53b7114396b3b6381ff4c6d7c0060beee",
          "sha256": "b12ab32bb6e6aec0186aab79d027b0085095efe42646519232d52016c68b1e77",
          "sha1": "709d802c5fd10ba0b3f5891fc2c6fa5c880f57f4",
          "md5": "0aa0209294ba7266b3a9d154a3c788cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-xml-0.2-sources.jar",
          "url": "echosvg-xml-0.2-sources.jar",
          "size": 23431,
          "sha512": "0c94ea07fa25cf22b1c453cd5841f185aa850e53d3c0e72e4bc61d1dd640a75454915ca3928a24b1c1abfea03013ed91542ff7612cbb429c4586143dbe8dbe5e",
          "sha256": "28a1c3c7907afeeb7879e709a001f6c73048188e7d27caa2adc1d6573e8f465e",
          "sha1": "a7ebda2f92f08d989f82f0e9e87935ed2913dbe3",
          "md5": "03c3e20da810dc6b16ac7aed628c9fc8"
        }
      ]
    }
  ]
}
