{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-gui-util",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "0.3"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-gui-util-0.3.jar",
          "url": "echosvg-gui-util-0.3.jar",
          "size": 176250,
          "sha512": "f23d50fdb0e7cbdbd2c49ac2d2942656a72994b589ffae73632b57c4e0d2198d4838e93787c4911dd349fc294b6448c0d7fa53642c20ddf0d8f22be0e7593ecf",
          "sha256": "168f5333af5cacb4dc12427455778c7d37aed398e2ff41fadb4b6efc5e7c6306",
          "sha1": "d581f4fd8be349ca3096eaaabdaf6213706e0b3a",
          "md5": "1cd634bb42d342d17547fc0493a6a08a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "0.3"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-gui-util-0.3.jar",
          "url": "echosvg-gui-util-0.3.jar",
          "size": 176250,
          "sha512": "f23d50fdb0e7cbdbd2c49ac2d2942656a72994b589ffae73632b57c4e0d2198d4838e93787c4911dd349fc294b6448c0d7fa53642c20ddf0d8f22be0e7593ecf",
          "sha256": "168f5333af5cacb4dc12427455778c7d37aed398e2ff41fadb4b6efc5e7c6306",
          "sha1": "d581f4fd8be349ca3096eaaabdaf6213706e0b3a",
          "md5": "1cd634bb42d342d17547fc0493a6a08a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-gui-util-0.3-sources.jar",
          "url": "echosvg-gui-util-0.3-sources.jar",
          "size": 119785,
          "sha512": "865b6d6c7bf5d9b3522918132e13fb88d112065dcb6d38998aa3cb46e2ce2ef0c993fba45af5ecf52b2b61e72c2ae1687733343bc5c26aefb8110b66b4920b61",
          "sha256": "be11e3391c62bc3f0a7c16ff7423fe81686eea61cb8b975befc350a839b0c3d5",
          "sha1": "d603536ddc5dfa785b5805d1f7a4b062907fa0e6",
          "md5": "6993dd34d6a9672163649654597bb155"
        }
      ]
    }
  ]
}
