{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-gui-util",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-gui-util-2.0.1.jar",
          "url": "echosvg-gui-util-2.0.1.jar",
          "size": 177536,
          "sha512": "f9110645c7bc086b85e1da51cf8b88adc978000447d07d80d9d27ab96f18ccdac17dba07b7a442b66858ab891fd366dab3b69be8a38bd0626636d717637587c2",
          "sha256": "2adb139ef68910ff93bdcec906f6f8b7e3f4f45cf711ea0377e28161e11e4219",
          "sha1": "1851c8124c697b62ddff9cac2e7d7ff3a91a3a9d",
          "md5": "d323444c4c2e9f94046f6fb1a192519a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-gui-util-2.0.1.jar",
          "url": "echosvg-gui-util-2.0.1.jar",
          "size": 177536,
          "sha512": "f9110645c7bc086b85e1da51cf8b88adc978000447d07d80d9d27ab96f18ccdac17dba07b7a442b66858ab891fd366dab3b69be8a38bd0626636d717637587c2",
          "sha256": "2adb139ef68910ff93bdcec906f6f8b7e3f4f45cf711ea0377e28161e11e4219",
          "sha1": "1851c8124c697b62ddff9cac2e7d7ff3a91a3a9d",
          "md5": "d323444c4c2e9f94046f6fb1a192519a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-gui-util-2.0.1-sources.jar",
          "url": "echosvg-gui-util-2.0.1-sources.jar",
          "size": 120184,
          "sha512": "04da5eb91582064e9e0cc08e2d3ad17ff6091bca25486c35fe36ed4e19dea83e67440862a98bbfb432a4ba649886cdd7834fcb217d1eefb268f63ba7da0ad27b",
          "sha256": "6cdc508dc46c24bd6d5207db36d94d01e9f993339f8882fee0d0706d198310b7",
          "sha1": "713b2cff8759ad244b3b0a19fb06e456a54cc45f",
          "md5": "0651403b7facdd8598d899a8fe351354"
        }
      ]
    }
  ]
}
