{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-all",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-extension",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-swing",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-slideshow",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgpp",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ttf2svg",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgrasterizer",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-all-0.1.1.jar",
          "url": "echosvg-all-0.1.1.jar",
          "size": 5347,
          "sha512": "9a677a86fbcb257ddff5b460adbfebc3eece6cff603ec898da5c73d3c22dc36c44078080ba9162a283695776c062635a2d8457d760f48724b6fc8124d77db900",
          "sha256": "da437200dfe9b08fc7bb60a9dd9bdf3c373a98c2af3ca2a367fe412a7840bea9",
          "sha1": "3cf3540696ee196b63138e807e47796bf6f47b98",
          "md5": "54fc538b97cfff8c89e377fe7b3b48c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-extension",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-swing",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-slideshow",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgpp",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ttf2svg",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgrasterizer",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-all-0.1.1.jar",
          "url": "echosvg-all-0.1.1.jar",
          "size": 5347,
          "sha512": "9a677a86fbcb257ddff5b460adbfebc3eece6cff603ec898da5c73d3c22dc36c44078080ba9162a283695776c062635a2d8457d760f48724b6fc8124d77db900",
          "sha256": "da437200dfe9b08fc7bb60a9dd9bdf3c373a98c2af3ca2a367fe412a7840bea9",
          "sha1": "3cf3540696ee196b63138e807e47796bf6f47b98",
          "md5": "54fc538b97cfff8c89e377fe7b3b48c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-all-0.1.1-sources.jar",
          "url": "echosvg-all-0.1.1-sources.jar",
          "size": 5494,
          "sha512": "1a77283d109a67204331d5434f0ddaa8a8da5d37fe596729c5f521c91536de8febb3b0bb7ca7f29a7209e74e036a1a99ececdd2cd8f5fbaea94106b9201f45f3",
          "sha256": "d7916210656c922134b0c59be3e8079e752a51ddf0becc8b88ae621508f75388",
          "sha1": "dd68c93bd3ef3304b74c82116d1de4190900d25e",
          "md5": "f6bae1206514a864a36123bdd6e0f97a"
        }
      ]
    }
  ]
}
