{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-parser",
    "version": "2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "css4j",
          "version": {
            "requires": "6.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-parser-2.2.jar",
          "url": "echosvg-parser-2.2.jar",
          "size": 87192,
          "sha512": "efec21da63d56dd2c72072a32b5eca873b6a85f250c92e7ff34586aec288987dd9ce1eaa9346260fbafd27f77eaf2644d3841f64c711e764e35bdaffe8c66a62",
          "sha256": "081059a4ba00cf97725b004af07aa9e7af7aa8fdca3d8c2f97c031b50e4eb79d",
          "sha1": "954b0d6569efcc2ce06a1b4c323589e99730c130",
          "md5": "7b005c584eb7c8b661be1a9b504d921b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "css4j",
          "version": {
            "requires": "6.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-parser-2.2.jar",
          "url": "echosvg-parser-2.2.jar",
          "size": 87192,
          "sha512": "efec21da63d56dd2c72072a32b5eca873b6a85f250c92e7ff34586aec288987dd9ce1eaa9346260fbafd27f77eaf2644d3841f64c711e764e35bdaffe8c66a62",
          "sha256": "081059a4ba00cf97725b004af07aa9e7af7aa8fdca3d8c2f97c031b50e4eb79d",
          "sha1": "954b0d6569efcc2ce06a1b4c323589e99730c130",
          "md5": "7b005c584eb7c8b661be1a9b504d921b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-parser-2.2-sources.jar",
          "url": "echosvg-parser-2.2-sources.jar",
          "size": 87063,
          "sha512": "94a778b99cda6fe773101edd0bed1e9dbd329a5ff1151d312eb0d3eb1eeed3919be86ef8bdd6f3f50f2fcabe3bdc0609be9757af0cffd1f2cd7f5065a97843bd",
          "sha256": "375815ac82e6d89d203aca3123f30ea2a98b894ab2ee9aa7ea3c442f6770d644",
          "sha1": "08f9d557f9d942e66367eb2ec9a982dedcb4b60b",
          "md5": "fb43d1f48df13b5ab33fa58f8c41b84d"
        }
      ]
    }
  ]
}
