{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-i18n",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "echosvg-i18n-0.1.jar",
          "url": "echosvg-i18n-0.1.jar",
          "size": 10163,
          "sha512": "ab803b7beee601952d11c09a4f18e6ed6382537805ebcb945872cac8d1c99003ef35bc0f6e2a7e467d787b264ccc2ec9a175ce11bb8aeacaf0f2fd42b7603ebf",
          "sha256": "e47410b331f71f3c1ffee2d65d273c72b88b7763cd453c406ff988045487245f",
          "sha1": "95379b72133fed70e496bae2a1b05eb7b46283bf",
          "md5": "b5dbce1b431c5ef20d1feadfc5b97817"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-i18n-0.1.jar",
          "url": "echosvg-i18n-0.1.jar",
          "size": 10163,
          "sha512": "ab803b7beee601952d11c09a4f18e6ed6382537805ebcb945872cac8d1c99003ef35bc0f6e2a7e467d787b264ccc2ec9a175ce11bb8aeacaf0f2fd42b7603ebf",
          "sha256": "e47410b331f71f3c1ffee2d65d273c72b88b7763cd453c406ff988045487245f",
          "sha1": "95379b72133fed70e496bae2a1b05eb7b46283bf",
          "md5": "b5dbce1b431c5ef20d1feadfc5b97817"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-i18n-0.1-sources.jar",
          "url": "echosvg-i18n-0.1-sources.jar",
          "size": 12301,
          "sha512": "07ff2d66500792e9cf82d3ecbcf04c6e83dd9ca32e83d60e292200872adca92a394169fd5713ef4ab87f2eca20f77cbb4f82745dd64f88e087b132bb5de5777a",
          "sha256": "cc59aa81b1d504ea75a42ce1a04cc669f4844a9cbde127e3467e3a9fff28d897",
          "sha1": "50e6656bcf400d10fb8f58df114b096c37d26a8a",
          "md5": "b3ae401782ffdbcd62105a3d4483c656"
        }
      ]
    }
  ]
}
