{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-gui-util",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-gui-util-0.2.jar",
          "url": "echosvg-gui-util-0.2.jar",
          "size": 176325,
          "sha512": "5e27bfd85d1bd516187fe13e3a67fa1b29402e80fd1a6b981d2f8e977768f279f0bff55f76540eaaa4d9ea97ed713cb87227a786e4aa3f094442da4d83a79b4b",
          "sha256": "052661abde0056757b412bfe28e5b5c7295ff1a5e057b738b9a84dbaa303907d",
          "sha1": "48ea23182ee11ff99487d4abeb9d38d296c9d480",
          "md5": "dabdb23854654b0697b73fd591f0e949"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-gui-util-0.2.jar",
          "url": "echosvg-gui-util-0.2.jar",
          "size": 176325,
          "sha512": "5e27bfd85d1bd516187fe13e3a67fa1b29402e80fd1a6b981d2f8e977768f279f0bff55f76540eaaa4d9ea97ed713cb87227a786e4aa3f094442da4d83a79b4b",
          "sha256": "052661abde0056757b412bfe28e5b5c7295ff1a5e057b738b9a84dbaa303907d",
          "sha1": "48ea23182ee11ff99487d4abeb9d38d296c9d480",
          "md5": "dabdb23854654b0697b73fd591f0e949"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-gui-util-0.2-sources.jar",
          "url": "echosvg-gui-util-0.2-sources.jar",
          "size": 120245,
          "sha512": "a70e30e2a28ec24903f404b76e608caa9b89de0155ec4d25b3ae48aa155d4377b3c07396e2a2d3f0d8dc887e292bf4aaa0b2fe63900cc32c973b6a2a7eaf3f07",
          "sha256": "7db72505876dd8efdcdfed6cd531305cc281f0dc30283ad6fc1cf93e24b205b7",
          "sha1": "ff5203fabe001b060c3c25bbed47934e4933ac15",
          "md5": "0a0aee89fa9414eb3f80532caedbe405"
        }
      ]
    }
  ]
}
