{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-all",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-extension",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-swing",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-slideshow",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgpp",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ttf2svg",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgrasterizer",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-all-0.1.jar",
          "url": "echosvg-all-0.1.jar",
          "size": 5322,
          "sha512": "04f06c6ecc2b1b02a356dbb388447cbff433a8c3e09bc5c11cafd2d99decae6aa92ae18b5b09272c1e350620ba11b985f07c105e9d92a1ab9115bd2f1874ea68",
          "sha256": "5554c715ad3af4032d0d897ebec89344a89c3ec63b894da5799d0b76f6a962f7",
          "sha1": "471935c99e58a28f5cd8f61771990932d6bf1a15",
          "md5": "a6f1b9554b9c1544f1f07d767bddc237"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-extension",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-swing",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-slideshow",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgpp",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ttf2svg",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgrasterizer",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-all-0.1.jar",
          "url": "echosvg-all-0.1.jar",
          "size": 5322,
          "sha512": "04f06c6ecc2b1b02a356dbb388447cbff433a8c3e09bc5c11cafd2d99decae6aa92ae18b5b09272c1e350620ba11b985f07c105e9d92a1ab9115bd2f1874ea68",
          "sha256": "5554c715ad3af4032d0d897ebec89344a89c3ec63b894da5799d0b76f6a962f7",
          "sha1": "471935c99e58a28f5cd8f61771990932d6bf1a15",
          "md5": "a6f1b9554b9c1544f1f07d767bddc237"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-all-0.1-sources.jar",
          "url": "echosvg-all-0.1-sources.jar",
          "size": 5466,
          "sha512": "1177256731543c33a44fa4409681c98c548f2399abb94c4c7bce281cee173ff2b30e7dc0cac02bd565d7dc56fc8992ee440052ed007f509fbb9114012c238f6c",
          "sha256": "3a14edc56da5e5c301d920bb1b62ba7566b4458eec5b4cd9378f679ec713a6e9",
          "sha1": "d60d27b3178bd2e0ce40c082c1ab7a676c6960d1",
          "md5": "15b0258d2c6e4298b9bbe38e774af57c"
        }
      ]
    }
  ]
}
