{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-xml",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-xml-0.1.2.jar",
          "url": "echosvg-xml-0.1.2.jar",
          "size": 32231,
          "sha512": "de0cb996d00f1fc882ee1c51b5791ac66a29845eb0bf5d63cf979a6243bfd840f04299a86d61fd2c499742be08714791d0a18967858b861c21568410ffb20a70",
          "sha256": "35902ed51cfd2fdef29fdd47cfbf7f85b26a7a27541a3b33bd6704f277fb699d",
          "sha1": "703534c4194c5fe80d3d4bfa4a4ae8cc8b4fa88c",
          "md5": "2df0c5b3d01891104070e18a94148e5e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-xml-0.1.2.jar",
          "url": "echosvg-xml-0.1.2.jar",
          "size": 32231,
          "sha512": "de0cb996d00f1fc882ee1c51b5791ac66a29845eb0bf5d63cf979a6243bfd840f04299a86d61fd2c499742be08714791d0a18967858b861c21568410ffb20a70",
          "sha256": "35902ed51cfd2fdef29fdd47cfbf7f85b26a7a27541a3b33bd6704f277fb699d",
          "sha1": "703534c4194c5fe80d3d4bfa4a4ae8cc8b4fa88c",
          "md5": "2df0c5b3d01891104070e18a94148e5e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-xml-0.1.2-sources.jar",
          "url": "echosvg-xml-0.1.2-sources.jar",
          "size": 23431,
          "sha512": "0c94ea07fa25cf22b1c453cd5841f185aa850e53d3c0e72e4bc61d1dd640a75454915ca3928a24b1c1abfea03013ed91542ff7612cbb429c4586143dbe8dbe5e",
          "sha256": "28a1c3c7907afeeb7879e709a001f6c73048188e7d27caa2adc1d6573e8f465e",
          "sha1": "a7ebda2f92f08d989f82f0e9e87935ed2913dbe3",
          "md5": "03c3e20da810dc6b16ac7aed628c9fc8"
        }
      ]
    }
  ]
}
