{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-awt-util",
    "version": "2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "2.3"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-awt-util-2.3.jar",
          "url": "echosvg-awt-util-2.3.jar",
          "size": 423500,
          "sha512": "c231bae2b2a5afb821b7fd92519d6d1b5627172a422413527662a283b94ce545c3fcad6a4acc319089a8eefec142003ab8c0c3a347a39ab9ed3871fb10856186",
          "sha256": "3b526de99ce2ab80084ad45496da2de9647f38c02663991573245db2c2d11cf4",
          "sha1": "241ca10bbaa194efd4f7224a44a4851ac7d81bbe",
          "md5": "1c75f89a232a32f5bbedfa46f5e08616"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "2.3"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-awt-util-2.3.jar",
          "url": "echosvg-awt-util-2.3.jar",
          "size": 423500,
          "sha512": "c231bae2b2a5afb821b7fd92519d6d1b5627172a422413527662a283b94ce545c3fcad6a4acc319089a8eefec142003ab8c0c3a347a39ab9ed3871fb10856186",
          "sha256": "3b526de99ce2ab80084ad45496da2de9647f38c02663991573245db2c2d11cf4",
          "sha1": "241ca10bbaa194efd4f7224a44a4851ac7d81bbe",
          "md5": "1c75f89a232a32f5bbedfa46f5e08616"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-awt-util-2.3-sources.jar",
          "url": "echosvg-awt-util-2.3-sources.jar",
          "size": 392955,
          "sha512": "00629c334b9def0937221f32377739419bc286c1e878bc1d1d1dd5b5952919f01a445f473b77e32960f3cdd42cf9fd4067876c4e18d113d4c620d9e76a7a26ef",
          "sha256": "1d747bea014aa9b5d2fc31e81bd087a903d002b6c25cb66d40a37c8c71adf211",
          "sha1": "bab3d7dbbe081d7c441f81d0db5efe303b6a5cc7",
          "md5": "10590874c7bfb4d918f3c82f4cbafcbf"
        }
      ]
    }
  ]
}
