{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-anim",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-anim-2.0.1.jar",
          "url": "echosvg-anim-2.0.1.jar",
          "size": 516239,
          "sha512": "e0451fe5e53e2aae8d923b6dac09334a92ccd4b1f31b58b8605ac7ded9c5e0b8d2c0fc4902d97d2c699857c99619a8f96f31658300832c11868e5941140cd6e8",
          "sha256": "2e463b514b596a15fa0c0f0e1b85e6e4bc6ab7a7e65ae8cbddf83272709befac",
          "sha1": "c0bf071197a614d6b963af7b59f69aa6e84d3559",
          "md5": "cda4439485d422340709faed9d7fe7c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-anim-2.0.1.jar",
          "url": "echosvg-anim-2.0.1.jar",
          "size": 516239,
          "sha512": "e0451fe5e53e2aae8d923b6dac09334a92ccd4b1f31b58b8605ac7ded9c5e0b8d2c0fc4902d97d2c699857c99619a8f96f31658300832c11868e5941140cd6e8",
          "sha256": "2e463b514b596a15fa0c0f0e1b85e6e4bc6ab7a7e65ae8cbddf83272709befac",
          "sha1": "c0bf071197a614d6b963af7b59f69aa6e84d3559",
          "md5": "cda4439485d422340709faed9d7fe7c1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-anim-2.0.1-sources.jar",
          "url": "echosvg-anim-2.0.1-sources.jar",
          "size": 382520,
          "sha512": "429433fc2d66486a8b9847c862c252389dac212927ff0cf40c84d2cdecd9d635b4410e42ed0fe71f27cbe0537aeed55bed81b9df43dba8a1ec117a5b0f27c2da",
          "sha256": "85d41449215bb05838aaa19d61698719adf67d5151bfa5b4c9f6de7008bd9d8a",
          "sha1": "bad263c59c85615fd03b81bb3eec6dea100b1c88",
          "md5": "297968e623335b7ba998535708515d7a"
        }
      ]
    }
  ]
}
