{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "carte-util",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "carte-util-3.5.0.jar",
          "url": "carte-util-3.5.0.jar",
          "size": 5244,
          "sha512": "fb9ba5083e9be480281650742f54a2328bdd6f99250f1cf4d7e38ba9f002e4ed2ce0e873577a9d8fff72b3310de5e1585f32de27028f2e000ddad57288935746",
          "sha256": "f143db083c2bc7bfe57bed8c29daf56be8151bf921690c332b95dbe7edd2c4d3",
          "sha1": "08ab99ce482c57fd9452de39b7fd4e9c2edca0d3",
          "md5": "e985dc992a8abd3b7d0d51868d93ff56"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "carte-util-3.5.0.jar",
          "url": "carte-util-3.5.0.jar",
          "size": 5244,
          "sha512": "fb9ba5083e9be480281650742f54a2328bdd6f99250f1cf4d7e38ba9f002e4ed2ce0e873577a9d8fff72b3310de5e1585f32de27028f2e000ddad57288935746",
          "sha256": "f143db083c2bc7bfe57bed8c29daf56be8151bf921690c332b95dbe7edd2c4d3",
          "sha1": "08ab99ce482c57fd9452de39b7fd4e9c2edca0d3",
          "md5": "e985dc992a8abd3b7d0d51868d93ff56"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "carte-util-3.5.0-javadoc.jar",
          "url": "carte-util-3.5.0-javadoc.jar",
          "size": 126798,
          "sha512": "f111280a4e2200b4cb70773f9b428aa444f5e70db7745cf27ecbbabf86598cec05a54652c181e7999988699505a9f1629f7b7c7a22987f27dfeec08db2a2538f",
          "sha256": "3aa38fc6b92a719fe83d90f92814b9625be0843e8ffe35402d0f97b6ef679f23",
          "sha1": "f5f1a3115e4ee3b1b98c0a5de9381e0d95d399b4",
          "md5": "ae50b48fff7e5dd09b34db235bffab76"
        },
        {
          "name": "carte-util-3.5.0-javadoc.jar",
          "url": "carte-util-3.5.0-javadoc.jar",
          "size": 126798,
          "sha512": "f111280a4e2200b4cb70773f9b428aa444f5e70db7745cf27ecbbabf86598cec05a54652c181e7999988699505a9f1629f7b7c7a22987f27dfeec08db2a2538f",
          "sha256": "3aa38fc6b92a719fe83d90f92814b9625be0843e8ffe35402d0f97b6ef679f23",
          "sha1": "f5f1a3115e4ee3b1b98c0a5de9381e0d95d399b4",
          "md5": "ae50b48fff7e5dd09b34db235bffab76"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "carte-util-3.5.0-sources.jar",
          "url": "carte-util-3.5.0-sources.jar",
          "size": 6215,
          "sha512": "2a9ab166669e0f81195f2035fff95827c6beb50bdd4370a860f043544f5000ac309026021c838081e7eeda6fb829c9d6f21d12aac80b2cca00aa98b3f022543f",
          "sha256": "ed747c791f48be61aa6db159de12819cd76f2c12e40b43705fb8af49d64b4f97",
          "sha1": "9d6dcf64fd2ab9a20c10b489ccfc20ac8371652f",
          "md5": "190e27eaf1aa4e6fe06cafa6eb1d10ac"
        }
      ]
    }
  ]
}
