{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-xml",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-xml-2.0.1.jar",
          "url": "echosvg-xml-2.0.1.jar",
          "size": 32554,
          "sha512": "1380a3f5db53c53eb4aad46f80c09ea6056d861f5c1f9f9aec6d771d7e9695b207201f4c7ba28785f20a714f3d6cedd76db7db7191f412b662ed983dc2b000fe",
          "sha256": "2bdac8322e329224729067f8bc8a522e4438ae01ed68ad688642b493a1cdc825",
          "sha1": "14e60ff7b69c0f2f8e8cd5cb4e44ed3929faa339",
          "md5": "cadd4533601668159d84c08efb8d2041"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-xml-2.0.1.jar",
          "url": "echosvg-xml-2.0.1.jar",
          "size": 32554,
          "sha512": "1380a3f5db53c53eb4aad46f80c09ea6056d861f5c1f9f9aec6d771d7e9695b207201f4c7ba28785f20a714f3d6cedd76db7db7191f412b662ed983dc2b000fe",
          "sha256": "2bdac8322e329224729067f8bc8a522e4438ae01ed68ad688642b493a1cdc825",
          "sha1": "14e60ff7b69c0f2f8e8cd5cb4e44ed3929faa339",
          "md5": "cadd4533601668159d84c08efb8d2041"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-xml-2.0.1-sources.jar",
          "url": "echosvg-xml-2.0.1-sources.jar",
          "size": 23643,
          "sha512": "46e6adb0aed73df13ebb3dea3bb9fab86ad96782ded9c1de3792d0ea3bd6df0f19caa13afdec8fdd147644c1a1bea5cf9b4708ebafcfe017c20d816a22ed7ae4",
          "sha256": "1dfbac43d9ef18052454998fde81f36f640d2faf25e73a01c81c2c3388498c2b",
          "sha1": "db6400203b897c470e507e183d587222f090d434",
          "md5": "c0f2940904e5f34de8711017ab979a15"
        }
      ]
    }
  ]
}
