{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "xml-dtd",
    "version": "3.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "carte-util",
          "version": {
            "requires": "[3.4.0,)"
          }
        }
      ],
      "files": [
        {
          "name": "xml-dtd-3.5.1.jar",
          "url": "xml-dtd-3.5.1.jar",
          "size": 186814,
          "sha512": "814192831a553667470e4932fb80a5626cec390a02fe5060f0fe99e125c4f5b923ef88d59203adcc335aad94c0a4b9ebffdebcd8611bd197fc9d06ae0835eccf",
          "sha256": "a0941eee02e0bf511d3207ba620956538307b371fb42fe474f268568550d2711",
          "sha1": "4061c3bce298129fdd5aecb6142a0ed476f68689",
          "md5": "ca6e649c081c5e3191d3968e1dbf0f58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "carte-util",
          "version": {
            "requires": "[3.4.0,)"
          }
        }
      ],
      "files": [
        {
          "name": "xml-dtd-3.5.1.jar",
          "url": "xml-dtd-3.5.1.jar",
          "size": 186814,
          "sha512": "814192831a553667470e4932fb80a5626cec390a02fe5060f0fe99e125c4f5b923ef88d59203adcc335aad94c0a4b9ebffdebcd8611bd197fc9d06ae0835eccf",
          "sha256": "a0941eee02e0bf511d3207ba620956538307b371fb42fe474f268568550d2711",
          "sha1": "4061c3bce298129fdd5aecb6142a0ed476f68689",
          "md5": "ca6e649c081c5e3191d3968e1dbf0f58"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "xml-dtd-3.5.1-javadoc.jar",
          "url": "xml-dtd-3.5.1-javadoc.jar",
          "size": 127779,
          "sha512": "93f38ede471cd95072b86713bb582be8e00d43829a38b455a75bdf8815b9ec53cb294736c312494f130e31af94bd2676e219d93cd851c016b559fb40497d81d1",
          "sha256": "918c50c4ee152dc06bc26f09725f308169de7d6e62748a2d374d08e65391bcda",
          "sha1": "522877e21343d9c80c3c07def09d8ccd996b4bd4",
          "md5": "ae52a29004c9cfb2c05d54439d4efe69"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "xml-dtd-3.5.1-sources.jar",
          "url": "xml-dtd-3.5.1-sources.jar",
          "size": 179201,
          "sha512": "be5003cf97a6bb83da93a84cb79a9dc51fe4b41366ce4097643e13be17297a709256d4abcee20f26c36d3efb77b568ffcdd13ec46bdd0db12851cb5bad8bf13b",
          "sha256": "245567764f6f9a875d456da1ffd8a7c4e7c8ea46831c791db7c384a2db71ede8",
          "sha1": "0279d712dd23390306b064afdca367f4205ae764",
          "md5": "63079e07bc3c13ad09067cce10afaa5b"
        }
      ]
    },
    {
      "name": "dtdparseApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "xml-dtd-3.5.1.jar",
          "url": "xml-dtd-3.5.1.jar",
          "size": 186814,
          "sha512": "814192831a553667470e4932fb80a5626cec390a02fe5060f0fe99e125c4f5b923ef88d59203adcc335aad94c0a4b9ebffdebcd8611bd197fc9d06ae0835eccf",
          "sha256": "a0941eee02e0bf511d3207ba620956538307b371fb42fe474f268568550d2711",
          "sha1": "4061c3bce298129fdd5aecb6142a0ed476f68689",
          "md5": "ca6e649c081c5e3191d3968e1dbf0f58"
        }
      ],
      "capabilities": [
        {
          "group": "io.sf.carte",
          "name": "xml-dtd-dtdparse",
          "version": "3.5.1"
        }
      ]
    },
    {
      "name": "dtdparseRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "tokenproducer",
          "version": {
            "requires": "[1.1.1,)"
          }
        }
      ],
      "files": [
        {
          "name": "xml-dtd-3.5.1.jar",
          "url": "xml-dtd-3.5.1.jar",
          "size": 186814,
          "sha512": "814192831a553667470e4932fb80a5626cec390a02fe5060f0fe99e125c4f5b923ef88d59203adcc335aad94c0a4b9ebffdebcd8611bd197fc9d06ae0835eccf",
          "sha256": "a0941eee02e0bf511d3207ba620956538307b371fb42fe474f268568550d2711",
          "sha1": "4061c3bce298129fdd5aecb6142a0ed476f68689",
          "md5": "ca6e649c081c5e3191d3968e1dbf0f58"
        }
      ],
      "capabilities": [
        {
          "group": "io.sf.carte",
          "name": "xml-dtd-dtdparse",
          "version": "3.5.1"
        }
      ]
    },
    {
      "name": "dtdeclApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "xml-dtd-3.5.1.jar",
          "url": "xml-dtd-3.5.1.jar",
          "size": 186814,
          "sha512": "814192831a553667470e4932fb80a5626cec390a02fe5060f0fe99e125c4f5b923ef88d59203adcc335aad94c0a4b9ebffdebcd8611bd197fc9d06ae0835eccf",
          "sha256": "a0941eee02e0bf511d3207ba620956538307b371fb42fe474f268568550d2711",
          "sha1": "4061c3bce298129fdd5aecb6142a0ed476f68689",
          "md5": "ca6e649c081c5e3191d3968e1dbf0f58"
        }
      ],
      "capabilities": [
        {
          "group": "io.sf.carte",
          "name": "xml-dtd-dtdecl",
          "version": "3.5.1"
        }
      ]
    },
    {
      "name": "dtdeclRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.jclf",
          "module": "jclf-text",
          "version": {
            "requires": "[5.0.0,)"
          }
        }
      ],
      "files": [
        {
          "name": "xml-dtd-3.5.1.jar",
          "url": "xml-dtd-3.5.1.jar",
          "size": 186814,
          "sha512": "814192831a553667470e4932fb80a5626cec390a02fe5060f0fe99e125c4f5b923ef88d59203adcc335aad94c0a4b9ebffdebcd8611bd197fc9d06ae0835eccf",
          "sha256": "a0941eee02e0bf511d3207ba620956538307b371fb42fe474f268568550d2711",
          "sha1": "4061c3bce298129fdd5aecb6142a0ed476f68689",
          "md5": "ca6e649c081c5e3191d3968e1dbf0f58"
        }
      ],
      "capabilities": [
        {
          "group": "io.sf.carte",
          "name": "xml-dtd-dtdecl",
          "version": "3.5.1"
        }
      ]
    }
  ]
}
