{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "xml-dtd",
    "version": "3.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "carte-util",
          "version": {
            "requires": "3.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "xml-dtd-3.5.1.jar",
          "url": "xml-dtd-3.5.1.jar",
          "size": 187146,
          "sha512": "2ad948a117e7ea65fc8dc132a1afe28a252cbe1dc36ab8ede6462347e956be8c4d1714631c42f3b5693e1b729df76ac392850eeb5efc33f4eb3456f2b079e752",
          "sha256": "d08d0c58668dbbf59ffe9989092e2401e00482c71d92651c77d76aa4a5f2f6f9",
          "sha1": "9e5e746682e6b00b3459de4b1d45e04cee749dd9",
          "md5": "a62cf032eb5e877c2f6551585fc57318"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "carte-util",
          "version": {
            "requires": "3.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "xml-dtd-3.5.1.jar",
          "url": "xml-dtd-3.5.1.jar",
          "size": 187146,
          "sha512": "2ad948a117e7ea65fc8dc132a1afe28a252cbe1dc36ab8ede6462347e956be8c4d1714631c42f3b5693e1b729df76ac392850eeb5efc33f4eb3456f2b079e752",
          "sha256": "d08d0c58668dbbf59ffe9989092e2401e00482c71d92651c77d76aa4a5f2f6f9",
          "sha1": "9e5e746682e6b00b3459de4b1d45e04cee749dd9",
          "md5": "a62cf032eb5e877c2f6551585fc57318"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "xml-dtd-3.5.1-javadoc.jar",
          "url": "xml-dtd-3.5.1-javadoc.jar",
          "size": 127439,
          "sha512": "54e4e0875a058afc9126d85a0e279beea4dad41bd95e28a02716c3c54970a4c56d3f62b0f1734f8a9220fca33ed52433696a1ed32406860e7b585e27c243561d",
          "sha256": "cc2010918150d4151283a9d8870d897f3ae0a1ceae8aab5fbc8fc80c03f652dd",
          "sha1": "70d91d8af28d5ae943be386ed6fbc80a7b57f029",
          "md5": "55a16ce1fe2cfc592297a9713e4ab757"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "xml-dtd-3.5.1-sources.jar",
          "url": "xml-dtd-3.5.1-sources.jar",
          "size": 178861,
          "sha512": "c0a3c39e075b19caca8dd8c65d62a187b9c4ea0f0f9b542b1de7283f2a9ba5dd9fd0c2f116d27b9118b4991509ee23a71a73dd175443ea53b90891e624415c93",
          "sha256": "3d90212e2bc4ef4c58b5fb6c8712cc4dbc1ab3d402d4fe3842106969e40ce677",
          "sha1": "d61871c8b47e1d37b0d01e37ccf178e35ed3f30f",
          "md5": "6fbeefe7110b9d4b37b6a227805fa7e5"
        }
      ]
    },
    {
      "name": "dtdparseApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "xml-dtd-3.5.1.jar",
          "url": "xml-dtd-3.5.1.jar",
          "size": 187146,
          "sha512": "2ad948a117e7ea65fc8dc132a1afe28a252cbe1dc36ab8ede6462347e956be8c4d1714631c42f3b5693e1b729df76ac392850eeb5efc33f4eb3456f2b079e752",
          "sha256": "d08d0c58668dbbf59ffe9989092e2401e00482c71d92651c77d76aa4a5f2f6f9",
          "sha1": "9e5e746682e6b00b3459de4b1d45e04cee749dd9",
          "md5": "a62cf032eb5e877c2f6551585fc57318"
        }
      ],
      "capabilities": [
        {
          "group": "io.sf.carte",
          "name": "xml-dtd-dtdparse",
          "version": "3.5.1"
        }
      ]
    },
    {
      "name": "dtdparseRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "tokenproducer",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "xml-dtd-3.5.1.jar",
          "url": "xml-dtd-3.5.1.jar",
          "size": 187146,
          "sha512": "2ad948a117e7ea65fc8dc132a1afe28a252cbe1dc36ab8ede6462347e956be8c4d1714631c42f3b5693e1b729df76ac392850eeb5efc33f4eb3456f2b079e752",
          "sha256": "d08d0c58668dbbf59ffe9989092e2401e00482c71d92651c77d76aa4a5f2f6f9",
          "sha1": "9e5e746682e6b00b3459de4b1d45e04cee749dd9",
          "md5": "a62cf032eb5e877c2f6551585fc57318"
        }
      ],
      "capabilities": [
        {
          "group": "io.sf.carte",
          "name": "xml-dtd-dtdparse",
          "version": "3.5.1"
        }
      ]
    },
    {
      "name": "dtdeclApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "xml-dtd-3.5.1.jar",
          "url": "xml-dtd-3.5.1.jar",
          "size": 187146,
          "sha512": "2ad948a117e7ea65fc8dc132a1afe28a252cbe1dc36ab8ede6462347e956be8c4d1714631c42f3b5693e1b729df76ac392850eeb5efc33f4eb3456f2b079e752",
          "sha256": "d08d0c58668dbbf59ffe9989092e2401e00482c71d92651c77d76aa4a5f2f6f9",
          "sha1": "9e5e746682e6b00b3459de4b1d45e04cee749dd9",
          "md5": "a62cf032eb5e877c2f6551585fc57318"
        }
      ],
      "capabilities": [
        {
          "group": "io.sf.carte",
          "name": "xml-dtd-dtdecl",
          "version": "3.5.1"
        }
      ]
    },
    {
      "name": "dtdeclRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.jclf",
          "module": "jclf-text",
          "version": {
            "requires": "[5.0.0,)"
          }
        }
      ],
      "files": [
        {
          "name": "xml-dtd-3.5.1.jar",
          "url": "xml-dtd-3.5.1.jar",
          "size": 187146,
          "sha512": "2ad948a117e7ea65fc8dc132a1afe28a252cbe1dc36ab8ede6462347e956be8c4d1714631c42f3b5693e1b729df76ac392850eeb5efc33f4eb3456f2b079e752",
          "sha256": "d08d0c58668dbbf59ffe9989092e2401e00482c71d92651c77d76aa4a5f2f6f9",
          "sha1": "9e5e746682e6b00b3459de4b1d45e04cee749dd9",
          "md5": "a62cf032eb5e877c2f6551585fc57318"
        }
      ],
      "capabilities": [
        {
          "group": "io.sf.carte",
          "name": "xml-dtd-dtdecl",
          "version": "3.5.1"
        }
      ]
    }
  ]
}
