{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-extension",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-extension-1.1.jar",
          "url": "echosvg-extension-1.1.jar",
          "size": 72639,
          "sha512": "8be54eaed157ad0e621e593a2cd038914d9e9b9afe6c73f4fd807c9782c397d72fe5600aadeb0dd5eb2b09c5905a4f08c9d0b91da99dbc5b088073603ee425bd",
          "sha256": "bca594a2cc8fee518c1def8098fad458f1f7dd0f2333ffe4523c71088ec24a9f",
          "sha1": "86611fba040125aed581c99a7e1ea9a21a300fc5",
          "md5": "592f268e9022bf44b72a93ecb7b96373"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "xml-apis",
          "module": "xml-apis",
          "version": {
            "requires": "1.4.01"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-extension-1.1.jar",
          "url": "echosvg-extension-1.1.jar",
          "size": 72639,
          "sha512": "8be54eaed157ad0e621e593a2cd038914d9e9b9afe6c73f4fd807c9782c397d72fe5600aadeb0dd5eb2b09c5905a4f08c9d0b91da99dbc5b088073603ee425bd",
          "sha256": "bca594a2cc8fee518c1def8098fad458f1f7dd0f2333ffe4523c71088ec24a9f",
          "sha1": "86611fba040125aed581c99a7e1ea9a21a300fc5",
          "md5": "592f268e9022bf44b72a93ecb7b96373"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-extension-1.1-sources.jar",
          "url": "echosvg-extension-1.1-sources.jar",
          "size": 67504,
          "sha512": "472eaa4346d4f23847a0a18760fa21c6717cf794a1f095c1673588f304468fca4b5b03e793a390e3de2963d53b8f338922afd0b52f65fd2fde8209651bca847a",
          "sha256": "493bd37da21607da6d2dc7b76e50e820e17a04fd8600db575c190715e9bfc85e",
          "sha1": "2ac80db969d925d9c5892cfc6c64901b35393000",
          "md5": "095d4db196b5532c878f12ca7d189d51"
        }
      ]
    }
  ]
}
