{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-ext",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "echosvg-ext-1.2.1.jar",
          "url": "echosvg-ext-1.2.1.jar",
          "size": 8938,
          "sha512": "cc61f822a092c9532b9f98bba1f4c0f62a3b9453a454f24dbb1a5c1a9a6cda053ae8f855ee458517261b6f39f2d5aac2a36dd40b18916ade185415c85b83b129",
          "sha256": "7bdc4b270fd333a664705066f3402f3e252f63be05a49e950f1774a81e55f13b",
          "sha1": "91986ff12a31204a428e8e9f62b4615b1b84234d",
          "md5": "cb2f3d747b14434ea09569d5082fc6ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-ext-1.2.1.jar",
          "url": "echosvg-ext-1.2.1.jar",
          "size": 8938,
          "sha512": "cc61f822a092c9532b9f98bba1f4c0f62a3b9453a454f24dbb1a5c1a9a6cda053ae8f855ee458517261b6f39f2d5aac2a36dd40b18916ade185415c85b83b129",
          "sha256": "7bdc4b270fd333a664705066f3402f3e252f63be05a49e950f1774a81e55f13b",
          "sha1": "91986ff12a31204a428e8e9f62b4615b1b84234d",
          "md5": "cb2f3d747b14434ea09569d5082fc6ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-ext-1.2.1-sources.jar",
          "url": "echosvg-ext-1.2.1-sources.jar",
          "size": 14755,
          "sha512": "bb7565b37eb63741a74ae2a98464fde4ebbaab1ac375859c637b36b85f8c37518313e01eab3f90b5d9350e975a191a352edbcfff6dffcde8f95185dfd8b40c49",
          "sha256": "26675d229c0483b491f534d3f44c38bcffae07dfc728e438f10c0526319b0659",
          "sha1": "177e9086ca5862cccba998181776fa71b60b9c1b",
          "md5": "bb9d50015501ee4858c6f7db4509782a"
        }
      ]
    }
  ]
}
