{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-transcoder-api",
    "version": "2.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "echosvg-transcoder-api-2.2.1.jar",
          "url": "echosvg-transcoder-api-2.2.1.jar",
          "size": 23970,
          "sha512": "a02a8e7b7f0ab01d5543b40e5a6d4097b100a2426a988675e6b42f26f9710aa65cf535fe24a14a32a7394ee044502c57468ce4b00b7a97015a132b155aa57d7a",
          "sha256": "a9224bc76bd6bd1e07cee50d1f4586d589741ced6f34ef7862b9c8059cf42aa5",
          "sha1": "165cf153829e772db43db82ab7d805fc938acb04",
          "md5": "25f012f75ad85396d34c0ec1b1554395"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-transcoder-api-2.2.1.jar",
          "url": "echosvg-transcoder-api-2.2.1.jar",
          "size": 23970,
          "sha512": "a02a8e7b7f0ab01d5543b40e5a6d4097b100a2426a988675e6b42f26f9710aa65cf535fe24a14a32a7394ee044502c57468ce4b00b7a97015a132b155aa57d7a",
          "sha256": "a9224bc76bd6bd1e07cee50d1f4586d589741ced6f34ef7862b9c8059cf42aa5",
          "sha1": "165cf153829e772db43db82ab7d805fc938acb04",
          "md5": "25f012f75ad85396d34c0ec1b1554395"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-transcoder-api-2.2.1-sources.jar",
          "url": "echosvg-transcoder-api-2.2.1-sources.jar",
          "size": 32853,
          "sha512": "0d31195e5f86cf34c802c8efe888f45ced1c2828daa636adc8b627ea897daa730fb6a077443d1e3a64805e05d1f9fa5340ef9cebea3d5ee1ef233a093db0aaaa",
          "sha256": "b112fa9a797c8d9ec8effe00c259e7c6b999336b9fb1a2f94d71e5557f9f319a",
          "sha1": "962302fa2770158d9e1374f0f30e24c622a69e66",
          "md5": "bc980eb7de4cc107dc88afe523889411"
        }
      ]
    }
  ]
}
