{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-transcoder",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svggen",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-transcoder-1.2.jar",
          "url": "echosvg-transcoder-1.2.jar",
          "size": 158399,
          "sha512": "a27cc37288b8fc4022b0bcb8e6ad6943ed769db143b8d95555c67479d7146f9fbdb745d5c8e54e819ad3d5077f63627809030cdd31ae972113fc17a5dd71f407",
          "sha256": "3d89e4dfa788d7f6ff2d3db8a1f0e3b190534cc4898cb23f85a1bba85cf735a5",
          "sha1": "a83361b6424c1f2419bc01ac79455b4fab4bc7b1",
          "md5": "a40dbaa680d27c4934852cff853d1c7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-codec",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "css4j-awt",
          "version": {
            "requires": "4.0"
          }
        },
        {
          "group": "xml-apis",
          "module": "xml-apis",
          "version": {
            "requires": "1.4.01"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svggen",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-transcoder-1.2.jar",
          "url": "echosvg-transcoder-1.2.jar",
          "size": 158399,
          "sha512": "a27cc37288b8fc4022b0bcb8e6ad6943ed769db143b8d95555c67479d7146f9fbdb745d5c8e54e819ad3d5077f63627809030cdd31ae972113fc17a5dd71f407",
          "sha256": "3d89e4dfa788d7f6ff2d3db8a1f0e3b190534cc4898cb23f85a1bba85cf735a5",
          "sha1": "a83361b6424c1f2419bc01ac79455b4fab4bc7b1",
          "md5": "a40dbaa680d27c4934852cff853d1c7e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-transcoder-1.2-sources.jar",
          "url": "echosvg-transcoder-1.2-sources.jar",
          "size": 130132,
          "sha512": "b60a648031aec7ab31d121a1d7dbe1730f1b5cf442aefbe68d2c3675e322a07ef938cac63b56da1e07faec57b86b4bef48c20032124855b5d6405762a73f6db9",
          "sha256": "b0e3e3631e3b6f79dd51ba354b1fb1d8dd89d3eeec9a227924048f8b333b2052",
          "sha1": "a30eb164ef8e1a4fc10bec6b893e38cb65545313",
          "md5": "12b3f8ff9a837a3c62f74c43ab9003d2"
        }
      ]
    }
  ]
}
