{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-svgrasterizer",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svgrasterizer-0.1.jar",
          "url": "echosvg-svgrasterizer-0.1.jar",
          "size": 61248,
          "sha512": "28f4b6dad4ce2a9c7bf92c1b5cba3aaedf615a27c051346fb3d1884a3536dc7275f510f108ea2400e809fa011ed9471e22beeb720b1690b9f8557deeb43f207b",
          "sha256": "783815ad289788dc8e9a60544d4b488b94466f3fc0f43fb4d8b816a0e7c7e1a8",
          "sha1": "6a0ca7dd793cf709252d1ed3184685ccc8be2573",
          "md5": "5b28007098ca32f993c655de8144b4ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svgrasterizer-0.1.jar",
          "url": "echosvg-svgrasterizer-0.1.jar",
          "size": 61248,
          "sha512": "28f4b6dad4ce2a9c7bf92c1b5cba3aaedf615a27c051346fb3d1884a3536dc7275f510f108ea2400e809fa011ed9471e22beeb720b1690b9f8557deeb43f207b",
          "sha256": "783815ad289788dc8e9a60544d4b488b94466f3fc0f43fb4d8b816a0e7c7e1a8",
          "sha1": "6a0ca7dd793cf709252d1ed3184685ccc8be2573",
          "md5": "5b28007098ca32f993c655de8144b4ae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-svgrasterizer-0.1-sources.jar",
          "url": "echosvg-svgrasterizer-0.1-sources.jar",
          "size": 37041,
          "sha512": "27bacd2ee9ae8772ebe431672bc86c2781bf46f0bff542af36fd12f3d5a7d64b6a18cb77549d34ef24031a8aa1cfefa872f12a8c63f8ffac181aa2b2b04e7579",
          "sha256": "a941ad46bc5566ae97293d1d415346f704cf83489d38487f3280ed8f8b18856d",
          "sha1": "c7e350b88346593ecd74068fd75fb3b9dd8f1c9c",
          "md5": "6cd2dae7356f571531455737d8f1ab9a"
        }
      ]
    }
  ]
}
