{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-svgrasterizer",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svgrasterizer-0.1.jar",
          "url": "echosvg-svgrasterizer-0.1.jar",
          "size": 61248,
          "sha512": "9312ccac74272ff962d443fdf9d6264a57c4e2536b007e078f1962a9ca456f2569d24699477101cfedfdda5e5c0c5c65ac308dea9c5f3d50bff028ab2d840ef1",
          "sha256": "1641193a2f43f0b714856f679579e8faa87799a5c588531ac713fcca4b91f77a",
          "sha1": "6768c6de67720797df5d1fbc20aa7a5cedf260a0",
          "md5": "bb9b0ec0fdd554ea7a360d8610e4f467"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svgrasterizer-0.1.jar",
          "url": "echosvg-svgrasterizer-0.1.jar",
          "size": 61248,
          "sha512": "9312ccac74272ff962d443fdf9d6264a57c4e2536b007e078f1962a9ca456f2569d24699477101cfedfdda5e5c0c5c65ac308dea9c5f3d50bff028ab2d840ef1",
          "sha256": "1641193a2f43f0b714856f679579e8faa87799a5c588531ac713fcca4b91f77a",
          "sha1": "6768c6de67720797df5d1fbc20aa7a5cedf260a0",
          "md5": "bb9b0ec0fdd554ea7a360d8610e4f467"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-svgrasterizer-0.1-sources.jar",
          "url": "echosvg-svgrasterizer-0.1-sources.jar",
          "size": 37041,
          "sha512": "ec21a2f361d2ca95648489b4de188a71483db12785163a69c06a1edbaa0d235c5663a4ff918c3b17314e2433c3f3893f1f1cf64c55f785822c3dcfc28a8e9aa4",
          "sha256": "cc43f39d624a63694a8e10937843a882db185bc8e8e51113f919b63cb9477c02",
          "sha1": "7d0507961824244fa377edca72b8b7139a778a3e",
          "md5": "218ba6f2b9c82b32d3f8be8ecbae4f71"
        }
      ]
    }
  ]
}
