{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-slideshow",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gvt",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-slideshow-1.0.jar",
          "url": "echosvg-slideshow-1.0.jar",
          "size": 16184,
          "sha512": "74f08d66e17d90f17df02abd92a90170bac0f175d24207857f21fb74e947ec5e7cfa5416e423c3aad7bc22e61223bec2ca687990c43b3334d062ccb0b2be98bb",
          "sha256": "ace6c16285b40f42aafec45e640ecda9b5794d870f5aa00ad24a874c6648e81b",
          "sha1": "1721491b8665230e4bb102313f9e96e337a251f9",
          "md5": "f12132887105409012c629b5d3767358"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gvt",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-slideshow-1.0.jar",
          "url": "echosvg-slideshow-1.0.jar",
          "size": 16184,
          "sha512": "74f08d66e17d90f17df02abd92a90170bac0f175d24207857f21fb74e947ec5e7cfa5416e423c3aad7bc22e61223bec2ca687990c43b3334d062ccb0b2be98bb",
          "sha256": "ace6c16285b40f42aafec45e640ecda9b5794d870f5aa00ad24a874c6648e81b",
          "sha1": "1721491b8665230e4bb102313f9e96e337a251f9",
          "md5": "f12132887105409012c629b5d3767358"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-slideshow-1.0-sources.jar",
          "url": "echosvg-slideshow-1.0-sources.jar",
          "size": 9967,
          "sha512": "96d2a842436b3dfaa88287ddd827d483e94ac45d1d5d25e9a0b8fe2c224aba1881164a9f71001f22c7397cca2965d7e1a1f0334db4ca75a072bdbd50656f5e1e",
          "sha256": "ed0c52130a205e566b4f17193bf6e072c64bf289e2c49fe0a003448f920a0675",
          "sha1": "ac3be5ee51a609da87839da00462a5b82f5a5d05",
          "md5": "be0363ce8de851b1b4a520e744e7856f"
        }
      ]
    }
  ]
}
