{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-constants",
    "version": "2.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "echosvg-constants-2.2.1.jar",
          "url": "echosvg-constants-2.2.1.jar",
          "size": 7196,
          "sha512": "9f84708d3859be61fef82bc3fdd7706404fdd3d657eff5ae01958346b07e7b1f11c90a4522101348b1c06c804db4762f2fda66f9be616dadb953abd1d72e7b94",
          "sha256": "e7c95b8b7aaf6f6b8feb03063fe163b70df8a6d530573ac6741cc00dd13ce7a5",
          "sha1": "e17e5f44c74c03b5f35332ecacf89a3e8999a2dd",
          "md5": "63cc4f4c7f7369dd28ed513457ed2c50"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-constants-2.2.1.jar",
          "url": "echosvg-constants-2.2.1.jar",
          "size": 7196,
          "sha512": "9f84708d3859be61fef82bc3fdd7706404fdd3d657eff5ae01958346b07e7b1f11c90a4522101348b1c06c804db4762f2fda66f9be616dadb953abd1d72e7b94",
          "sha256": "e7c95b8b7aaf6f6b8feb03063fe163b70df8a6d530573ac6741cc00dd13ce7a5",
          "sha1": "e17e5f44c74c03b5f35332ecacf89a3e8999a2dd",
          "md5": "63cc4f4c7f7369dd28ed513457ed2c50"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-constants-2.2.1-sources.jar",
          "url": "echosvg-constants-2.2.1-sources.jar",
          "size": 7611,
          "sha512": "bacd67be3f9af039e265317c9437faeae0efe9653c6c127fa8d4e5b20e53dc4c9d8d6537dcfcdc666fc3b68c32c0b44ec25c83752122c578ab865b3adeaa3b93",
          "sha256": "0e6bc65fe23606f45e9a6b4c4f9ee282ea547193ef10e32f811be3e12391d361",
          "sha1": "99439d4998f43516f0099d3f67574240979af543",
          "md5": "cebaa770a2b8562bb06d73a77734aabd"
        }
      ]
    }
  ]
}
