{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-xml",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-xml-1.1.1.jar",
          "url": "echosvg-xml-1.1.1.jar",
          "size": 32357,
          "sha512": "79cfc1a5a654c8f36313f7929f2c18dc80c08ed03cf04fd37fc17a22fe93dd632e7c561ff97503e494d0b07af153ee62f7adcebb83f89a44a1715c82191c5a3b",
          "sha256": "6c087ed38710a17eeab0299dcdcbd4cdfd01178bd0bb05a1227946364c3d354b",
          "sha1": "90fdb1a923155a912886f356ca2ecb7ee7722613",
          "md5": "25068e475ffee2f6a421c47f1a04a01b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-xml-1.1.1.jar",
          "url": "echosvg-xml-1.1.1.jar",
          "size": 32357,
          "sha512": "79cfc1a5a654c8f36313f7929f2c18dc80c08ed03cf04fd37fc17a22fe93dd632e7c561ff97503e494d0b07af153ee62f7adcebb83f89a44a1715c82191c5a3b",
          "sha256": "6c087ed38710a17eeab0299dcdcbd4cdfd01178bd0bb05a1227946364c3d354b",
          "sha1": "90fdb1a923155a912886f356ca2ecb7ee7722613",
          "md5": "25068e475ffee2f6a421c47f1a04a01b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-xml-1.1.1-sources.jar",
          "url": "echosvg-xml-1.1.1-sources.jar",
          "size": 23446,
          "sha512": "f70b08f27c81d15c99197ded89142e712195622269fc5a368df580679fd4eee6b0b3050b5b569a3fb2af4ae732204e25e4d808069a90ee208fba7c0fe167a53a",
          "sha256": "31b4592d59a4f4729a2dd146e602d913a7d582d13703c6f4b3776342a2fd02ee",
          "sha1": "4f22609c36dd952313db9c07c0eb2774ba2ed8f8",
          "md5": "833c3cbba68925fb1918ba6ed597389a"
        }
      ]
    }
  ]
}
