{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-anim",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-anim-1.0.1.jar",
          "url": "echosvg-anim-1.0.1.jar",
          "size": 502565,
          "sha512": "e2592d780571fc0174e667fe6763e20faf95871f0f0523018054acfcaf385c019306fdfabcf0ecf285ece2846321f77a7b075c372d2a43526c0b35439d13a00f",
          "sha256": "92c6f943511d4bc3a65307628a3439ac1dbf20aa18e5d32964ead89885c645c3",
          "sha1": "44a5469f464291da9e7ce421e0c1682e5ddd242c",
          "md5": "0286968483fd209b8c1ccaa68a316da0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "xml-apis",
          "module": "xml-apis",
          "version": {
            "requires": "1.4.01"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-anim-1.0.1.jar",
          "url": "echosvg-anim-1.0.1.jar",
          "size": 502565,
          "sha512": "e2592d780571fc0174e667fe6763e20faf95871f0f0523018054acfcaf385c019306fdfabcf0ecf285ece2846321f77a7b075c372d2a43526c0b35439d13a00f",
          "sha256": "92c6f943511d4bc3a65307628a3439ac1dbf20aa18e5d32964ead89885c645c3",
          "sha1": "44a5469f464291da9e7ce421e0c1682e5ddd242c",
          "md5": "0286968483fd209b8c1ccaa68a316da0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-anim-1.0.1-sources.jar",
          "url": "echosvg-anim-1.0.1-sources.jar",
          "size": 378146,
          "sha512": "fc07f88aee9fb402af350507332624089d6a216a63f1be9c63c4c98f2218955460d5931532c2a8ff676c35e17cd6415fba11e6110c5ab6f597740abfea7933f4",
          "sha256": "82f3badab38a6f97b9ee723d068286b804c50388873d26aaaf1de52444dc782a",
          "sha1": "6452220ec3bd05477ebc2610a90e6e0cb0136c14",
          "md5": "b483cbe4b4254bd53d5931c9d210b7c6"
        }
      ]
    }
  ]
}
