{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-css",
    "version": "2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "io.sf.w3",
          "module": "domview-api",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.sf.w3",
          "module": "cssom-api",
          "version": {
            "requires": "0.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "css4j",
          "version": {
            "requires": "6.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-css-2.2.jar",
          "url": "echosvg-css-2.2.jar",
          "size": 372913,
          "sha512": "20fbd7eae8b86cf041aa3f740cded2ef85198d3853d25de74ee3ef3ea6cf2be4b52aeb027803ea1fc99bb368c5fefdf92a46da6ee721717631e7cf073a66ddb5",
          "sha256": "5c385253145469d45b0b7e3920974ae706f4eb8276e40fe85309b855bf2e01ec",
          "sha1": "02a0ffb7e8de47362bdb196036b5cc8011cb98c1",
          "md5": "fc3a6109f0e4d95fe300fbdda1737893"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "io.sf.w3",
          "module": "domview-api",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.sf.w3",
          "module": "cssom-api",
          "version": {
            "requires": "0.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "css4j",
          "version": {
            "requires": "6.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-css-2.2.jar",
          "url": "echosvg-css-2.2.jar",
          "size": 372913,
          "sha512": "20fbd7eae8b86cf041aa3f740cded2ef85198d3853d25de74ee3ef3ea6cf2be4b52aeb027803ea1fc99bb368c5fefdf92a46da6ee721717631e7cf073a66ddb5",
          "sha256": "5c385253145469d45b0b7e3920974ae706f4eb8276e40fe85309b855bf2e01ec",
          "sha1": "02a0ffb7e8de47362bdb196036b5cc8011cb98c1",
          "md5": "fc3a6109f0e4d95fe300fbdda1737893"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-css-2.2-sources.jar",
          "url": "echosvg-css-2.2-sources.jar",
          "size": 266475,
          "sha512": "b6f657568ba32069d72449765fb2e628f7a13c787268b6d0f71ecf363d5443a9b6da025cd402f97849888e10245cdfb0a0139c18c940c056da69b4c69a9dacdd",
          "sha256": "d32be5f832e3304dd417a29fcea96c4e0614840f0ce376b2b51fa10d03570ac8",
          "sha1": "432bce5f114658bde79ebd4a8058e99d8908877e",
          "md5": "c0af3901df108f5ed6312c2ed212d75e"
        }
      ]
    }
  ]
}
