{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-css",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "css4j",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-css-1.1.1.jar",
          "url": "echosvg-css-1.1.1.jar",
          "size": 292380,
          "sha512": "1944519099b8d085f54eba93b7484bba5ed5efe4bd7791f9ae898b5fd3b51032af446cc6c9cbcc574331673f0aa24f8c19ea27281b99615c9ddf3fe78b531d29",
          "sha256": "1911502277d23ba175c0244bc3384225b6bae16809d7af568ebc21f9764a8e76",
          "sha1": "03d9b5ee9417f2608b5ec056c9bef801d6ac0ade",
          "md5": "679556e2e0270f690e575be58381a221"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "css4j",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-css-1.1.1.jar",
          "url": "echosvg-css-1.1.1.jar",
          "size": 292380,
          "sha512": "1944519099b8d085f54eba93b7484bba5ed5efe4bd7791f9ae898b5fd3b51032af446cc6c9cbcc574331673f0aa24f8c19ea27281b99615c9ddf3fe78b531d29",
          "sha256": "1911502277d23ba175c0244bc3384225b6bae16809d7af568ebc21f9764a8e76",
          "sha1": "03d9b5ee9417f2608b5ec056c9bef801d6ac0ade",
          "md5": "679556e2e0270f690e575be58381a221"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-css-1.1.1-sources.jar",
          "url": "echosvg-css-1.1.1-sources.jar",
          "size": 208748,
          "sha512": "8710947a67cffa6c972b8afe2d3907d432d6bb7d43467d376c461f0d72043dcfef08d1af441bce0c5ef08e8b594ceec33f07bd219c4c813cde8a6016dcf02013",
          "sha256": "7a8192c0ed6abfe5b34f9310681c44ead11e2e2d183b90b4ff37579f473d9a37",
          "sha1": "2da7a32484814d005c013312c19a7039b6f262da",
          "md5": "d1a756397e68dff06d674541b00e2b96"
        }
      ]
    }
  ]
}
