{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-script",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.7.15"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-script-1.1.1.jar",
          "url": "echosvg-script-1.1.1.jar",
          "size": 27016,
          "sha512": "2f5067d40e3de4d7be1c7658f1f18571c498a43d5e31bf3881eb19efef1b176271026e6706aefb378a295621b0df5fc7a6cbb8872b0562ad8be72f41b8207f0d",
          "sha256": "52e5e7920ddcdb6e0083e664bef06eb2aec42ed015f26fa210cbcc3b5f914d0b",
          "sha1": "d138f1a4fada933aa23beec4996ac4aa624bfb03",
          "md5": "2c87288f2acaa6bbde66086c20716d36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "xml-apis",
          "module": "xml-apis",
          "version": {
            "requires": "1.4.01"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.7.15"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-script-1.1.1.jar",
          "url": "echosvg-script-1.1.1.jar",
          "size": 27016,
          "sha512": "2f5067d40e3de4d7be1c7658f1f18571c498a43d5e31bf3881eb19efef1b176271026e6706aefb378a295621b0df5fc7a6cbb8872b0562ad8be72f41b8207f0d",
          "sha256": "52e5e7920ddcdb6e0083e664bef06eb2aec42ed015f26fa210cbcc3b5f914d0b",
          "sha1": "d138f1a4fada933aa23beec4996ac4aa624bfb03",
          "md5": "2c87288f2acaa6bbde66086c20716d36"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-script-1.1.1-sources.jar",
          "url": "echosvg-script-1.1.1-sources.jar",
          "size": 29616,
          "sha512": "071b815d7c053d21506670a07969b81319babba21905b02eb8906e9443ce943a1a89dfe27d2ffa695d745ac0e0fc3554e7ff96183180b9b5ed1be41f603dcb7f",
          "sha256": "1d881746f80d62623bdd21bf161cb63f55b05b756898d6ccb4974dc234584f08",
          "sha1": "66003b33042e1c9ca03b46de4052ce5db2df139b",
          "md5": "33695d38278c0a9d623ca1be68f2b68d"
        }
      ]
    }
  ]
}
