{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-ext-swing",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "echosvg-ext-swing-2.0.jar",
          "url": "echosvg-ext-swing-2.0.jar",
          "size": 26266,
          "sha512": "3ae02e90b6e01230449bf138ed2227691d08dc6788c9e24b02b12ac85af53ec2a89460c7d6a17ea627f67b834340e4b6c0ec51b761106f13f971384a76e57d79",
          "sha256": "47056e8d4136fbc8d202e59929bf25f6cccdccd337c2b644406fa1549ea22629",
          "sha1": "e6560414f520c9bec03516d9edac539c1ffca5b3",
          "md5": "79071ddca6d3e2bb39c417f7507364dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-ext-swing-2.0.jar",
          "url": "echosvg-ext-swing-2.0.jar",
          "size": 26266,
          "sha512": "3ae02e90b6e01230449bf138ed2227691d08dc6788c9e24b02b12ac85af53ec2a89460c7d6a17ea627f67b834340e4b6c0ec51b761106f13f971384a76e57d79",
          "sha256": "47056e8d4136fbc8d202e59929bf25f6cccdccd337c2b644406fa1549ea22629",
          "sha1": "e6560414f520c9bec03516d9edac539c1ffca5b3",
          "md5": "79071ddca6d3e2bb39c417f7507364dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-ext-swing-2.0-sources.jar",
          "url": "echosvg-ext-swing-2.0-sources.jar",
          "size": 18304,
          "sha512": "9f0b5235e9d880fd98e62a40e3fb00057da86c00248870b584b7c4431e25fc9ad316819af86cea8c441c6635457f01231b03cd8c876df1aaf2fe0995f3481bad",
          "sha256": "10192b9b029c34d30ebfbf1801d6593c54b11cf83a22ee1dae2ccaaa46a444d8",
          "sha1": "7af2b447935f703b942126fee56edd04688f9bc0",
          "md5": "25682faf9358b7d949af10c04dde422b"
        }
      ]
    }
  ]
}
