{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-i18n",
    "version": "2.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "echosvg-i18n-2.2.1.jar",
          "url": "echosvg-i18n-2.2.1.jar",
          "size": 10531,
          "sha512": "77bc8a6c5a3ea9eb65ed5db5ce4515e3745ad8ac9643572e7c2518aef3e0ba676df7bdf8a0d93aac764146fd1f479b54c7c6f9580f681004244f12ae703aff4d",
          "sha256": "6b1458ac5e48c51c3039d981c90148155ab3df2bad1c844b5f2f295426efae75",
          "sha1": "7eeea847d14fb49a797ae3e089592831e04386d6",
          "md5": "c8a1c7db721a2fb4f4a6adbccb5b7960"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-i18n-2.2.1.jar",
          "url": "echosvg-i18n-2.2.1.jar",
          "size": 10531,
          "sha512": "77bc8a6c5a3ea9eb65ed5db5ce4515e3745ad8ac9643572e7c2518aef3e0ba676df7bdf8a0d93aac764146fd1f479b54c7c6f9580f681004244f12ae703aff4d",
          "sha256": "6b1458ac5e48c51c3039d981c90148155ab3df2bad1c844b5f2f295426efae75",
          "sha1": "7eeea847d14fb49a797ae3e089592831e04386d6",
          "md5": "c8a1c7db721a2fb4f4a6adbccb5b7960"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-i18n-2.2.1-sources.jar",
          "url": "echosvg-i18n-2.2.1-sources.jar",
          "size": 12742,
          "sha512": "18cfd814bbc5c3d156176b9e59bef304439862574d004eaedc3c7f5a3b4954bcc3f6800941721a14b3cb66180ccda0e9823b24810a2ef3e538a25fa658b1e3f8",
          "sha256": "d93930abc78a1e8ea6f36721a99fe5dfc268116be47e4772138c2c73b21941b5",
          "sha1": "55f7489d7d88de533f16c116856683c8a564c34b",
          "md5": "96127b33a7a9fc9813d67d9f6fc88c06"
        }
      ]
    }
  ]
}
