{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-css",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "io.sf.w3",
          "module": "domview-api",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "css4j",
          "version": {
            "requires": "5.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-css-2.0.1.jar",
          "url": "echosvg-css-2.0.1.jar",
          "size": 358888,
          "sha512": "a1ec3b20db5153a9933d36af3fb0001a01825ed713f84e476dc05e26a995443cdf648e2a04ef6680cb3f861b56b64cf0cb89a1b2ecc29a5dea297f368cadebe1",
          "sha256": "e548fa044217c4efd95763b650264ade6375edca9b032480758b7f181745fd35",
          "sha1": "9b59e66e49f8b693d10eba5660506ecec7d8a20e",
          "md5": "23a552442dc34838c5f2f2da0626efd9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "io.sf.w3",
          "module": "domview-api",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "css4j",
          "version": {
            "requires": "5.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-css-2.0.1.jar",
          "url": "echosvg-css-2.0.1.jar",
          "size": 358888,
          "sha512": "a1ec3b20db5153a9933d36af3fb0001a01825ed713f84e476dc05e26a995443cdf648e2a04ef6680cb3f861b56b64cf0cb89a1b2ecc29a5dea297f368cadebe1",
          "sha256": "e548fa044217c4efd95763b650264ade6375edca9b032480758b7f181745fd35",
          "sha1": "9b59e66e49f8b693d10eba5660506ecec7d8a20e",
          "md5": "23a552442dc34838c5f2f2da0626efd9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-css-2.0.1-sources.jar",
          "url": "echosvg-css-2.0.1-sources.jar",
          "size": 256498,
          "sha512": "15d4f44ffb8228b8b8cf7a91bbf67c9f7cc0731c7b5754dd74afc3cf9e394c3b83dd901dcdd757acfadbf7d5f33598cc81ca31130d667a8ef17a669db096c995",
          "sha256": "370bbb672d3e4b6b8cfa614e42657a5f1412dcae2093b812435b3973272845fd",
          "sha1": "c68ae1c86c8c29f066b0ed3089ee631ea600a6c3",
          "md5": "75f46645ea7099bfe199fa0d42d99388"
        }
      ]
    }
  ]
}
