{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-test-util",
    "version": "2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "echosvg-test-util-2.2.jar",
          "url": "echosvg-test-util-2.2.jar",
          "size": 30700,
          "sha512": "e83699decfae09a8263a454c441951791f1534e614945d5d40efa13f93b1c5e0d0fcea3a03c4912a6fbc0afe5f1ae025657e6d0450aa4ef04a992a500b5c3ebf",
          "sha256": "538fd380f89ae8758f86d6d0d0734639bd7ca894c0dad12980cd7078ac14a060",
          "sha1": "4f55ec03960f2d0a6e7cd4d629a4bf50d65ee683",
          "md5": "a87c3d563e81decc5cda6f009072e2f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "io.sf.jclf",
          "module": "jclf-text",
          "version": {
            "requires": "5.0.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "xml-dtd",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "carte-util",
          "version": {
            "requires": "[3.6.0,)"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-test-util-2.2.jar",
          "url": "echosvg-test-util-2.2.jar",
          "size": 30700,
          "sha512": "e83699decfae09a8263a454c441951791f1534e614945d5d40efa13f93b1c5e0d0fcea3a03c4912a6fbc0afe5f1ae025657e6d0450aa4ef04a992a500b5c3ebf",
          "sha256": "538fd380f89ae8758f86d6d0d0734639bd7ca894c0dad12980cd7078ac14a060",
          "sha1": "4f55ec03960f2d0a6e7cd4d629a4bf50d65ee683",
          "md5": "a87c3d563e81decc5cda6f009072e2f0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-test-util-2.2-sources.jar",
          "url": "echosvg-test-util-2.2-sources.jar",
          "size": 24960,
          "sha512": "20a8bc5d2f7d346257941f2729400099abd040618fb61327b3a47c7bbf4c2a72b1de1d3295e8b642be32b48a340b4a039a89d9ee1e3a400bddb17abb70b96d5a",
          "sha256": "4bab0dcc29690164522adb247fe9582c623f08d7708d5087ca241478c7a9fb01",
          "sha1": "9baa3fdbb6ae1a4b3c93a170354a85c19b02aaa1",
          "md5": "4cc55ada30b9ccd0ddde7029e0ea9183"
        }
      ]
    }
  ]
}
