{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-parser",
    "version": "2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "css4j",
          "version": {
            "requires": "6.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-parser-2.5.jar",
          "url": "echosvg-parser-2.5.jar",
          "size": 87193,
          "sha512": "d2b78e854a9659c4aa4c85fe8846b4abbd2687a8161e5f6be29df55ce78fff71872e6af482a463640c656c570e14ba62d8e3bd1b5d22cb2e6d3dcfdf5e22e0e7",
          "sha256": "595d1493ab580e0db577d9f612a69f3500b32bc0704ef7de0fb63f6b6813e571",
          "sha1": "0dcd116e12dcfa93fd938d3a7fddd2f0e2d08753",
          "md5": "d05d24477d0b60eb60e009b031e6eef2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "css4j",
          "version": {
            "requires": "6.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-parser-2.5.jar",
          "url": "echosvg-parser-2.5.jar",
          "size": 87193,
          "sha512": "d2b78e854a9659c4aa4c85fe8846b4abbd2687a8161e5f6be29df55ce78fff71872e6af482a463640c656c570e14ba62d8e3bd1b5d22cb2e6d3dcfdf5e22e0e7",
          "sha256": "595d1493ab580e0db577d9f612a69f3500b32bc0704ef7de0fb63f6b6813e571",
          "sha1": "0dcd116e12dcfa93fd938d3a7fddd2f0e2d08753",
          "md5": "d05d24477d0b60eb60e009b031e6eef2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-parser-2.5-sources.jar",
          "url": "echosvg-parser-2.5-sources.jar",
          "size": 87063,
          "sha512": "f62cd5e04b5d10d03a1851838e1cd93726aa78cb1974ccfd8528496cd6c9eadf62c4123ed6056f011009dc5edcf50f44bfd680e7ef84c850bbb27350ae0253a8",
          "sha256": "c9deb326619bf710716db6d576c5edb7cb419b5a3377ae5e5db12dcc5ba4b7f8",
          "sha1": "bd4fb1766157da6de6a68a815f4260b1fc061254",
          "md5": "0f8fb5bccdc990f7dfa53308a18b6865"
        }
      ]
    }
  ]
}
