{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-parser",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-parser-1.2.1.jar",
          "url": "echosvg-parser-1.2.1.jar",
          "size": 77056,
          "sha512": "31350da110eceb112280ed9410b7b1407220680c3fb4cf804c4da794d2904655f20e0791cf9b07c46c3c180c79794197b570224e8bb3efc6c95edf548ca7c3a5",
          "sha256": "bd3fdbadd2055191b71856e87cdebaa179069ca14c6dee1cd7ab9c1b2374f6c7",
          "sha1": "3babc34ad4fc6b87c7cbd037aff3ae5eab23db98",
          "md5": "e69b1c208b5a6f4a09d3c2139aac53f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-parser-1.2.1.jar",
          "url": "echosvg-parser-1.2.1.jar",
          "size": 77056,
          "sha512": "31350da110eceb112280ed9410b7b1407220680c3fb4cf804c4da794d2904655f20e0791cf9b07c46c3c180c79794197b570224e8bb3efc6c95edf548ca7c3a5",
          "sha256": "bd3fdbadd2055191b71856e87cdebaa179069ca14c6dee1cd7ab9c1b2374f6c7",
          "sha1": "3babc34ad4fc6b87c7cbd037aff3ae5eab23db98",
          "md5": "e69b1c208b5a6f4a09d3c2139aac53f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-parser-1.2.1-sources.jar",
          "url": "echosvg-parser-1.2.1-sources.jar",
          "size": 83445,
          "sha512": "ff689e4463c4a46f1ff28315b373f41fac594b3611f009decfda192b420fd211fb68ae464db7b47996395eeff2d6a9abbe0331bece3e3c5c14345e39da3f4e49",
          "sha256": "2720ecded0b9240acff2b17814171b7622a84ac886acf22a060886d838c0c570",
          "sha1": "a7c7b340006c7a9b9791c617631fb83a088d5377",
          "md5": "25ba5ad8c04d5e65fb28fa5502b8903c"
        }
      ]
    }
  ]
}
