{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-swing",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-css",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gvt",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-swing-0.1.jar",
          "url": "echosvg-swing-0.1.jar",
          "size": 196609,
          "sha512": "5cf7a6ec363928e3dbae36f65ed9ae4ae16aa2e2d8338aac9a5538c3578318b7e4fa88085e98fba4f5bd324cb84cb72cfc19c9811b032bcbee7f6602f649b886",
          "sha256": "3c43b96adee8eefa024ab033d2bc5b7bdadf043ae94e7d1aea18d0fea715d8bf",
          "sha1": "2e2ab8634f71824973eeb50f92dcd50cb5f8ee0d",
          "md5": "436c86dde807ac6180e2f88d32305844"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-css",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gvt",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-swing-0.1.jar",
          "url": "echosvg-swing-0.1.jar",
          "size": 196609,
          "sha512": "5cf7a6ec363928e3dbae36f65ed9ae4ae16aa2e2d8338aac9a5538c3578318b7e4fa88085e98fba4f5bd324cb84cb72cfc19c9811b032bcbee7f6602f649b886",
          "sha256": "3c43b96adee8eefa024ab033d2bc5b7bdadf043ae94e7d1aea18d0fea715d8bf",
          "sha1": "2e2ab8634f71824973eeb50f92dcd50cb5f8ee0d",
          "md5": "436c86dde807ac6180e2f88d32305844"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-swing-0.1-sources.jar",
          "url": "echosvg-swing-0.1-sources.jar",
          "size": 98974,
          "sha512": "c3ff509184de4d6c3027e8b5884241213e5f46554a8efb0d9e223298fe7aac310279c0e6ad8ca7d6fb7f9eb64165b2884373a6886a97d79af92deaa43dd32859",
          "sha256": "19dbd796d2beececf1fc5b665742591ac9385b16d0de5673a6c7caacd216d89a",
          "sha1": "4f25e8054d9e52379b63cd6e5108b9a8e033906c",
          "md5": "2504a3107d83e5387f847b45c40108ac"
        }
      ]
    }
  ]
}
