{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-constants",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "echosvg-constants-1.2.2.jar",
          "url": "echosvg-constants-1.2.2.jar",
          "size": 7041,
          "sha512": "e292b5a850388ab16734229efb3063bd57b07867167ca39513b48d380d689c6d25198e704af4cee05614f5b5572875fd38941305b658a59af874bcba74d2c57d",
          "sha256": "141499972d051cb8532258ca904ab67f71ef21064f5dbdd776b3dfd111f10b4c",
          "sha1": "c25709435ec6ad3268ca10488f23fdb3d462c6f4",
          "md5": "f945f9481e7713c5cc8628ed9db5ffab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-constants-1.2.2.jar",
          "url": "echosvg-constants-1.2.2.jar",
          "size": 7041,
          "sha512": "e292b5a850388ab16734229efb3063bd57b07867167ca39513b48d380d689c6d25198e704af4cee05614f5b5572875fd38941305b658a59af874bcba74d2c57d",
          "sha256": "141499972d051cb8532258ca904ab67f71ef21064f5dbdd776b3dfd111f10b4c",
          "sha1": "c25709435ec6ad3268ca10488f23fdb3d462c6f4",
          "md5": "f945f9481e7713c5cc8628ed9db5ffab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-constants-1.2.2-sources.jar",
          "url": "echosvg-constants-1.2.2-sources.jar",
          "size": 7466,
          "sha512": "7ad8398eb03f1b45783646eae9e915d6f1ebbca3924909f5393c91bac0e35ae73ffe187a48e311f548525ab0fbeaf5e61cfab2817c040fdacaea3151d2375417",
          "sha256": "22bc36a205dc2344f3e4cd3591a62c5e2e032f8fdd6cf3584dc28dcd659ee86f",
          "sha1": "384f8b8efc9a085e137c82d88b26a0c696e4b082",
          "md5": "9094d0de940a320b2174e02486e5105e"
        }
      ]
    }
  ]
}
