{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-svg-dom",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svg-dom-1.2.jar",
          "url": "echosvg-svg-dom-1.2.jar",
          "size": 74123,
          "sha512": "611e697ea5fd31f76005f52c56cdb262472800af3f7bda5739a43dc2ac6adf7a6c1851affffb573a547d235ea0cdc46bbb7ae0e373a22dde4dd646b9888ad6ad",
          "sha256": "a385dcfdf33f9057ce3ea68c63a3fefa05eb4c7e0c06de6823549c9004778d50",
          "sha1": "5f9162f49675b173fdb9d6e22ec6156915e09fdd",
          "md5": "9c241350ddcdc7ea3ebf1aa53a51c279"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "xml-apis",
          "module": "xml-apis",
          "version": {
            "requires": "1.4.01"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svg-dom-1.2.jar",
          "url": "echosvg-svg-dom-1.2.jar",
          "size": 74123,
          "sha512": "611e697ea5fd31f76005f52c56cdb262472800af3f7bda5739a43dc2ac6adf7a6c1851affffb573a547d235ea0cdc46bbb7ae0e373a22dde4dd646b9888ad6ad",
          "sha256": "a385dcfdf33f9057ce3ea68c63a3fefa05eb4c7e0c06de6823549c9004778d50",
          "sha1": "5f9162f49675b173fdb9d6e22ec6156915e09fdd",
          "md5": "9c241350ddcdc7ea3ebf1aa53a51c279"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-svg-dom-1.2-sources.jar",
          "url": "echosvg-svg-dom-1.2-sources.jar",
          "size": 69466,
          "sha512": "02c89ecac60aa96c333e58c455817246d9b8fdab3953764615395a42e5320441a8db46186d8695ab777d79442f9f64f9eeae24db7deb96532bd68a18596b6f55",
          "sha256": "bed26467cc4c202273253b3dd643b2e48cedda722fe6ed4ac9734b4a1ffb600c",
          "sha1": "06e044596c87b78743bf2c8cd88b5850e4ce18d0",
          "md5": "4751472c2a5674d89ad77b1bba3e33d9"
        }
      ]
    }
  ]
}
