{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-bridge",
    "version": "0.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gvt",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.8"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-bridge-0.3.2.jar",
          "url": "echosvg-bridge-0.3.2.jar",
          "size": 721456,
          "sha512": "4142db3a906333291d60d0b80286f96587b481ab00b3c63084e01d7518b83397a61dd8da715eff0155616968642fedd132ad94dcbed2c2abd213233eb64fa141",
          "sha256": "8e19f7c200d9bbb4a79f02227e8d69fcd2b17bde09ee208dff67f92ab0543434",
          "sha1": "39fd29903153aaba0b216b8392a0913a0482fc74",
          "md5": "87cc9b4172c94f137b8fb733e3a18966"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "xml-apis",
          "module": "xml-apis",
          "version": {
            "requires": "1.4.01"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gvt",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.8"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-bridge-0.3.2.jar",
          "url": "echosvg-bridge-0.3.2.jar",
          "size": 721456,
          "sha512": "4142db3a906333291d60d0b80286f96587b481ab00b3c63084e01d7518b83397a61dd8da715eff0155616968642fedd132ad94dcbed2c2abd213233eb64fa141",
          "sha256": "8e19f7c200d9bbb4a79f02227e8d69fcd2b17bde09ee208dff67f92ab0543434",
          "sha1": "39fd29903153aaba0b216b8392a0913a0482fc74",
          "md5": "87cc9b4172c94f137b8fb733e3a18966"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-bridge-0.3.2-sources.jar",
          "url": "echosvg-bridge-0.3.2-sources.jar",
          "size": 488791,
          "sha512": "e0be3b18195be84feeca28d8bd8a742e28ccccbec283ab23c0a9e091c1a21ea48104cacbc7c3c43d051f40e5f2a187af9c80939b81c1f4b42b779771eae163ee",
          "sha256": "a8527a6406cc03301e7446810a93c45f990ccc55d11f25fceacd827e8b3c3627",
          "sha1": "fa31cf9cc50eeb0ea2ad6a7bd6001ded7b3377ff",
          "md5": "089c5ebe7eab624dfff147b18e98be32"
        }
      ]
    }
  ]
}
