{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-ttf2svg",
    "version": "2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "echosvg-ttf2svg-2.3.jar",
          "url": "echosvg-ttf2svg-2.3.jar",
          "size": 6619,
          "sha512": "fc932ed04f9491c052a9bff0ae714966131517e7d66d65a0536f144e513137608220e87fd7828fd516dd2771da3338eb62a3f1cafc70511b6373f72abe593856",
          "sha256": "df140552e0b413418684fab19d12344b697d2a0d36c0f99569559fdf80e52252",
          "sha1": "55735866b0e5f7efe06d6506f88c9bc31048ff66",
          "md5": "bfd483c550fc0596a06e1f9354409ecf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-svggen",
          "version": {
            "requires": "2.3"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-ttf2svg-2.3.jar",
          "url": "echosvg-ttf2svg-2.3.jar",
          "size": 6619,
          "sha512": "fc932ed04f9491c052a9bff0ae714966131517e7d66d65a0536f144e513137608220e87fd7828fd516dd2771da3338eb62a3f1cafc70511b6373f72abe593856",
          "sha256": "df140552e0b413418684fab19d12344b697d2a0d36c0f99569559fdf80e52252",
          "sha1": "55735866b0e5f7efe06d6506f88c9bc31048ff66",
          "md5": "bfd483c550fc0596a06e1f9354409ecf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-ttf2svg-2.3-sources.jar",
          "url": "echosvg-ttf2svg-2.3-sources.jar",
          "size": 7250,
          "sha512": "e41cf66700b2f03e3def122b605b606429cb9b1b8caee8468f28a342c22f10c3767c4b2dd067e13f59b2d3f6f0f78591b71d18d75dd9cedc2580256f0cf676a0",
          "sha256": "176a7e68d8282f54f34edd4f0cd280f14b2df20d08cc5842b1e4b10ed2bfc70d",
          "sha1": "e7a10e7fc05c901205a0a35bc59fc06dbec54d66",
          "md5": "a0147f0aec87365c3f5dd897ae8d4156"
        }
      ]
    }
  ]
}
