{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-util",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-constants",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-util-0.1.jar",
          "url": "echosvg-util-0.1.jar",
          "size": 130683,
          "sha512": "3949a6acfe2fb87aaa3b43bed00a4ee2e166556a0b4ef46879fd32d135cac6654309a9ccfa261aa388b905b9cd9084f4b56075f920042f436a75fad235c3d696",
          "sha256": "9991d5eb901a82f7252efb126c143e6c77beede46ff22dada92a6284c7b26458",
          "sha1": "c2eabd7cded602dd0d08cc23300e17c9830373ac",
          "md5": "7f4684fb0908b65b9569ba8da240d80a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-constants",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-util-0.1.jar",
          "url": "echosvg-util-0.1.jar",
          "size": 130683,
          "sha512": "3949a6acfe2fb87aaa3b43bed00a4ee2e166556a0b4ef46879fd32d135cac6654309a9ccfa261aa388b905b9cd9084f4b56075f920042f436a75fad235c3d696",
          "sha256": "9991d5eb901a82f7252efb126c143e6c77beede46ff22dada92a6284c7b26458",
          "sha1": "c2eabd7cded602dd0d08cc23300e17c9830373ac",
          "md5": "7f4684fb0908b65b9569ba8da240d80a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-util-0.1-sources.jar",
          "url": "echosvg-util-0.1-sources.jar",
          "size": 109118,
          "sha512": "4550837a9efe8b6b5f214bdb6902eeb263dbf6544d1428d7fee5b6a111872fe22cdc4c9d2855bb75adce3356e5ff32e8797e49f359e5b9f763e2e64289485494",
          "sha256": "ca98352de01ef4a057d85c1ac84bb33a346cdf5b6ed38e3402a1b42c02090ed8",
          "sha1": "a097b438cc6d7756955cb8b3f31d854ae4244d4b",
          "md5": "e35450bcbb99bc3b2dc0d91a1102a00a"
        }
      ]
    }
  ]
}
