{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-util",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-constants",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-util-0.1.jar",
          "url": "echosvg-util-0.1.jar",
          "size": 130727,
          "sha512": "53bb1f22ed869396e5d3d1e267f6a5e19de050862e60e1e5f4c44d956950e58708e90571ee1b5993b6ac4dcad0283138f282b025d0f995d47ca5396bdf8078c4",
          "sha256": "5eb2cb4d80f0fdbefd7c96ca2cf6ae21e9cc318a14953adfb5f0099c6e4c550f",
          "sha1": "2e0da6b35c58da86ea19a8f899fc6678fcd2d6c7",
          "md5": "fff76cb0453c9916d47ddd4ae3b3ef3a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-constants",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-util-0.1.jar",
          "url": "echosvg-util-0.1.jar",
          "size": 130727,
          "sha512": "53bb1f22ed869396e5d3d1e267f6a5e19de050862e60e1e5f4c44d956950e58708e90571ee1b5993b6ac4dcad0283138f282b025d0f995d47ca5396bdf8078c4",
          "sha256": "5eb2cb4d80f0fdbefd7c96ca2cf6ae21e9cc318a14953adfb5f0099c6e4c550f",
          "sha1": "2e0da6b35c58da86ea19a8f899fc6678fcd2d6c7",
          "md5": "fff76cb0453c9916d47ddd4ae3b3ef3a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-util-0.1-sources.jar",
          "url": "echosvg-util-0.1-sources.jar",
          "size": 109146,
          "sha512": "a16f9e71c35de9bdd9820e14e305c5b73cce0fa88f04c482f6f9620dc896463736dd84ae7df0997a802d44994770649e63527a4bde2db0350e95e253a3187a12",
          "sha256": "fbe351687e82becf49e85779e3746963f35f0e48f55bd82f53873b501166e889",
          "sha1": "80b5b3e94cc6cbd9fcdbf9b3d7281840b2da3627",
          "md5": "fbe70766d0b03d639f33f3af51cf64d7"
        }
      ]
    }
  ]
}
