{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-awt-util",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.3"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.8"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-awt-util-0.3.jar",
          "url": "echosvg-awt-util-0.3.jar",
          "size": 431523,
          "sha512": "c2385d5e5d0918187fdfb2b09c83a18f1f3898ba9deb37a17014731973ccbb51fae030cec38fd7c1471e667c4bca782a4f72933f243a5143f678b4b51fa1ebe2",
          "sha256": "d022d0ac9006196676abaa046cc52b53a6b911e2ac7ec19bbb93b036771a9ae9",
          "sha1": "945d24cb34d2ef127c08ca293052078777da39b2",
          "md5": "af2a75c8150feb430a9059eeb9bbb7f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.3"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.8"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-awt-util-0.3.jar",
          "url": "echosvg-awt-util-0.3.jar",
          "size": 431523,
          "sha512": "c2385d5e5d0918187fdfb2b09c83a18f1f3898ba9deb37a17014731973ccbb51fae030cec38fd7c1471e667c4bca782a4f72933f243a5143f678b4b51fa1ebe2",
          "sha256": "d022d0ac9006196676abaa046cc52b53a6b911e2ac7ec19bbb93b036771a9ae9",
          "sha1": "945d24cb34d2ef127c08ca293052078777da39b2",
          "md5": "af2a75c8150feb430a9059eeb9bbb7f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-awt-util-0.3-sources.jar",
          "url": "echosvg-awt-util-0.3-sources.jar",
          "size": 392706,
          "sha512": "5b16ab38f56e3f2be7327422f4a1b850853f06cac135d32fb262b339cb4aa369f8f746953d6e0513a33eb8b867c6b938d3d5689614252d26e321a23250a45df4",
          "sha256": "435cf0bead642560c9228b09302e423acaf28512522d2285df5c0211a553acfd",
          "sha1": "18c086e93772b21c3539d392cb3107dc06c79960",
          "md5": "c2c3afba5e187906e9dc839108e549cf"
        }
      ]
    }
  ]
}
