{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-script",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.7.15"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-script-1.2.3.jar",
          "url": "echosvg-script-1.2.3.jar",
          "size": 27068,
          "sha512": "70c689d2314bac5d4fefe1c318572284ec544fd47f366124fc1e878e9bf9b8f2190999930436cbdd2ff74bc24e41cc3c98e4a8ff0e6ba7686f2f3d2c60446e3b",
          "sha256": "297b1410f20ddd7dcf6fb6dcc3ac06d17f7d71d19bcd40cea07b033d9a6740cb",
          "sha1": "84153412c263e091cdea6d58f9d4949f5b4ba730",
          "md5": "a669d15ebdcbdd571c665b55fc7d88c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.7.15"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-script-1.2.3.jar",
          "url": "echosvg-script-1.2.3.jar",
          "size": 27068,
          "sha512": "70c689d2314bac5d4fefe1c318572284ec544fd47f366124fc1e878e9bf9b8f2190999930436cbdd2ff74bc24e41cc3c98e4a8ff0e6ba7686f2f3d2c60446e3b",
          "sha256": "297b1410f20ddd7dcf6fb6dcc3ac06d17f7d71d19bcd40cea07b033d9a6740cb",
          "sha1": "84153412c263e091cdea6d58f9d4949f5b4ba730",
          "md5": "a669d15ebdcbdd571c665b55fc7d88c7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-script-1.2.3-sources.jar",
          "url": "echosvg-script-1.2.3-sources.jar",
          "size": 29667,
          "sha512": "054e1fff7ca95a08fbe321bf6c638a70c0b390fb74ef1d8448f0eaa4da41540bd22301d4521c069f6b9d5287d5e9e1aa000300db8f6c0c3de80a2f675d67a570",
          "sha256": "1bfe3b950e4ef8013f283b4dc0d510a3347c193d8a2a258e610f00e2ebacd96f",
          "sha1": "f92ab7310fee5451bc3723872c026363e41b8f2b",
          "md5": "3ebf1f5b64e173a4b214f8da97e9faa0"
        }
      ]
    }
  ]
}
