{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-codec",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-codec-1.2.2.jar",
          "url": "echosvg-codec-1.2.2.jar",
          "size": 102497,
          "sha512": "6ffe2a06d2ac7e268d9aebd24c3d73c38e2b73cb4898669935653c0304d11843e140599497489b2960ef787a0d4b62b2350427385223961b5897dbc1bbbd92d9",
          "sha256": "80dc9a53e91404a87467b2dc69da1156cf2adb0cdc3a3e678794384d69938c20",
          "sha1": "d3449c3a887fff80b17f05e44420cb253896c4cc",
          "md5": "a244fe48f822f8b319e7dea2f766f76f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-codec-1.2.2.jar",
          "url": "echosvg-codec-1.2.2.jar",
          "size": 102497,
          "sha512": "6ffe2a06d2ac7e268d9aebd24c3d73c38e2b73cb4898669935653c0304d11843e140599497489b2960ef787a0d4b62b2350427385223961b5897dbc1bbbd92d9",
          "sha256": "80dc9a53e91404a87467b2dc69da1156cf2adb0cdc3a3e678794384d69938c20",
          "sha1": "d3449c3a887fff80b17f05e44420cb253896c4cc",
          "md5": "a244fe48f822f8b319e7dea2f766f76f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-codec-1.2.2-sources.jar",
          "url": "echosvg-codec-1.2.2-sources.jar",
          "size": 97104,
          "sha512": "3b3be21964314a0afe3ab6ccff49d3e6f0787b1834e535c2fbde4e42f72103fbf45fc4d939d878cf58cd52199ad352fe03e60ece9fe05f9d2e00bfd99cc89c2e",
          "sha256": "459b42f51caf4c9a799c2f313c7ce9113f05142fd8ce2bf55dd6a234c2e4938b",
          "sha1": "f3c8113ec226ec8428b2bb2ebc6e1bf1a5133532",
          "md5": "6027f5a9cf811f81dd464f4d3c104fa5"
        }
      ]
    }
  ]
}
