{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "css4j-agent",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "css4j",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "xml-dtd",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "nu.validator",
          "module": "htmlparser",
          "version": {
            "requires": "1.4.16"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "css4j-agent-3.5.0.jar",
          "url": "css4j-agent-3.5.0.jar",
          "size": 89545,
          "sha512": "2bd8f7b63357073a27328d7d7ea4e7079cffa94494ddd9951f9a518bd893378b82025a4b7ccb5377f713ff06d40041427c6f09f1cbca33ff9a25bf21283384ad",
          "sha256": "17873a9ea61c507803494cb408d4fa9581b283e0310e820e9bc6d4ae83ad2568",
          "sha1": "aeaddc95a5f5afe6faa9a452041ff363bc690d17",
          "md5": "7fadda42bb356e271892eea42d67c15f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "css4j",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "xml-dtd",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "nu.validator",
          "module": "htmlparser",
          "version": {
            "requires": "1.4.16"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "css4j-agent-3.5.0.jar",
          "url": "css4j-agent-3.5.0.jar",
          "size": 89545,
          "sha512": "2bd8f7b63357073a27328d7d7ea4e7079cffa94494ddd9951f9a518bd893378b82025a4b7ccb5377f713ff06d40041427c6f09f1cbca33ff9a25bf21283384ad",
          "sha256": "17873a9ea61c507803494cb408d4fa9581b283e0310e820e9bc6d4ae83ad2568",
          "sha1": "aeaddc95a5f5afe6faa9a452041ff363bc690d17",
          "md5": "7fadda42bb356e271892eea42d67c15f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "css4j-agent-3.5.0-javadoc.jar",
          "url": "css4j-agent-3.5.0-javadoc.jar",
          "size": 125325,
          "sha512": "413c705dc0f85a9722bce718fe8332bd60275bcb2faceb57a033639b062770a499ddc3ed7db0490c079abf267cc6fa660a744dee9e9f6ab497ca755adf6fa7d9",
          "sha256": "a11a493578a277d81bcca5fb625e4ab65bc8edfba5c2d7db5d4374bb507b92c3",
          "sha1": "2611fdb7aef34a051d287e94d80858c9a15c19de",
          "md5": "442bb8e62df1aad8222fca7778c76ad8"
        },
        {
          "name": "css4j-agent-3.5.0-javadoc.jar",
          "url": "css4j-agent-3.5.0-javadoc.jar",
          "size": 125325,
          "sha512": "413c705dc0f85a9722bce718fe8332bd60275bcb2faceb57a033639b062770a499ddc3ed7db0490c079abf267cc6fa660a744dee9e9f6ab497ca755adf6fa7d9",
          "sha256": "a11a493578a277d81bcca5fb625e4ab65bc8edfba5c2d7db5d4374bb507b92c3",
          "sha1": "2611fdb7aef34a051d287e94d80858c9a15c19de",
          "md5": "442bb8e62df1aad8222fca7778c76ad8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "css4j-agent-3.5.0-sources.jar",
          "url": "css4j-agent-3.5.0-sources.jar",
          "size": 81368,
          "sha512": "1b5b74c58a7c88f62682cc8322863b941f614442984ce123702a9043259c0f72241c5914f4c770a696c3091a6ff273bd0bd2282c3f2adb98d36cd2cbf272db70",
          "sha256": "4ae0841b11fcc0b1aac323874937df2420adc4e3c045fb56e264e9fb8d9680ea",
          "sha1": "9cd1042700c35498ffc5a69a5542a9ac333fb624",
          "md5": "c155e860f5a7534de6b56a8a50398583"
        }
      ]
    }
  ]
}
