{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-script",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.7.15"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-script-1.2.jar",
          "url": "echosvg-script-1.2.jar",
          "size": 27016,
          "sha512": "2f5067d40e3de4d7be1c7658f1f18571c498a43d5e31bf3881eb19efef1b176271026e6706aefb378a295621b0df5fc7a6cbb8872b0562ad8be72f41b8207f0d",
          "sha256": "52e5e7920ddcdb6e0083e664bef06eb2aec42ed015f26fa210cbcc3b5f914d0b",
          "sha1": "d138f1a4fada933aa23beec4996ac4aa624bfb03",
          "md5": "2c87288f2acaa6bbde66086c20716d36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "xml-apis",
          "module": "xml-apis",
          "version": {
            "requires": "1.4.01"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.7.15"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-script-1.2.jar",
          "url": "echosvg-script-1.2.jar",
          "size": 27016,
          "sha512": "2f5067d40e3de4d7be1c7658f1f18571c498a43d5e31bf3881eb19efef1b176271026e6706aefb378a295621b0df5fc7a6cbb8872b0562ad8be72f41b8207f0d",
          "sha256": "52e5e7920ddcdb6e0083e664bef06eb2aec42ed015f26fa210cbcc3b5f914d0b",
          "sha1": "d138f1a4fada933aa23beec4996ac4aa624bfb03",
          "md5": "2c87288f2acaa6bbde66086c20716d36"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-script-1.2-sources.jar",
          "url": "echosvg-script-1.2-sources.jar",
          "size": 29615,
          "sha512": "d29fddf13f96d704f2f487ab498a053391d7376ddb7b75fa73d9fa51f841a6d86f7b9216ad468fc6fedb1e147fa716c09d8748d1bcac5b5ecaf2d3fa8cf03bac",
          "sha256": "cc4a6011d83c7dd2fbd3ac21f715a675ad71a93db736ba51212f15325efa9ae0",
          "sha1": "fe5dc08dc68c92880c157db6370ac1e587373aec",
          "md5": "cb1678334f389207aa4b719e1c2d7f83"
        }
      ]
    }
  ]
}
