{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-svg-dom",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svg-dom-0.1.jar",
          "url": "echosvg-svg-dom-0.1.jar",
          "size": 232647,
          "sha512": "19d1ca4d3ab6a50c74d6455141efe5ddd14cb2dabd725495bc9550d815064cc644f49f628e11887d709110b35ad0d98a39d8fd421457e242d86ee69fade55f93",
          "sha256": "df1a0ce4e921d0d7517b689e392511e1c1ff85a0a0557cf35e85edfb67fca057",
          "sha1": "8371af77838c75c319c9297cff61065a7a37821d",
          "md5": "e38abcc7337ee39abaca0190417e192c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svg-dom-0.1.jar",
          "url": "echosvg-svg-dom-0.1.jar",
          "size": 232647,
          "sha512": "19d1ca4d3ab6a50c74d6455141efe5ddd14cb2dabd725495bc9550d815064cc644f49f628e11887d709110b35ad0d98a39d8fd421457e242d86ee69fade55f93",
          "sha256": "df1a0ce4e921d0d7517b689e392511e1c1ff85a0a0557cf35e85edfb67fca057",
          "sha1": "8371af77838c75c319c9297cff61065a7a37821d",
          "md5": "e38abcc7337ee39abaca0190417e192c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-svg-dom-0.1-sources.jar",
          "url": "echosvg-svg-dom-0.1-sources.jar",
          "size": 226445,
          "sha512": "7657160db07d5298a46b4178836cb156fa4a39bb00d93f72a12e3f966225cc2d2429ef349afda4688efd6c4d38208dcdc3e3c4d5029aeb417d79150864eb95e8",
          "sha256": "c6f1464b2a4ee9a7d0e482e62dd188e8e80eb7aa31c195223d9d66585a79574b",
          "sha1": "28e001438ecf51f37fb9e808704f38f0cc0521d6",
          "md5": "6ba3b9f55fd9107a68e03c521d1da040"
        }
      ]
    }
  ]
}
