{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-svg-dom",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "xml-apis",
          "module": "xml-apis-ext",
          "version": {
            "requires": "1.3.04"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svg-dom-0.1.jar",
          "url": "echosvg-svg-dom-0.1.jar",
          "size": 232695,
          "sha512": "88665ebaef627b4d255fbaa2fb8f06d711a6f6201f751f353c41c1823107c72b7cc581328ee08b4dee717085bbe02edee0a33c9cb2019f5cef51e2c756bf21fc",
          "sha256": "4b1df7b43f706d738f420bdec9e54274bc29d4d32825ce71059081e8ddcb6ae4",
          "sha1": "6f26369b8bc7c514a87b8d4ff8718d9610aa7f8f",
          "md5": "1963b6dae02e7a831af60d3b9d36906e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "xml-apis",
          "module": "xml-apis-ext",
          "version": {
            "requires": "1.3.04"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svg-dom-0.1.jar",
          "url": "echosvg-svg-dom-0.1.jar",
          "size": 232695,
          "sha512": "88665ebaef627b4d255fbaa2fb8f06d711a6f6201f751f353c41c1823107c72b7cc581328ee08b4dee717085bbe02edee0a33c9cb2019f5cef51e2c756bf21fc",
          "sha256": "4b1df7b43f706d738f420bdec9e54274bc29d4d32825ce71059081e8ddcb6ae4",
          "sha1": "6f26369b8bc7c514a87b8d4ff8718d9610aa7f8f",
          "md5": "1963b6dae02e7a831af60d3b9d36906e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-svg-dom-0.1-sources.jar",
          "url": "echosvg-svg-dom-0.1-sources.jar",
          "size": 226476,
          "sha512": "26835d7a4ba000110cfee6154e552a90512be27f3b5fbbcfbad0197345d4c1688e3c27c2714fcc1f47cc94423dcd4a4a9dccf2a7e9a17d7d2217fd8552644a06",
          "sha256": "730e48f0730f98b2321919ef7332fdc1bf1437f451da89a3ac31f75238977827",
          "sha1": "c3fea6dee59c54d42180e8412e8a1de097a38fd5",
          "md5": "39c90442952c75cb311e251ae4a1f33c"
        }
      ]
    }
  ]
}
