{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-script",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.7.14-RC1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-script-0.1.2.jar",
          "url": "echosvg-script-0.1.2.jar",
          "size": 25606,
          "sha512": "2d4fc0eba4aa7e8e55c2f0c07dfc0de9c96132348f7d4939504b6f665cbac137b7b7093a37cb2c965ddde1fcc44f56195fe68ad2387ac491117661169ce8597a",
          "sha256": "dea7ed5e485a5a4aca27d727c27d8f298b01312adb381bdaee7857c1d4f2a51c",
          "sha1": "a2b08c0822d8c3291a5c63b6d1c0f13b51510571",
          "md5": "629deb7d11b679cc17252564aa067bfa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.7.14-RC1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-script-0.1.2.jar",
          "url": "echosvg-script-0.1.2.jar",
          "size": 25606,
          "sha512": "2d4fc0eba4aa7e8e55c2f0c07dfc0de9c96132348f7d4939504b6f665cbac137b7b7093a37cb2c965ddde1fcc44f56195fe68ad2387ac491117661169ce8597a",
          "sha256": "dea7ed5e485a5a4aca27d727c27d8f298b01312adb381bdaee7857c1d4f2a51c",
          "sha1": "a2b08c0822d8c3291a5c63b6d1c0f13b51510571",
          "md5": "629deb7d11b679cc17252564aa067bfa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-script-0.1.2-sources.jar",
          "url": "echosvg-script-0.1.2-sources.jar",
          "size": 28746,
          "sha512": "f9e59b4eb749733b2fb74658aa89aa2c08962acc8aa10417d615b7b37497b72e4ccf23663cdd1ec325254006fd160cddf0930c12f95894a6b5b4de12f7768407",
          "sha256": "190f1ac570392c3d08c8778a23fd132031c036579c314923b833825e05071e19",
          "sha1": "6b181dfcc50805f3c2d917a7bb611f5160d8ea60",
          "md5": "d846545c7f55404a5513fd71b51b9c92"
        }
      ]
    }
  ]
}
