{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-awt-util",
    "version": "2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-awt-util-2.5.jar",
          "url": "echosvg-awt-util-2.5.jar",
          "size": 423500,
          "sha512": "8c6f5a0446d33ae5dde883a946ae7cc0e06e5e8daff70291f55907f12fe1adf6dbdae0207dc58ff445e7673bb70b4f3949b757703be004906a28fe56965873cf",
          "sha256": "1fab0f03fbde7195d9398b4d5ff272086eb2ce7ed0528207a66fb59fc2aadf22",
          "sha1": "1696cd2f44d410c0600909581500debdfd48295a",
          "md5": "d66d98a6cac0ffbbc1e992aef4ef808c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-awt-util-2.5.jar",
          "url": "echosvg-awt-util-2.5.jar",
          "size": 423500,
          "sha512": "8c6f5a0446d33ae5dde883a946ae7cc0e06e5e8daff70291f55907f12fe1adf6dbdae0207dc58ff445e7673bb70b4f3949b757703be004906a28fe56965873cf",
          "sha256": "1fab0f03fbde7195d9398b4d5ff272086eb2ce7ed0528207a66fb59fc2aadf22",
          "sha1": "1696cd2f44d410c0600909581500debdfd48295a",
          "md5": "d66d98a6cac0ffbbc1e992aef4ef808c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-awt-util-2.5-sources.jar",
          "url": "echosvg-awt-util-2.5-sources.jar",
          "size": 392955,
          "sha512": "d523b13d3fe080a952d2fc0ff99a9e6cf71093b6f42aca873a3c349c5bae45aa07b5eb7799112bc31beeff6bd8ff52b4aa76923f0c4550ff9ae6780c56a4afa4",
          "sha256": "bd10931959ed898bd3bbe88f6b82431e333d79077c451d8072a25ab5e76b4599",
          "sha1": "51d31b8ae2159fd4313faaa1872470d864ce34c1",
          "md5": "44fa2872b2ba95d1ccf640c551c25dc6"
        }
      ]
    }
  ]
}
