{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-svgrasterizer",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svgrasterizer-0.2.2.jar",
          "url": "echosvg-svgrasterizer-0.2.2.jar",
          "size": 58863,
          "sha512": "b7ea6a4770435fbb6588a4004ab6e1571836caeb21c25c4325ef634bca5d34a7e9be9281c25acdd72272bc31d43cea6c318671af59626bab8565868fd600be72",
          "sha256": "f661dfe5117dca4e2045cd4a88e53a9b0ad398e8ebb2975092cc8dd378ea987f",
          "sha1": "29dc5cfaa562fa874139b6343d37c68e61a94e81",
          "md5": "4fd81510dd46baabe306e70c80921b21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svgrasterizer-0.2.2.jar",
          "url": "echosvg-svgrasterizer-0.2.2.jar",
          "size": 58863,
          "sha512": "b7ea6a4770435fbb6588a4004ab6e1571836caeb21c25c4325ef634bca5d34a7e9be9281c25acdd72272bc31d43cea6c318671af59626bab8565868fd600be72",
          "sha256": "f661dfe5117dca4e2045cd4a88e53a9b0ad398e8ebb2975092cc8dd378ea987f",
          "sha1": "29dc5cfaa562fa874139b6343d37c68e61a94e81",
          "md5": "4fd81510dd46baabe306e70c80921b21"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-svgrasterizer-0.2.2-sources.jar",
          "url": "echosvg-svgrasterizer-0.2.2-sources.jar",
          "size": 36243,
          "sha512": "8a92460aa7ed0c2a1ee415bb9884ed9ba4aa97b7ab6e60130bddfb6d9c243cb9e2f9950a07a4947d4d1caaa470539af0cfed788a9cbb3f44c19009f992ef6113",
          "sha256": "4ff6a61a6a0d7a1810e088702934533c3cc6935a311596fb75e3f7452d0fd9fc",
          "sha1": "c8f3b3019d49a48b2a3606f06e6d421e95839447",
          "md5": "aac4c67f62f55da98c86d164f445f56b"
        }
      ]
    }
  ]
}
