{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-parser",
    "version": "0.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.8"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-parser-0.3.3.jar",
          "url": "echosvg-parser-0.3.3.jar",
          "size": 76325,
          "sha512": "0a9aeb94ce8b449ffe68ebc95a1421fec6753201d7b2f382ddb71bf3b433ec3237e754bd1b7ae10d7b964e4fcf1d2f77258544561d3732724e5a8ba5e09d5eae",
          "sha256": "35f322c48e63d101706bc94263b1b630b9c175059077bd68439465778f5250a2",
          "sha1": "bdbcab45a052022b14adcc2651bc56ee5febb60f",
          "md5": "479e5878ee44743e7c9847bb82d2c342"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "0.3.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.8"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-parser-0.3.3.jar",
          "url": "echosvg-parser-0.3.3.jar",
          "size": 76325,
          "sha512": "0a9aeb94ce8b449ffe68ebc95a1421fec6753201d7b2f382ddb71bf3b433ec3237e754bd1b7ae10d7b964e4fcf1d2f77258544561d3732724e5a8ba5e09d5eae",
          "sha256": "35f322c48e63d101706bc94263b1b630b9c175059077bd68439465778f5250a2",
          "sha1": "bdbcab45a052022b14adcc2651bc56ee5febb60f",
          "md5": "479e5878ee44743e7c9847bb82d2c342"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-parser-0.3.3-sources.jar",
          "url": "echosvg-parser-0.3.3-sources.jar",
          "size": 82457,
          "sha512": "87892496552e3e68a06241562c2475f268cf6bc18d696efb92ca39f56e97c1b06c445e9e42721489e8c134f2113f59cb6210325c19e24c2d1e67eeb5ede3979c",
          "sha256": "114eef8d26a8ff62626eeeb317d1bbfbb1f0ed29257dc69e28255b56495ca491",
          "sha1": "bed7bbe829c437ec0cf0952c33558de09813a00f",
          "md5": "50416115cd251aa9ff10d351832774f5"
        }
      ]
    }
  ]
}
