{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-svg-dom",
    "version": "2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "2.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svg-dom-2.1.jar",
          "url": "echosvg-svg-dom-2.1.jar",
          "size": 75684,
          "sha512": "5bf727d75669b9943c688b282e15e8a23ebe2054a9b405fa95c78ffba9e928887a2b9e2c86b1cbc7de81ad68b58788b68a991578ffd623c1a97143d15f241334",
          "sha256": "31f4d77a6115fb17084675eabe429459390f4d2650f41239326cad9668d38272",
          "sha1": "72262753a315f573b58b692d2b1848ab69b93ee0",
          "md5": "9eb6304a27d9a2e83d539fe54d21c02a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "2.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svg-dom-2.1.jar",
          "url": "echosvg-svg-dom-2.1.jar",
          "size": 75684,
          "sha512": "5bf727d75669b9943c688b282e15e8a23ebe2054a9b405fa95c78ffba9e928887a2b9e2c86b1cbc7de81ad68b58788b68a991578ffd623c1a97143d15f241334",
          "sha256": "31f4d77a6115fb17084675eabe429459390f4d2650f41239326cad9668d38272",
          "sha1": "72262753a315f573b58b692d2b1848ab69b93ee0",
          "md5": "9eb6304a27d9a2e83d539fe54d21c02a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-svg-dom-2.1-sources.jar",
          "url": "echosvg-svg-dom-2.1-sources.jar",
          "size": 70330,
          "sha512": "627981c2130d5bf7c3cc321bb7a5aca417085bcf80aff3f3cfc48b5f7edb0487dd51c29525f7e282413df071b2ff9f9974ebfb11228528b3f59123546eadffe9",
          "sha256": "c8f5a796400f886bba4187de041bfcd65d10a7dc7afcd291600725ec5f0af3d5",
          "sha1": "255bf15561068397c5393897a0ebb5850052c2d9",
          "md5": "7bb5fad984b98e442d6cbc6ff1378af9"
        }
      ]
    }
  ]
}
