{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "css4j-dom4j",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "css4j",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "css4j-dom4j-3.5.0.jar",
          "url": "css4j-dom4j-3.5.0.jar",
          "size": 69736,
          "sha512": "9c9c8bcec49f28856b7da7f1671deaf6e3fc1992150d1b79e807a244a201fd11717311bdcc9031e414fd70458fa7ec0175c1cf8310ac660806d16196ed243e06",
          "sha256": "5476eca98ea4ee145607d569565bd6f08db31d0643d092f4dd960a9771c2153f",
          "sha1": "1928821761dd3004e5c27fe86d4656ee13d57c52",
          "md5": "669f5b9abdda4da9350e3177fa7acbec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "css4j-agent",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "xmlpull",
          "module": "xmlpull",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "xpp3",
          "module": "xpp3_min",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "css4j",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "css4j-dom4j-3.5.0.jar",
          "url": "css4j-dom4j-3.5.0.jar",
          "size": 69736,
          "sha512": "9c9c8bcec49f28856b7da7f1671deaf6e3fc1992150d1b79e807a244a201fd11717311bdcc9031e414fd70458fa7ec0175c1cf8310ac660806d16196ed243e06",
          "sha256": "5476eca98ea4ee145607d569565bd6f08db31d0643d092f4dd960a9771c2153f",
          "sha1": "1928821761dd3004e5c27fe86d4656ee13d57c52",
          "md5": "669f5b9abdda4da9350e3177fa7acbec"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "css4j-dom4j-3.5.0-javadoc.jar",
          "url": "css4j-dom4j-3.5.0-javadoc.jar",
          "size": 156737,
          "sha512": "c18720acd57ef44882272a2184a007e83b4d7b4c3e4ba18a039589cb194980365b1e1c0710cc0ee17540f06f20d764080fcaa692636469c9a6f77cba042b779a",
          "sha256": "e5bf023421d399ebb50814246f215eaf76cfbcca332750272ccff638a243bacd",
          "sha1": "12611424fddbd9723f4702efb3ece7f0ba827009",
          "md5": "996fbeb39dab049b74cbf23be3eb4756"
        },
        {
          "name": "css4j-dom4j-3.5.0-javadoc.jar",
          "url": "css4j-dom4j-3.5.0-javadoc.jar",
          "size": 156737,
          "sha512": "c18720acd57ef44882272a2184a007e83b4d7b4c3e4ba18a039589cb194980365b1e1c0710cc0ee17540f06f20d764080fcaa692636469c9a6f77cba042b779a",
          "sha256": "e5bf023421d399ebb50814246f215eaf76cfbcca332750272ccff638a243bacd",
          "sha1": "12611424fddbd9723f4702efb3ece7f0ba827009",
          "md5": "996fbeb39dab049b74cbf23be3eb4756"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "css4j-dom4j-3.5.0-sources.jar",
          "url": "css4j-dom4j-3.5.0-sources.jar",
          "size": 40568,
          "sha512": "76c97cc870dffe6ad617114a2b7a122d0c7fe1c28fd14bb93d7161cb6d19b6f62fec1ef941be5a77d5be700c2dda1c520c44299c6034379039bf91a62347cb6a",
          "sha256": "f3b6da11279c8ed50f4e8946978361f6f148f8d532643f05dd3012f44223a20d",
          "sha1": "cda4955f705744d34266e7ff30578e5638b1bc29",
          "md5": "6fcd71d232d84b333143baa84f50d073"
        }
      ]
    }
  ]
}
