{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "css4j",
    "version": "4.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "carte-util",
          "version": {
            "requires": "[3.6.0,)"
          }
        }
      ],
      "files": [
        {
          "name": "css4j-4.3.1.jar",
          "url": "css4j-4.3.1.jar",
          "size": 1543302,
          "sha512": "e22ad40b2cc7b5c82c0d9a73de349699d7c99b8f92ffe6c64d6e55418c847ca3a5912a7585d9891f256017fca14c382fa583d5dbdb2d3a56cc07e7f97b1211ea",
          "sha256": "193b4c219b1aa63b1ab1faff4a830f1eb2d164bfbe1fed33aca58308befa71a5",
          "sha1": "7e5abd0f8f08f27ecc0c49bc34493f65dfabb48c",
          "md5": "6c0105e74db07d450a80a27f94032227"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "tokenproducer",
          "version": {
            "requires": "[3.0,)"
          }
        },
        {
          "group": "io.sf.jclf",
          "module": "jclf-text",
          "version": {
            "requires": "[5.0.0,)"
          }
        },
        {
          "group": "io.sf.jclf",
          "module": "jclf-linear3",
          "version": {
            "requires": "[1.0.0,)"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "carte-util",
          "version": {
            "requires": "[3.6.0,)"
          }
        }
      ],
      "files": [
        {
          "name": "css4j-4.3.1.jar",
          "url": "css4j-4.3.1.jar",
          "size": 1543302,
          "sha512": "e22ad40b2cc7b5c82c0d9a73de349699d7c99b8f92ffe6c64d6e55418c847ca3a5912a7585d9891f256017fca14c382fa583d5dbdb2d3a56cc07e7f97b1211ea",
          "sha256": "193b4c219b1aa63b1ab1faff4a830f1eb2d164bfbe1fed33aca58308befa71a5",
          "sha1": "7e5abd0f8f08f27ecc0c49bc34493f65dfabb48c",
          "md5": "6c0105e74db07d450a80a27f94032227"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "css4j-4.3.1-javadoc.jar",
          "url": "css4j-4.3.1-javadoc.jar",
          "size": 2036350,
          "sha512": "ff4488294b15c4de8a91b114e876cbb6e052edec3bd1bc281901d4eb35074904dd04ac9f352dfcba2f1f74cf85106c791a7a8f80d95875623c67fd902402232f",
          "sha256": "e4b4a92db9167b1c3bbd290cbfdfb99067515ac7e1390a4d5a6f3aa01e7bd5eb",
          "sha1": "8248ca8b4c7ef7b2464ce84ccbde5955a3631401",
          "md5": "572e5840b73c2c3303e4cc3cb9e422ec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "css4j-4.3.1-sources.jar",
          "url": "css4j-4.3.1-sources.jar",
          "size": 878571,
          "sha512": "a26d23c7af623289926269686f813257bd884939e2dcf3446aa6d39d337c057d9fc1bedf130551c339cbe62318b4a61db6ad1431184289619d07a219a3037d58",
          "sha256": "c40c2e5dd27c29dfead8900d8a0e7bfd80c62cab43c31c7832d89484f0bbecb9",
          "sha1": "ebc6c9d4a82b299d0121f6bab7555f5335be0d6a",
          "md5": "fb6c48601f575c802809f7090c57eea5"
        }
      ]
    },
    {
      "name": "xmldtdApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "css4j-4.3.1.jar",
          "url": "css4j-4.3.1.jar",
          "size": 1543302,
          "sha512": "e22ad40b2cc7b5c82c0d9a73de349699d7c99b8f92ffe6c64d6e55418c847ca3a5912a7585d9891f256017fca14c382fa583d5dbdb2d3a56cc07e7f97b1211ea",
          "sha256": "193b4c219b1aa63b1ab1faff4a830f1eb2d164bfbe1fed33aca58308befa71a5",
          "sha1": "7e5abd0f8f08f27ecc0c49bc34493f65dfabb48c",
          "md5": "6c0105e74db07d450a80a27f94032227"
        }
      ],
      "capabilities": [
        {
          "group": "io.sf.carte",
          "name": "css4j-xmldtd",
          "version": "4.3.1"
        }
      ]
    },
    {
      "name": "xmldtdRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "xml-dtd",
          "version": {
            "requires": "[4.2.1,)"
          }
        }
      ],
      "files": [
        {
          "name": "css4j-4.3.1.jar",
          "url": "css4j-4.3.1.jar",
          "size": 1543302,
          "sha512": "e22ad40b2cc7b5c82c0d9a73de349699d7c99b8f92ffe6c64d6e55418c847ca3a5912a7585d9891f256017fca14c382fa583d5dbdb2d3a56cc07e7f97b1211ea",
          "sha256": "193b4c219b1aa63b1ab1faff4a830f1eb2d164bfbe1fed33aca58308befa71a5",
          "sha1": "7e5abd0f8f08f27ecc0c49bc34493f65dfabb48c",
          "md5": "6c0105e74db07d450a80a27f94032227"
        }
      ],
      "capabilities": [
        {
          "group": "io.sf.carte",
          "name": "css4j-xmldtd",
          "version": "4.3.1"
        }
      ]
    },
    {
      "name": "loggingApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "css4j-4.3.1.jar",
          "url": "css4j-4.3.1.jar",
          "size": 1543302,
          "sha512": "e22ad40b2cc7b5c82c0d9a73de349699d7c99b8f92ffe6c64d6e55418c847ca3a5912a7585d9891f256017fca14c382fa583d5dbdb2d3a56cc07e7f97b1211ea",
          "sha256": "193b4c219b1aa63b1ab1faff4a830f1eb2d164bfbe1fed33aca58308befa71a5",
          "sha1": "7e5abd0f8f08f27ecc0c49bc34493f65dfabb48c",
          "md5": "6c0105e74db07d450a80a27f94032227"
        }
      ],
      "capabilities": [
        {
          "group": "io.sf.carte",
          "name": "css4j-logging",
          "version": "4.3.1"
        }
      ]
    },
    {
      "name": "loggingRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "[1.7.28,)"
          }
        }
      ],
      "files": [
        {
          "name": "css4j-4.3.1.jar",
          "url": "css4j-4.3.1.jar",
          "size": 1543302,
          "sha512": "e22ad40b2cc7b5c82c0d9a73de349699d7c99b8f92ffe6c64d6e55418c847ca3a5912a7585d9891f256017fca14c382fa583d5dbdb2d3a56cc07e7f97b1211ea",
          "sha256": "193b4c219b1aa63b1ab1faff4a830f1eb2d164bfbe1fed33aca58308befa71a5",
          "sha1": "7e5abd0f8f08f27ecc0c49bc34493f65dfabb48c",
          "md5": "6c0105e74db07d450a80a27f94032227"
        }
      ],
      "capabilities": [
        {
          "group": "io.sf.carte",
          "name": "css4j-logging",
          "version": "4.3.1"
        }
      ]
    }
  ]
}
