{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-css",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.9"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "css4j",
          "version": {
            "requires": "4.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-css-1.0.jar",
          "url": "echosvg-css-1.0.jar",
          "size": 292652,
          "sha512": "1fff83d1fc97d4c0a787f3c7bc56675eda3143df954714795f552975a3ed8d986d9fc734f864f45c8389bc1c90fa702d9260e0fea88a7314fa0114be2852ef2c",
          "sha256": "3e2be36770a340407d4ab81e8719281bc52ec53213aa0154b6764e8b937a07c0",
          "sha1": "22b8c6bf1339b5c0e8bc35e195ab3dfefbf87c6b",
          "md5": "db6e1f1776ffdc85d347b94c05b8d260"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.9"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "css4j",
          "version": {
            "requires": "4.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-css-1.0.jar",
          "url": "echosvg-css-1.0.jar",
          "size": 292652,
          "sha512": "1fff83d1fc97d4c0a787f3c7bc56675eda3143df954714795f552975a3ed8d986d9fc734f864f45c8389bc1c90fa702d9260e0fea88a7314fa0114be2852ef2c",
          "sha256": "3e2be36770a340407d4ab81e8719281bc52ec53213aa0154b6764e8b937a07c0",
          "sha1": "22b8c6bf1339b5c0e8bc35e195ab3dfefbf87c6b",
          "md5": "db6e1f1776ffdc85d347b94c05b8d260"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-css-1.0-sources.jar",
          "url": "echosvg-css-1.0-sources.jar",
          "size": 209852,
          "sha512": "07c6de99abcb77f32c702cb2aa3b45d00b25c9ca1cb65405765372d3502a67efaf3312ea69b7568b6c7e81a043afda44bad8d1a9266dc14c6cff8bf37c43d3ff",
          "sha256": "df72b28a6cd7515515ed40bc7b14f193702e2dd3389d21706afcfc178d37799c",
          "sha1": "b0be73beed21ef1fc00390b406e23c4afe9d2558",
          "md5": "6639cd771da91618bd11ba3a5baba6cd"
        }
      ]
    }
  ]
}
