{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-all",
    "version": "2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext-swing",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-extension",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-swing",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-slideshow",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgpp",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-api",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-svg",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-svg2svg",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-tosvg",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ttf2svg",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgrasterizer",
          "version": {
            "requires": "2.4"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-all-2.4.jar",
          "url": "echosvg-all-2.4.jar",
          "size": 5714,
          "sha512": "3d19f5d7e5e2456b34c0992dfddd2e3bca17f756888d0b43898370e51d7343926817945806e247eed0656ba1729aaf5c1a59a4f8d08e0309bc2dff1548cf1062",
          "sha256": "e834d3d8863f038ff834867c36253756c2904fee3995f72837cc6fcabf188cbd",
          "sha1": "474cf6b355134f96ca579de202850eb45a66a885",
          "md5": "bdc6e2783ecbad840d5b8fc7f51a6b59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext-swing",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-extension",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-swing",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-slideshow",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgpp",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-api",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-svg",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-svg2svg",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-tosvg",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ttf2svg",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgrasterizer",
          "version": {
            "requires": "2.4"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-all-2.4.jar",
          "url": "echosvg-all-2.4.jar",
          "size": 5714,
          "sha512": "3d19f5d7e5e2456b34c0992dfddd2e3bca17f756888d0b43898370e51d7343926817945806e247eed0656ba1729aaf5c1a59a4f8d08e0309bc2dff1548cf1062",
          "sha256": "e834d3d8863f038ff834867c36253756c2904fee3995f72837cc6fcabf188cbd",
          "sha1": "474cf6b355134f96ca579de202850eb45a66a885",
          "md5": "bdc6e2783ecbad840d5b8fc7f51a6b59"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-all-2.4-sources.jar",
          "url": "echosvg-all-2.4-sources.jar",
          "size": 5872,
          "sha512": "b5b8bea353452c8792413dc784c9fea096e39b73a405ef8bcdbb2a62bfe79fbd41a1c347e0b8cfe1811303fd2f477a463a2eb3a1cba85b86286d1852e47126ee",
          "sha256": "9484b95125dceb3a157e9bc2444ed84190359389425705a8246524e50272b33e",
          "sha1": "6d6d2c45bb2861c95845dbf3828781a14b3870f6",
          "md5": "e4d8facb5eba6ceaed615d2543b99376"
        }
      ]
    }
  ]
}
