{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-transcoder",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svggen",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-transcoder-1.2.3.jar",
          "url": "echosvg-transcoder-1.2.3.jar",
          "size": 162018,
          "sha512": "6f6b3c636e5f968d8a18e683db09eff2fd2bb8ab164b191be6ce9ba72a3054fa1435e00b2ca9c22ddcac556caf957d47e93f081efb0a1db6ad230a9662b19995",
          "sha256": "370debf61fb63b1cb691f51c0346aeb5c5e9c1435f16e7129b1759c03351c25d",
          "sha1": "1dc9e6eec62eeedead81027ea213625780d02dcc",
          "md5": "0d854e6472723a7514807a08d21c374a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-codec",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "css4j-awt",
          "version": {
            "requires": "4.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svggen",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-transcoder-1.2.3.jar",
          "url": "echosvg-transcoder-1.2.3.jar",
          "size": 162018,
          "sha512": "6f6b3c636e5f968d8a18e683db09eff2fd2bb8ab164b191be6ce9ba72a3054fa1435e00b2ca9c22ddcac556caf957d47e93f081efb0a1db6ad230a9662b19995",
          "sha256": "370debf61fb63b1cb691f51c0346aeb5c5e9c1435f16e7129b1759c03351c25d",
          "sha1": "1dc9e6eec62eeedead81027ea213625780d02dcc",
          "md5": "0d854e6472723a7514807a08d21c374a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-transcoder-1.2.3-sources.jar",
          "url": "echosvg-transcoder-1.2.3-sources.jar",
          "size": 133414,
          "sha512": "cb00cf42c6ed10125244050e87c54baf6d9b8cbea69fe040e4f2f720feb795585af475f20bff0d9e9a09b034075eb98cd56e9f3628a614ba458a5dd582a279cf",
          "sha256": "23bd64373e426758a87d35d74934e8363e356a806ea70dca7f70564b78532739",
          "sha1": "f18b5327bdd509ca59666cb75228fa971025a8c8",
          "md5": "132a0996e1a80c0512f78e59a9ef419d"
        }
      ]
    }
  ]
}
