{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-constants",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "echosvg-constants-0.3.jar",
          "url": "echosvg-constants-0.3.jar",
          "size": 6870,
          "sha512": "25455b4a2ed3bb76cb531f6e1d52166d987f07da091d1ab6649fe15a05cb06ca50c1d93bff3c64e74271d275cf7465993a9d82db021cbb99fe9621302575f4dc",
          "sha256": "225f5670ed0f49c2654eaff0b18607f27e05d2cc025a9f7dca31b4e8e60df065",
          "sha1": "9110415486c5b0b28b345890f6da78947717cb5f",
          "md5": "359746b308d0ef38b8cf210f6977ce0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-constants-0.3.jar",
          "url": "echosvg-constants-0.3.jar",
          "size": 6870,
          "sha512": "25455b4a2ed3bb76cb531f6e1d52166d987f07da091d1ab6649fe15a05cb06ca50c1d93bff3c64e74271d275cf7465993a9d82db021cbb99fe9621302575f4dc",
          "sha256": "225f5670ed0f49c2654eaff0b18607f27e05d2cc025a9f7dca31b4e8e60df065",
          "sha1": "9110415486c5b0b28b345890f6da78947717cb5f",
          "md5": "359746b308d0ef38b8cf210f6977ce0c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-constants-0.3-sources.jar",
          "url": "echosvg-constants-0.3-sources.jar",
          "size": 7258,
          "sha512": "2fa882134fbed9bf1ef509644043f579c0afa8c385361f303d67492d2cc5bc1ab00a0df7d50cb26f073a9e4b06f28707ea7ac9b0ca6cded6791f9a459f5fc2d3",
          "sha256": "b65fbcf50f36ff92e8bd70a2c9aae6e69cc6f378573f1d8d4e0c73763053a115",
          "sha1": "7a7ec1a2bbdf6ba02ec2f8a2299413072fbff5d4",
          "md5": "a98e8471a6c01e091d02015a773375da"
        }
      ]
    }
  ]
}
