{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-svg-dom",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svg-dom-0.2.jar",
          "url": "echosvg-svg-dom-0.2.jar",
          "size": 73629,
          "sha512": "e11fc1a11d9e7c7810b65a714d7d2710568699e381a466bdb8c0f20dda921828ab8d22977a22c4b473772211e31fc9d692284e020fd9ad7266e3899614168e12",
          "sha256": "b3efd7a7e0f6dde872a20f4c1c951a31a7f8e0f163e2967dbbe000047ec2afb6",
          "sha1": "53f15d983ef12873d6b63c3cfbf2add5d02d1a19",
          "md5": "fdae30d2e9082b045364525061e667d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "xml-apis",
          "module": "xml-apis",
          "version": {
            "requires": "1.4.01"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svg-dom-0.2.jar",
          "url": "echosvg-svg-dom-0.2.jar",
          "size": 73629,
          "sha512": "e11fc1a11d9e7c7810b65a714d7d2710568699e381a466bdb8c0f20dda921828ab8d22977a22c4b473772211e31fc9d692284e020fd9ad7266e3899614168e12",
          "sha256": "b3efd7a7e0f6dde872a20f4c1c951a31a7f8e0f163e2967dbbe000047ec2afb6",
          "sha1": "53f15d983ef12873d6b63c3cfbf2add5d02d1a19",
          "md5": "fdae30d2e9082b045364525061e667d6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-svg-dom-0.2-sources.jar",
          "url": "echosvg-svg-dom-0.2-sources.jar",
          "size": 69660,
          "sha512": "295d9e0e7be89e3d42e81c9dbeacd4e11090f994b2b5d6a522a3dcaacd33837b32b003e4cafd6ab34792d7cacb3e1aa66ece16f8ec74b05c5b3446a28ec5761b",
          "sha256": "d3f2963f8c66b2ff11770309cb1e02bd234d171eb43ab3bd12588117697ecb9a",
          "sha1": "6a2d2302f74b542acc4521369818d2ab8a9e209c",
          "md5": "71815a973fdbee27a764bada5750ebb7"
        }
      ]
    }
  ]
}
