{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-gvt",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-gvt-1.1.jar",
          "url": "echosvg-gvt-1.1.jar",
          "size": 193859,
          "sha512": "18c28ab12c998b293914833a27b5d89fb10f2719070f6a19889870918b5bb92ebf5bd7fd9a2a63861230ab1e6601dbb668b4845daf4d10861bdca47c5a82c2c7",
          "sha256": "fe3bc71a4c656371f85f4fd3ae33dc6e30efa02be00752d8fb6508dbd82c3b4f",
          "sha1": "0f209944ac8c6d8b1dd52679ce1f9f69942aab9b",
          "md5": "9e43d05c7127e0c659177e400eb750e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-gvt-1.1.jar",
          "url": "echosvg-gvt-1.1.jar",
          "size": 193859,
          "sha512": "18c28ab12c998b293914833a27b5d89fb10f2719070f6a19889870918b5bb92ebf5bd7fd9a2a63861230ab1e6601dbb668b4845daf4d10861bdca47c5a82c2c7",
          "sha256": "fe3bc71a4c656371f85f4fd3ae33dc6e30efa02be00752d8fb6508dbd82c3b4f",
          "sha1": "0f209944ac8c6d8b1dd52679ce1f9f69942aab9b",
          "md5": "9e43d05c7127e0c659177e400eb750e3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-gvt-1.1-sources.jar",
          "url": "echosvg-gvt-1.1-sources.jar",
          "size": 200036,
          "sha512": "f1f37a3eb00e8a61894587bc6e127edbaf7a150c8bb5663f725ed8552c7078bcc47f7a4b92e86e4ddebd5cfd9e09b580b10b34aaca4403595129d1d174dcd239",
          "sha256": "18c3b2c4a58527f3765859b9c2cfdc7d5af71ae8f9efa708e35f2ae934cbb3c5",
          "sha1": "b6507a1fd9c867ea40a7b0438332b0cc90238215",
          "md5": "c9506c9d9e6d99c0c21a0611c6c34b96"
        }
      ]
    }
  ]
}
