{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-parser",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.9"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-parser-1.0.jar",
          "url": "echosvg-parser-1.0.jar",
          "size": 76327,
          "sha512": "1e93d784776ee240493eae8683151486ba9e448d7b9cd642007ce16521592ecadff0279f093d631c7b8c5d33ae71fcd323448d43b702325c30462bde600e6e2a",
          "sha256": "3535d70ebd67796e97d64b3cccd53fc43525e26a1b673698a096326f2bdf7b9e",
          "sha1": "11d5bf1bf592453ff0426b062e4128fa537b6ce7",
          "md5": "c055b897634018caf12e09607b8d3b2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "svgom-api",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.9"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-parser-1.0.jar",
          "url": "echosvg-parser-1.0.jar",
          "size": 76327,
          "sha512": "1e93d784776ee240493eae8683151486ba9e448d7b9cd642007ce16521592ecadff0279f093d631c7b8c5d33ae71fcd323448d43b702325c30462bde600e6e2a",
          "sha256": "3535d70ebd67796e97d64b3cccd53fc43525e26a1b673698a096326f2bdf7b9e",
          "sha1": "11d5bf1bf592453ff0426b062e4128fa537b6ce7",
          "md5": "c055b897634018caf12e09607b8d3b2d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-parser-1.0-sources.jar",
          "url": "echosvg-parser-1.0-sources.jar",
          "size": 82457,
          "sha512": "87892496552e3e68a06241562c2475f268cf6bc18d696efb92ca39f56e97c1b06c445e9e42721489e8c134f2113f59cb6210325c19e24c2d1e67eeb5ede3979c",
          "sha256": "114eef8d26a8ff62626eeeb317d1bbfbb1f0ed29257dc69e28255b56495ca491",
          "sha1": "bed7bbe829c437ec0cf0952c33558de09813a00f",
          "md5": "50416115cd251aa9ff10d351832774f5"
        }
      ]
    }
  ]
}
