{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-util",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-constants",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-util-0.1.2.jar",
          "url": "echosvg-util-0.1.2.jar",
          "size": 127694,
          "sha512": "5fcc3370229cc3fbaa6f2a978473d83e33f41c9ec8010c1c0022401c1b52884856a17ce5ca9a9f485e825c39d6f7dbedf3bc1ece169617616fbc812c11820ae3",
          "sha256": "83b931745b98bb8d1f72911b03944f2bda762da2bef0cf3553bbc4e3020278af",
          "sha1": "506811ed6ef26f9eeb1c859fb3171f27977e730f",
          "md5": "7a34d4673e984bdcfd0441f938302121"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-constants",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-util-0.1.2.jar",
          "url": "echosvg-util-0.1.2.jar",
          "size": 127694,
          "sha512": "5fcc3370229cc3fbaa6f2a978473d83e33f41c9ec8010c1c0022401c1b52884856a17ce5ca9a9f485e825c39d6f7dbedf3bc1ece169617616fbc812c11820ae3",
          "sha256": "83b931745b98bb8d1f72911b03944f2bda762da2bef0cf3553bbc4e3020278af",
          "sha1": "506811ed6ef26f9eeb1c859fb3171f27977e730f",
          "md5": "7a34d4673e984bdcfd0441f938302121"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-util-0.1.2-sources.jar",
          "url": "echosvg-util-0.1.2-sources.jar",
          "size": 108923,
          "sha512": "7b4ab950323b0bf8d203a1bc503b69e3dc2cc8827daaa5a2769f84bb22d8102640d0bf1a1b287702a9e3a0c874e4863e0b1fc5ba0055300836ac0cde9ba9642f",
          "sha256": "7f432da499c3a1f2ddb91ba2291c9e607fcd9fd056e6298cc53eb65e0bd27846",
          "sha1": "8826eb5e71f31bbd5d940b859d5f93be7f766ef8",
          "md5": "f6ae9d187167c18aaea804faa178c270"
        }
      ]
    }
  ]
}
