{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-ttf2svg",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "echosvg-ttf2svg-1.2.jar",
          "url": "echosvg-ttf2svg-1.2.jar",
          "size": 6422,
          "sha512": "0d9790ea1a4303fde87abe4f7b3857e9865f8d5a33e8b66fe27ee51aa1fb690a63bb897ac971f07a3f4d6db96676596c9727f908596b75c5850d56f09a2c6db8",
          "sha256": "8888803375376c42f7252fd9d3ba54ea29e3888a95086cd6469e01e52accb0df",
          "sha1": "cbb37dc2f4f54d5ddc410e2f684bc47fd71e3814",
          "md5": "ecb7aace7e0325a10c4d5bfa49481ffc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-svggen",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-ttf2svg-1.2.jar",
          "url": "echosvg-ttf2svg-1.2.jar",
          "size": 6422,
          "sha512": "0d9790ea1a4303fde87abe4f7b3857e9865f8d5a33e8b66fe27ee51aa1fb690a63bb897ac971f07a3f4d6db96676596c9727f908596b75c5850d56f09a2c6db8",
          "sha256": "8888803375376c42f7252fd9d3ba54ea29e3888a95086cd6469e01e52accb0df",
          "sha1": "cbb37dc2f4f54d5ddc410e2f684bc47fd71e3814",
          "md5": "ecb7aace7e0325a10c4d5bfa49481ffc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-ttf2svg-1.2-sources.jar",
          "url": "echosvg-ttf2svg-1.2-sources.jar",
          "size": 7053,
          "sha512": "5c71baf755c28cba53bfab436aecb20ffb7e8295e0a2657de94641d8fe09affa2685123f60d4d5333a330960e3e86ccd01b5b1f40841bf731861c98185bf3729",
          "sha256": "76b8a9ff0945d24f5eda11fc9215516370e3c364bdd184da9c4239d57fc9ba11",
          "sha1": "14478f7a97b5079bfd24cbb9d82960e28a72f8e0",
          "md5": "701318230c316a6c27cc654c309bdf6d"
        }
      ]
    }
  ]
}
