{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-constants",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "echosvg-constants-1.1.1.jar",
          "url": "echosvg-constants-1.1.1.jar",
          "size": 6999,
          "sha512": "957e0c638a83e3c7b0601f75c2cea6c8c8fb892b4d0e924902efe990d11fd793f33e847aa53b6c839ee9d404b0a1987c10ae76abbcfb13fb4b4c09d5dbcf1d86",
          "sha256": "4fe118a2ac225ca0a9210a2711ad1c76d5a445a6642a951a50e3183e902a7db4",
          "sha1": "557b8271bf91437a36c085bff30f59a962009970",
          "md5": "202dabb200dc16578ffbe3652aecdded"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-constants-1.1.1.jar",
          "url": "echosvg-constants-1.1.1.jar",
          "size": 6999,
          "sha512": "957e0c638a83e3c7b0601f75c2cea6c8c8fb892b4d0e924902efe990d11fd793f33e847aa53b6c839ee9d404b0a1987c10ae76abbcfb13fb4b4c09d5dbcf1d86",
          "sha256": "4fe118a2ac225ca0a9210a2711ad1c76d5a445a6642a951a50e3183e902a7db4",
          "sha1": "557b8271bf91437a36c085bff30f59a962009970",
          "md5": "202dabb200dc16578ffbe3652aecdded"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-constants-1.1.1-sources.jar",
          "url": "echosvg-constants-1.1.1-sources.jar",
          "size": 7414,
          "sha512": "f90a180077bf158b25497b6d87097010717e95c20be62b00ee4d64306989f44b984062ea64375955eed6792c0bf31641b558eb703fa116aba46cf369e0a5fcc4",
          "sha256": "5e44da01a2a2155506fc0f9a4ca17c173588dc32f52b2a4929460bcd83d73532",
          "sha1": "8a72028fb0d70b6773173e26d41a895a517a7d7d",
          "md5": "23ba1e531c63bd23ed99302611651bd7"
        }
      ]
    }
  ]
}
