{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-svggen",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svggen-1.2.jar",
          "url": "echosvg-svggen-1.2.jar",
          "size": 235014,
          "sha512": "cee4f0d216321ca9fbfa333bb24a2668a6f291961c00a5bc141486d93c439f6cf73de2e8e0e0203a67a4176dc604c70949501e3170c48d9b8fc5db6c8536b154",
          "sha256": "e82320238d5e2d0e62a0cb87f427fb56b851dd7bd0bd43ad8166ac78f6e88ae0",
          "sha1": "4945f66e1fd0aab4cb19637bbd0477e9efd59d96",
          "md5": "92efc083859dc3f2bd1a21d7e143559a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-codec",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svggen-1.2.jar",
          "url": "echosvg-svggen-1.2.jar",
          "size": 235014,
          "sha512": "cee4f0d216321ca9fbfa333bb24a2668a6f291961c00a5bc141486d93c439f6cf73de2e8e0e0203a67a4176dc604c70949501e3170c48d9b8fc5db6c8536b154",
          "sha256": "e82320238d5e2d0e62a0cb87f427fb56b851dd7bd0bd43ad8166ac78f6e88ae0",
          "sha1": "4945f66e1fd0aab4cb19637bbd0477e9efd59d96",
          "md5": "92efc083859dc3f2bd1a21d7e143559a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-svggen-1.2-sources.jar",
          "url": "echosvg-svggen-1.2-sources.jar",
          "size": 243478,
          "sha512": "15b783641a34a70389d15b25a4f89f461cf4ffc2705d873dde9f313898f63fad7ec8f26a2dfd8a5419fe5123dec5954d817e47d7e8929c0e801dbfec2e33f68f",
          "sha256": "cc2abd06db88b84b6f59c01c86938be46faa14075431feadf743a34c5716db6c",
          "sha1": "02ad409759960de04a0c9ff52f31ae76f9cefae2",
          "md5": "2313b085a6dbaeb9e6331341fb65af0b"
        }
      ]
    }
  ]
}
