{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-slideshow",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-slideshow-1.2.1.jar",
          "url": "echosvg-slideshow-1.2.1.jar",
          "size": 16230,
          "sha512": "b5c5a7e43d01dbf41e5b2ca7c3847f58fc3826fc9869be788e94d09a162d2797a64e50612420bea81cb3795523ae3606ee43edaf092eb0191f19cbc69298f475",
          "sha256": "d7694486ed3a20b69132756c2ddff4e488bf1b944260a51f71c9d8ec6833585c",
          "sha1": "4dfbacfc817bba30e4459e6870c4c6ce4d8a006f",
          "md5": "434fbaf54c83a877275801800ebe656e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-slideshow-1.2.1.jar",
          "url": "echosvg-slideshow-1.2.1.jar",
          "size": 16230,
          "sha512": "b5c5a7e43d01dbf41e5b2ca7c3847f58fc3826fc9869be788e94d09a162d2797a64e50612420bea81cb3795523ae3606ee43edaf092eb0191f19cbc69298f475",
          "sha256": "d7694486ed3a20b69132756c2ddff4e488bf1b944260a51f71c9d8ec6833585c",
          "sha1": "4dfbacfc817bba30e4459e6870c4c6ce4d8a006f",
          "md5": "434fbaf54c83a877275801800ebe656e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-slideshow-1.2.1-sources.jar",
          "url": "echosvg-slideshow-1.2.1-sources.jar",
          "size": 10120,
          "sha512": "9eabce3c9f67929318733164d596872827eeec65e76c2188b7c62c29db137096cad2909b99227c0ef2be8587ea24da5da4b53a9c0f9961346870dd1effb6b53c",
          "sha256": "a03032730660f09ae9eca13cc21c2e5b7b70ce435c3b96ac70d894d75c1e52d3",
          "sha1": "3c6f66f27bd9077f2428749fbff1142634d74868",
          "md5": "37053bbc4735c87fc807c6add74ffbdf"
        }
      ]
    }
  ]
}
