{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-all",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-extension",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-swing",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-slideshow",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgpp",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ttf2svg",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgrasterizer",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-all-1.2.2.jar",
          "url": "echosvg-all-1.2.2.jar",
          "size": 5528,
          "sha512": "2fbe6b5c0a23f73fdca1d199e28c73bc186a2064f86d3bed620dadc36b5b09c1395e63dc9b8170ea35611ff753069313a539766a45737a79f8570cc74ded81e5",
          "sha256": "5f623febac4ad3dc2f458ddaf9e2785d6af7bc215f91a7b1c46a7af2225c5d42",
          "sha1": "f72dced47659ca7afbec7ce1348f68dab42f1d85",
          "md5": "ccb1b1d9a6722da8563224cb80e8bf6e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-extension",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-swing",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-slideshow",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgpp",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ttf2svg",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgrasterizer",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-all-1.2.2.jar",
          "url": "echosvg-all-1.2.2.jar",
          "size": 5528,
          "sha512": "2fbe6b5c0a23f73fdca1d199e28c73bc186a2064f86d3bed620dadc36b5b09c1395e63dc9b8170ea35611ff753069313a539766a45737a79f8570cc74ded81e5",
          "sha256": "5f623febac4ad3dc2f458ddaf9e2785d6af7bc215f91a7b1c46a7af2225c5d42",
          "sha1": "f72dced47659ca7afbec7ce1348f68dab42f1d85",
          "md5": "ccb1b1d9a6722da8563224cb80e8bf6e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-all-1.2.2-sources.jar",
          "url": "echosvg-all-1.2.2-sources.jar",
          "size": 5709,
          "sha512": "761f5d4ea3e659b8e3f15251965b69c1de5517121cfbda6dc075ec0839d479ce9e479f7589b49a313c4f26644d5e2abebfc402830f978c7b476a33ca7321c309",
          "sha256": "b4c1b27fb75b3aa682c82d1ac42162cf34e2dcf4e61c22e5ce81385db3e81fe7",
          "sha1": "4def5563b6ff20d32e5b0b22298d2c9af477e602",
          "md5": "8c5a1b05f9dea69712533817a32ccd53"
        }
      ]
    }
  ]
}
