{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "xml-dtd",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "carte-util",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "xml-dtd-3.5.0.jar",
          "url": "xml-dtd-3.5.0.jar",
          "size": 186250,
          "sha512": "a9f71bb80298d62e092991be2d607b9a14bb47a6425b7df23f2bcfeb73ba7e918d32fe7391e72164af80d9755e877aed79ba1379e5aad795504e22c4314e5046",
          "sha256": "db7797405882ad42189ad693f093f7ccb595ab88bfd27d821009cd66bb674c9c",
          "sha1": "89f387e5dab640bb48a0d75595ca25a4d79c4857",
          "md5": "ee6bdf4591a75d5c0c3ee74c25f138b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "tokenproducer",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.sf.jclf",
          "module": "jclf-text",
          "version": {
            "requires": "[5.0.0,)"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "carte-util",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "xml-dtd-3.5.0.jar",
          "url": "xml-dtd-3.5.0.jar",
          "size": 186250,
          "sha512": "a9f71bb80298d62e092991be2d607b9a14bb47a6425b7df23f2bcfeb73ba7e918d32fe7391e72164af80d9755e877aed79ba1379e5aad795504e22c4314e5046",
          "sha256": "db7797405882ad42189ad693f093f7ccb595ab88bfd27d821009cd66bb674c9c",
          "sha1": "89f387e5dab640bb48a0d75595ca25a4d79c4857",
          "md5": "ee6bdf4591a75d5c0c3ee74c25f138b7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "xml-dtd-3.5.0-javadoc.jar",
          "url": "xml-dtd-3.5.0-javadoc.jar",
          "size": 129238,
          "sha512": "dc289b340b323e4cb1b9f91d31b80a2a6545d51e9d78d3ef3b84d1e9f0c1230b04956375d00d7bbbf4683564cddb4bdcc3cef6bb8a0008c74b51043f4f5be769",
          "sha256": "1100598e98d35a29d5b7f81a2a6cddf942d98d5ec1d08c7d18a04184308e1aa0",
          "sha1": "3fb89c2d8449f490af38cd1909646389915ad07d",
          "md5": "121569198bcdec3360c618028f3277d6"
        },
        {
          "name": "xml-dtd-3.5.0-javadoc.jar",
          "url": "xml-dtd-3.5.0-javadoc.jar",
          "size": 129238,
          "sha512": "dc289b340b323e4cb1b9f91d31b80a2a6545d51e9d78d3ef3b84d1e9f0c1230b04956375d00d7bbbf4683564cddb4bdcc3cef6bb8a0008c74b51043f4f5be769",
          "sha256": "1100598e98d35a29d5b7f81a2a6cddf942d98d5ec1d08c7d18a04184308e1aa0",
          "sha1": "3fb89c2d8449f490af38cd1909646389915ad07d",
          "md5": "121569198bcdec3360c618028f3277d6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "xml-dtd-3.5.0-sources.jar",
          "url": "xml-dtd-3.5.0-sources.jar",
          "size": 177813,
          "sha512": "8e01e384cf4677a0e06ef96a59172f82cef4def70544c75fea02a32871abf3e5ce0e2b67524f9a7a20540a8950d4e3df4dbe414558e430e738c768bb1e797fae",
          "sha256": "b6f29482d8cbee7f5eb0057d608d7815e95fdcaf205f64e2c0a45bb5043dc925",
          "sha1": "638eb514b8fa3e10198af33aae531413ef85a7b0",
          "md5": "60f7008945ed96a477c9962f85abdcaf"
        }
      ]
    }
  ]
}
