{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-ext",
    "version": "0.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "echosvg-ext-0.3.2.jar",
          "url": "echosvg-ext-0.3.2.jar",
          "size": 8801,
          "sha512": "5d774e956d37c2ba6f518ec2f357aecb6f7b3eafdaced0f4a0fc2725fd461e5a2ab7cce9eb96be61243188263f36561b692c2fd105066705eca24a7fa5f88f31",
          "sha256": "1784d26200b9fa9563925d6385bc8e881f1c523da3feb9aa69d21eda350492b6",
          "sha1": "ed0a5f82eb3aa658eac5ca81eeb189826a1653b1",
          "md5": "d6e941734cc4a0322be24a3ff42226c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-ext-0.3.2.jar",
          "url": "echosvg-ext-0.3.2.jar",
          "size": 8801,
          "sha512": "5d774e956d37c2ba6f518ec2f357aecb6f7b3eafdaced0f4a0fc2725fd461e5a2ab7cce9eb96be61243188263f36561b692c2fd105066705eca24a7fa5f88f31",
          "sha256": "1784d26200b9fa9563925d6385bc8e881f1c523da3feb9aa69d21eda350492b6",
          "sha1": "ed0a5f82eb3aa658eac5ca81eeb189826a1653b1",
          "md5": "d6e941734cc4a0322be24a3ff42226c1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-ext-0.3.2-sources.jar",
          "url": "echosvg-ext-0.3.2-sources.jar",
          "size": 14595,
          "sha512": "99cc285b30a4806d601635b93e658bbc01e056c72edcbbf662b42738c2069c6348f34ca6fac9ae9c0b6524f0bcceda7659db2a7d2b1d01e0f23aa55daa100018",
          "sha256": "3b3e7f25febce9a119a7ae1b8e79540900bcbbbb85e4bdcdb337c1f2a4488156",
          "sha1": "1d55c72b3e327ce0a70835896efb3e4c35433a19",
          "md5": "ad98dd7e7440a36cbb8f030740d3eeb0"
        }
      ]
    }
  ]
}
