{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-all",
    "version": "2.0-pre1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-extension",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-swing",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-slideshow",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgpp",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-api",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-svg",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-svg2svg",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-tosvg",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ttf2svg",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgrasterizer",
          "version": {
            "requires": "2.0-pre1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-all-2.0-pre1.jar",
          "url": "echosvg-all-2.0-pre1.jar",
          "size": 5714,
          "sha512": "d8b118e7ea14c2a1992cd5ce48ddce0fe19d5cf9cf5c33b6c93e842056e83092ca1e6cd296c5dd1f0a61a0a5b0417c51a184455f642375a93cb43e765660a3a2",
          "sha256": "43b060f7123af7602673796b98045712fa19cbc9d2205cbae55a3c2b632ec25b",
          "sha1": "8a2f1750123f3b47f8f6c61920f7f16a8d0220ce",
          "md5": "8dae77435b186b82b5ec06b5f23cda04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-extension",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gui-util",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-swing",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-slideshow",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgpp",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-api",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-svg",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-svg2svg",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-tosvg",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ttf2svg",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svgrasterizer",
          "version": {
            "requires": "2.0-pre1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-all-2.0-pre1.jar",
          "url": "echosvg-all-2.0-pre1.jar",
          "size": 5714,
          "sha512": "d8b118e7ea14c2a1992cd5ce48ddce0fe19d5cf9cf5c33b6c93e842056e83092ca1e6cd296c5dd1f0a61a0a5b0417c51a184455f642375a93cb43e765660a3a2",
          "sha256": "43b060f7123af7602673796b98045712fa19cbc9d2205cbae55a3c2b632ec25b",
          "sha1": "8a2f1750123f3b47f8f6c61920f7f16a8d0220ce",
          "md5": "8dae77435b186b82b5ec06b5f23cda04"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-all-2.0-pre1-sources.jar",
          "url": "echosvg-all-2.0-pre1-sources.jar",
          "size": 5872,
          "sha512": "2a7f09b669f00211c002a275d0165d02cc5aba0337c02a9d6303e44d4c2aa454d5e886ef44664fa0712371c3ca5ed9bb47b5929b511e3a9c19f9ddf06896112f",
          "sha256": "1e1e4c1fb328ff07f2e9178ec10c4553e63124b31b9c827c454df1efe77e95d6",
          "sha1": "654f892629786ff35c97b2ff698512c11f40968f",
          "md5": "c3a94eeedc215e48c3c5a6c7de2331f1"
        }
      ]
    }
  ]
}
