{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-ext",
    "version": "2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "echosvg-ext-2.3.jar",
          "url": "echosvg-ext-2.3.jar",
          "size": 9127,
          "sha512": "fadc78190edcae31090f4441c15387f8a9fa1219337403a695b0d375eeefc54c6f0416ec220cb315b91169128e476e6aa2f389d60504c4574cf3273c0e4dc08c",
          "sha256": "ae4f0f8ad310bd6c64eddfdb629f15f23c5eb06ce177d755c5f3cd86ef3dcfd2",
          "sha1": "f2ffa91e619ea14062d43b8ca9bc2029335c4e75",
          "md5": "f59c47a4a6b1770222963d752b7f9d5e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-ext-2.3.jar",
          "url": "echosvg-ext-2.3.jar",
          "size": 9127,
          "sha512": "fadc78190edcae31090f4441c15387f8a9fa1219337403a695b0d375eeefc54c6f0416ec220cb315b91169128e476e6aa2f389d60504c4574cf3273c0e4dc08c",
          "sha256": "ae4f0f8ad310bd6c64eddfdb629f15f23c5eb06ce177d755c5f3cd86ef3dcfd2",
          "sha1": "f2ffa91e619ea14062d43b8ca9bc2029335c4e75",
          "md5": "f59c47a4a6b1770222963d752b7f9d5e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-ext-2.3-sources.jar",
          "url": "echosvg-ext-2.3-sources.jar",
          "size": 14952,
          "sha512": "18e92a60a0d0442663debac828695179ddd6e1aca289fc6d85bc56c83c002dcaca481e942728562e51b98d00c7ad6935440a4c627248473b5990ab7e3204061c",
          "sha256": "1ad54803aaba5eb1d74677c7e3c02a6dd95dbea6afe431ce7f594e9d5f2e9549",
          "sha1": "e4b1ff569e38fffcc5c5776aae31e266300b1d0c",
          "md5": "853467b217a38e0f07b6af663c773c4f"
        }
      ]
    }
  ]
}
