{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-extension",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-extension-1.0.1.jar",
          "url": "echosvg-extension-1.0.1.jar",
          "size": 73083,
          "sha512": "6bfc910c5769e2813c96a7e6d1a63879e9ccfad9136e663da696d302bf5580cb1cb49441a86e6ad573a71d34191a2c3108108f405d874d99293ac51d58c54796",
          "sha256": "06f2958141b6ab0e38ef310f3c438a2e5019c561c6e4d5ab1c4d2cdadd9838fc",
          "sha1": "4b84aae00c4206d58c7baf38d34011bf28479931",
          "md5": "bf8b8033ada8b712092a68f4928e4622"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "xml-apis",
          "module": "xml-apis",
          "version": {
            "requires": "1.4.01"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-extension-1.0.1.jar",
          "url": "echosvg-extension-1.0.1.jar",
          "size": 73083,
          "sha512": "6bfc910c5769e2813c96a7e6d1a63879e9ccfad9136e663da696d302bf5580cb1cb49441a86e6ad573a71d34191a2c3108108f405d874d99293ac51d58c54796",
          "sha256": "06f2958141b6ab0e38ef310f3c438a2e5019c561c6e4d5ab1c4d2cdadd9838fc",
          "sha1": "4b84aae00c4206d58c7baf38d34011bf28479931",
          "md5": "bf8b8033ada8b712092a68f4928e4622"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-extension-1.0.1-sources.jar",
          "url": "echosvg-extension-1.0.1-sources.jar",
          "size": 67483,
          "sha512": "4676d8f9079bb3cefcc72a3dbc467e1b03cb7c01bf143f06115696253237fc2016151be0ad43577628e9bc91e42ee72f66e5efb54f408ac893c1ba81d60034f3",
          "sha256": "9986c88dc10bf10bba3eca5f644c4b8461289ce1d442e137d49ac9f03060bd07",
          "sha1": "19dff63c791b03764ff1addbf1bb0ff3852983a3",
          "md5": "de7acba844469ebe0b44aa2797910b65"
        }
      ]
    }
  ]
}
