{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-anim",
    "version": "2.0-pre1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "2.0-pre1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-anim-2.0-pre1.jar",
          "url": "echosvg-anim-2.0-pre1.jar",
          "size": 517331,
          "sha512": "49d7ee7636be79d81958a5819cc0e6874902e28e421646e9d1608901a4952012afb772abc1a9c9ecf2ad17d587f4d4902c117636032088b4ca496ec807ac4bd4",
          "sha256": "0d167db41e3b3172bf23c7d6a7057d3c56d20e717395acc3b4acfa70aae6cca3",
          "sha1": "8764ccd2b1feea0193c224225bd1a0f5e23f78c4",
          "md5": "46e048bf6b08a25e4922fca54db26ee6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "2.0-pre1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-anim-2.0-pre1.jar",
          "url": "echosvg-anim-2.0-pre1.jar",
          "size": 517331,
          "sha512": "49d7ee7636be79d81958a5819cc0e6874902e28e421646e9d1608901a4952012afb772abc1a9c9ecf2ad17d587f4d4902c117636032088b4ca496ec807ac4bd4",
          "sha256": "0d167db41e3b3172bf23c7d6a7057d3c56d20e717395acc3b4acfa70aae6cca3",
          "sha1": "8764ccd2b1feea0193c224225bd1a0f5e23f78c4",
          "md5": "46e048bf6b08a25e4922fca54db26ee6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-anim-2.0-pre1-sources.jar",
          "url": "echosvg-anim-2.0-pre1-sources.jar",
          "size": 383488,
          "sha512": "aa6de0bdbe9cb90f9d39e0c27bedf7dd08b4d3911927dc629421fc595ab5e875b036d58a02ce9e365ed3ac4b0381453b9a1e7afeb04f16907ef98dac807f38d1",
          "sha256": "688d4ea47f73debfaa0deb0bb47a1028d9ed7e5ea70c316de264dcddcbb4cd71",
          "sha1": "a2f6a0f98ac1e7dc6e3d9c9658992c8e113b2fb9",
          "md5": "0ae1e58e2e421c1ed531f4ac5d316355"
        }
      ]
    }
  ]
}
