{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-dom",
    "version": "0.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-css",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "xml-dtd",
          "version": {
            "requires": "4.2"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.8"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-dom-0.3.2.jar",
          "url": "echosvg-dom-0.3.2.jar",
          "size": 197284,
          "sha512": "ac4fe68b909e2ddfe00028024253786b71711581ad9c582b30b979e4b93290e5d230a163e02ccdc01ef3d4e64dc8490bfc22179ceb23cc1fb7fa164a355f82a6",
          "sha256": "2f8ef9cb226a1711ca12da7c3f00413c1a0d29ba0ab4b071e03d7d13539fbde6",
          "sha1": "e0f315e837d671db735b350485b4a4e3ed210c63",
          "md5": "6488246cd4ffc38302c006fccf959f2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "xml-apis",
          "module": "xml-apis",
          "version": {
            "requires": "1.4.01"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-css",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-ext",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-xml",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "xml-dtd",
          "version": {
            "requires": "4.2"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.8"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-dom-0.3.2.jar",
          "url": "echosvg-dom-0.3.2.jar",
          "size": 197284,
          "sha512": "ac4fe68b909e2ddfe00028024253786b71711581ad9c582b30b979e4b93290e5d230a163e02ccdc01ef3d4e64dc8490bfc22179ceb23cc1fb7fa164a355f82a6",
          "sha256": "2f8ef9cb226a1711ca12da7c3f00413c1a0d29ba0ab4b071e03d7d13539fbde6",
          "sha1": "e0f315e837d671db735b350485b4a4e3ed210c63",
          "md5": "6488246cd4ffc38302c006fccf959f2e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-dom-0.3.2-sources.jar",
          "url": "echosvg-dom-0.3.2-sources.jar",
          "size": 169123,
          "sha512": "7a493832bb49f1413685e3e4bf3fba0a2ce417bca5cc451361979f2297767e5bc6fbf04ae5982120fac5ef0d549c77b1ba7e9c87ef629b4653b66343d2f1b13a",
          "sha256": "ed522bb29f86a07a781752f943c964ee2c5422f93adb12e07bd1e0a15a89e288",
          "sha1": "85afc65e86c0b0bf3ced2bdb353a390a7e095028",
          "md5": "2ca9c39915437c4a2cc86b3abaf49da9"
        }
      ]
    }
  ]
}
