{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-anim",
    "version": "2.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-anim-2.2.1.jar",
          "url": "echosvg-anim-2.2.1.jar",
          "size": 514896,
          "sha512": "8c5c43b37e9db299b03f668fc232ddf64664daa37e2fec1f45e17f6e9e74ab4d688cb97680130a29e1ef7a10d4f4bd426ce8d7d39785a9086bf7b9d993fad117",
          "sha256": "b4157f3f5968df7602447fe82d93e43662843c2bd0ab79d15270dc852fb51f4f",
          "sha1": "8b57b54bb873a27ce1c974f872c15b6182fc8616",
          "md5": "46a4096cbd52cbc5795ed5058babb7c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-anim-2.2.1.jar",
          "url": "echosvg-anim-2.2.1.jar",
          "size": 514896,
          "sha512": "8c5c43b37e9db299b03f668fc232ddf64664daa37e2fec1f45e17f6e9e74ab4d688cb97680130a29e1ef7a10d4f4bd426ce8d7d39785a9086bf7b9d993fad117",
          "sha256": "b4157f3f5968df7602447fe82d93e43662843c2bd0ab79d15270dc852fb51f4f",
          "sha1": "8b57b54bb873a27ce1c974f872c15b6182fc8616",
          "md5": "46a4096cbd52cbc5795ed5058babb7c7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-anim-2.2.1-sources.jar",
          "url": "echosvg-anim-2.2.1-sources.jar",
          "size": 381563,
          "sha512": "570b67a96f8e0595f086ad5321670101f3fb5e7b23d31eaa93f9905986fd0f7716aa30a40bbc92d428ccbd8949c00be959baf6030bafcf0cde1b3e7b06e433e0",
          "sha256": "e4d018c2da045bbbb9163325f82cb096e789c891225cfc88f081589622bb74af",
          "sha1": "fcb2d4a3d35b7e6816f85896c715bb61f7fae4e3",
          "md5": "b24c3f8d05d548047b402e8ca9f3a8b7"
        }
      ]
    }
  ]
}
