{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-bridge",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gvt",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.7"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-bridge-0.2.1.jar",
          "url": "echosvg-bridge-0.2.1.jar",
          "size": 720329,
          "sha512": "ffc8f159b1323543bd02c86edc3cdb2d6b2bc9645d387f10b6936e62b45352adb23dfb11dcf882ee320b88f8bf5226a92114de87bc2225f7fc9d2195168d7ca9",
          "sha256": "33c5d169d32917477e38f4916c0f45719605ce75df88b9b3e23b2081abafede8",
          "sha1": "8810ecac63b52f6baaf90814137422ccacb84635",
          "md5": "c93a4ff85d11ea874f6b5e6ad31b5127"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "xml-apis",
          "module": "xml-apis",
          "version": {
            "requires": "1.4.01"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gvt",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.7"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-bridge-0.2.1.jar",
          "url": "echosvg-bridge-0.2.1.jar",
          "size": 720329,
          "sha512": "ffc8f159b1323543bd02c86edc3cdb2d6b2bc9645d387f10b6936e62b45352adb23dfb11dcf882ee320b88f8bf5226a92114de87bc2225f7fc9d2195168d7ca9",
          "sha256": "33c5d169d32917477e38f4916c0f45719605ce75df88b9b3e23b2081abafede8",
          "sha1": "8810ecac63b52f6baaf90814137422ccacb84635",
          "md5": "c93a4ff85d11ea874f6b5e6ad31b5127"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-bridge-0.2.1-sources.jar",
          "url": "echosvg-bridge-0.2.1-sources.jar",
          "size": 491522,
          "sha512": "077b62b43b7ad957f7e57e432aa3bde94ca2f09bbf2a541ed8c7105c33c875d8e0835a5ba766f81c9a0fb0d246908d8411f8ad1aba6a2d9c8a5ac759af867968",
          "sha256": "072aeb33b03440f44e591f5937c94076a82289b2de8ac6e57831eda379e52acb",
          "sha1": "f1a64555d437a65cfc7dd14535bb60b857c43134",
          "md5": "ce3b1f8e89a02923d314536b0fe720c2"
        }
      ]
    }
  ]
}
