{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-svggen",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svggen-0.1.jar",
          "url": "echosvg-svggen-0.1.jar",
          "size": 232800,
          "sha512": "9cb0fb762ef7d66c133f9fc1f8bd24b88eb82d808295bbd88d93b71219a85d4ad1606d1349a7ad4171d93a9d9cc014dedc0900ea400ebb8f150a64b48f790839",
          "sha256": "33397b216be0528adca1af9aab880e22593acf67bc1dcee5a0ecb3994434d257",
          "sha1": "ec176b526b380d3428d03e4ef27465177c021c9a",
          "md5": "920750dee80be10baa5e8436eed18653"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svggen-0.1.jar",
          "url": "echosvg-svggen-0.1.jar",
          "size": 232800,
          "sha512": "9cb0fb762ef7d66c133f9fc1f8bd24b88eb82d808295bbd88d93b71219a85d4ad1606d1349a7ad4171d93a9d9cc014dedc0900ea400ebb8f150a64b48f790839",
          "sha256": "33397b216be0528adca1af9aab880e22593acf67bc1dcee5a0ecb3994434d257",
          "sha1": "ec176b526b380d3428d03e4ef27465177c021c9a",
          "md5": "920750dee80be10baa5e8436eed18653"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-svggen-0.1-sources.jar",
          "url": "echosvg-svggen-0.1-sources.jar",
          "size": 240266,
          "sha512": "80a323dcfbead046ed170191e6751aa4a79a3660765e084c8d2949f782c237bc3b1c2e1e961f17454804859658eb51d447041559217258112e34a558523b8a12",
          "sha256": "03631db4c504a0e344cbdd48d09c9fd8391f11b98416280bfb252a45f5f9a56e",
          "sha1": "39a6a337e82a558cb8eed47b8aa9baf7ca7ae72b",
          "md5": "8749282738a671064e0352d914296c65"
        }
      ]
    }
  ]
}
