{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-bridge",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gvt",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.8"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-bridge-0.2.2.jar",
          "url": "echosvg-bridge-0.2.2.jar",
          "size": 720329,
          "sha512": "12f166937fcbf55b0884b16af082895d61e57d645b7970ec8c29459afc1c37b8983c98d16bc8eeb484c46394cd0db6e6710133b928e85fe495f6764ffcb681a6",
          "sha256": "97fe0a08c0aaba1e732026b4b3e42c89ac479e9b85876e91437c5357b99598ee",
          "sha1": "8f7c0a4aa4c5b0574c82abc789a1e70742450fb3",
          "md5": "97ba7b929f2265c89a18ae17026dcc7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "xml-apis",
          "module": "xml-apis",
          "version": {
            "requires": "1.4.01"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-anim",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-gvt",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-script",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "xmlgraphics-commons",
          "version": {
            "requires": "2.8"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-bridge-0.2.2.jar",
          "url": "echosvg-bridge-0.2.2.jar",
          "size": 720329,
          "sha512": "12f166937fcbf55b0884b16af082895d61e57d645b7970ec8c29459afc1c37b8983c98d16bc8eeb484c46394cd0db6e6710133b928e85fe495f6764ffcb681a6",
          "sha256": "97fe0a08c0aaba1e732026b4b3e42c89ac479e9b85876e91437c5357b99598ee",
          "sha1": "8f7c0a4aa4c5b0574c82abc789a1e70742450fb3",
          "md5": "97ba7b929f2265c89a18ae17026dcc7b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-bridge-0.2.2-sources.jar",
          "url": "echosvg-bridge-0.2.2-sources.jar",
          "size": 491524,
          "sha512": "27020722143ec67439f2004de8aa9c86cb9161d9f6068028ddb952649fa165e30597fc25f1b820c0c5d587bc0933c5fe27314bcc03fe7e48877d56660b3757b8",
          "sha256": "b5ad7c545f2933e9da68a9c13ee73cb1167c566b30e5f322f548571017163ca5",
          "sha1": "fc91cd6d3dd6ce65d98193c65390e6fd378035ca",
          "md5": "170007e85fb176b18bf09e1790f81dcc"
        }
      ]
    }
  ]
}
