{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-xml",
    "version": "2.0-pre1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "2.0-pre1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-xml-2.0-pre1.jar",
          "url": "echosvg-xml-2.0-pre1.jar",
          "size": 32554,
          "sha512": "4e52ebafb302672132d6e12f4be8ff069b8d47a1a564e1482130b6d603addd7d7872ce8ccbfff86eb657dadf63817848cdd9ab23d49e8f9866c61c126fca028e",
          "sha256": "39d2e8a802b9d14eeb25e47b373015ac74e3bfb26c244e99e0e8b0428e8db16d",
          "sha1": "b09d5de8757fe80d2a5931c97d96c5c0813e3f69",
          "md5": "8f22b9f11a9375c11023346ed5938c47"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "2.0-pre1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-i18n",
          "version": {
            "requires": "2.0-pre1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-xml-2.0-pre1.jar",
          "url": "echosvg-xml-2.0-pre1.jar",
          "size": 32554,
          "sha512": "4e52ebafb302672132d6e12f4be8ff069b8d47a1a564e1482130b6d603addd7d7872ce8ccbfff86eb657dadf63817848cdd9ab23d49e8f9866c61c126fca028e",
          "sha256": "39d2e8a802b9d14eeb25e47b373015ac74e3bfb26c244e99e0e8b0428e8db16d",
          "sha1": "b09d5de8757fe80d2a5931c97d96c5c0813e3f69",
          "md5": "8f22b9f11a9375c11023346ed5938c47"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-xml-2.0-pre1-sources.jar",
          "url": "echosvg-xml-2.0-pre1-sources.jar",
          "size": 23643,
          "sha512": "46e6adb0aed73df13ebb3dea3bb9fab86ad96782ded9c1de3792d0ea3bd6df0f19caa13afdec8fdd147644c1a1bea5cf9b4708ebafcfe017c20d816a22ed7ae4",
          "sha256": "1dfbac43d9ef18052454998fde81f36f640d2faf25e73a01c81c2c3388498c2b",
          "sha1": "db6400203b897c470e507e183d587222f090d434",
          "md5": "c0f2940904e5f34de8711017ab979a15"
        }
      ]
    }
  ]
}
