{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "xml-dtd",
    "version": "4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "carte-util",
          "version": {
            "strictly": "[3.4.0,)",
            "requires": "[3.4.0,)",
            "prefers": "3.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "xml-dtd-4.2.jar",
          "url": "xml-dtd-4.2.jar",
          "size": 198261,
          "sha512": "8a662cf1afa3f412feff96a658b35eae45d12e733088f3b56644299bece7f56e45e0c234fc398b674054bdd99bdab8a04ee152307931399cb39ade1d61e17323",
          "sha256": "1c1fe4a90d9cef2215ad8633a92828705c00902052afa34e7d67d2bbd2be4c6c",
          "sha1": "a1ebe6d2b6e456d38063bffd5068acdf5f3d8298",
          "md5": "f34d8b1e0cbe67873d243fac6276e3e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "carte-util",
          "version": {
            "strictly": "[3.4.0,)",
            "requires": "[3.4.0,)",
            "prefers": "3.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "xml-dtd-4.2.jar",
          "url": "xml-dtd-4.2.jar",
          "size": 198261,
          "sha512": "8a662cf1afa3f412feff96a658b35eae45d12e733088f3b56644299bece7f56e45e0c234fc398b674054bdd99bdab8a04ee152307931399cb39ade1d61e17323",
          "sha256": "1c1fe4a90d9cef2215ad8633a92828705c00902052afa34e7d67d2bbd2be4c6c",
          "sha1": "a1ebe6d2b6e456d38063bffd5068acdf5f3d8298",
          "md5": "f34d8b1e0cbe67873d243fac6276e3e7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "xml-dtd-4.2-javadoc.jar",
          "url": "xml-dtd-4.2-javadoc.jar",
          "size": 100226,
          "sha512": "c4d4f7b3acfd24226d6dba39ae3b966b06bbb01d559c51fe50189c7b70a54e533b54ba970df304d0bf33886bceb8cf1929ce922bf2f7be487fe90584091ae2d9",
          "sha256": "41b1bd161805413bf9d72b126e0c39ee2f8a875c1acaf71ce52ad5b919dffc12",
          "sha1": "e20d81c729546d8e76f1bc8809465ea887cf2d47",
          "md5": "a66d64941c9b2dd2db4793636754a428"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "xml-dtd-4.2-sources.jar",
          "url": "xml-dtd-4.2-sources.jar",
          "size": 190874,
          "sha512": "daae738a032c6093229e423c73235b17295a60136d972be2cea2ec6f2e1445a141cf821115ca04b9606da22f42a1fbd890ec548f3c83790a6537c322b06a4a94",
          "sha256": "d1a9bedc23cf6cdba676c8d905f843be5edd9490537bed9b37ea284097c3eb51",
          "sha1": "318b793b0810cda4e424ee0549cd9ef4fba7b660",
          "md5": "afa335a6d2566c0ec382e266eb088cc8"
        }
      ]
    },
    {
      "name": "dtdparseApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "xml-dtd-4.2.jar",
          "url": "xml-dtd-4.2.jar",
          "size": 198261,
          "sha512": "8a662cf1afa3f412feff96a658b35eae45d12e733088f3b56644299bece7f56e45e0c234fc398b674054bdd99bdab8a04ee152307931399cb39ade1d61e17323",
          "sha256": "1c1fe4a90d9cef2215ad8633a92828705c00902052afa34e7d67d2bbd2be4c6c",
          "sha1": "a1ebe6d2b6e456d38063bffd5068acdf5f3d8298",
          "md5": "f34d8b1e0cbe67873d243fac6276e3e7"
        }
      ],
      "capabilities": [
        {
          "group": "io.sf.carte",
          "name": "xml-dtd-dtdparse",
          "version": "4.2"
        }
      ]
    },
    {
      "name": "dtdparseRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "tokenproducer",
          "version": {
            "requires": "[2.0.1,)"
          }
        }
      ],
      "files": [
        {
          "name": "xml-dtd-4.2.jar",
          "url": "xml-dtd-4.2.jar",
          "size": 198261,
          "sha512": "8a662cf1afa3f412feff96a658b35eae45d12e733088f3b56644299bece7f56e45e0c234fc398b674054bdd99bdab8a04ee152307931399cb39ade1d61e17323",
          "sha256": "1c1fe4a90d9cef2215ad8633a92828705c00902052afa34e7d67d2bbd2be4c6c",
          "sha1": "a1ebe6d2b6e456d38063bffd5068acdf5f3d8298",
          "md5": "f34d8b1e0cbe67873d243fac6276e3e7"
        }
      ],
      "capabilities": [
        {
          "group": "io.sf.carte",
          "name": "xml-dtd-dtdparse",
          "version": "4.2"
        }
      ]
    },
    {
      "name": "dtdeclApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "xml-dtd-4.2.jar",
          "url": "xml-dtd-4.2.jar",
          "size": 198261,
          "sha512": "8a662cf1afa3f412feff96a658b35eae45d12e733088f3b56644299bece7f56e45e0c234fc398b674054bdd99bdab8a04ee152307931399cb39ade1d61e17323",
          "sha256": "1c1fe4a90d9cef2215ad8633a92828705c00902052afa34e7d67d2bbd2be4c6c",
          "sha1": "a1ebe6d2b6e456d38063bffd5068acdf5f3d8298",
          "md5": "f34d8b1e0cbe67873d243fac6276e3e7"
        }
      ],
      "capabilities": [
        {
          "group": "io.sf.carte",
          "name": "xml-dtd-dtdecl",
          "version": "4.2"
        }
      ]
    },
    {
      "name": "dtdeclRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.jclf",
          "module": "jclf-text",
          "version": {
            "requires": "[5.0.0,)"
          }
        }
      ],
      "files": [
        {
          "name": "xml-dtd-4.2.jar",
          "url": "xml-dtd-4.2.jar",
          "size": 198261,
          "sha512": "8a662cf1afa3f412feff96a658b35eae45d12e733088f3b56644299bece7f56e45e0c234fc398b674054bdd99bdab8a04ee152307931399cb39ade1d61e17323",
          "sha256": "1c1fe4a90d9cef2215ad8633a92828705c00902052afa34e7d67d2bbd2be4c6c",
          "sha1": "a1ebe6d2b6e456d38063bffd5068acdf5f3d8298",
          "md5": "f34d8b1e0cbe67873d243fac6276e3e7"
        }
      ],
      "capabilities": [
        {
          "group": "io.sf.carte",
          "name": "xml-dtd-dtdecl",
          "version": "4.2"
        }
      ]
    }
  ]
}
