{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-transcoder-svg",
    "version": "2.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-api",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-transcoder-svg-2.2.1.jar",
          "url": "echosvg-transcoder-svg-2.2.1.jar",
          "size": 71797,
          "sha512": "a6e0ed6f99932b9364606bbf4e42a480398717ca511082aecd9195275e266b97eb0363085fc47e8c12478e9082f43d81fe542fdc0ab00f78e1d33326ab906781",
          "sha256": "884ff16479bf62cf7790dd1c020e12696dcdf94d117fc033956265076c725a8f",
          "sha1": "5206cb7080d41e0433b9cb12b5c3ed8e437c7dcc",
          "md5": "99d4f2eed17c3b08be85917d52319ffb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-codec",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "css4j-awt",
          "version": {
            "requires": "6.0"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "xml-dtd",
          "version": {
            "requires": "4.3"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-transcoder-api",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-bridge",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-transcoder-svg-2.2.1.jar",
          "url": "echosvg-transcoder-svg-2.2.1.jar",
          "size": 71797,
          "sha512": "a6e0ed6f99932b9364606bbf4e42a480398717ca511082aecd9195275e266b97eb0363085fc47e8c12478e9082f43d81fe542fdc0ab00f78e1d33326ab906781",
          "sha256": "884ff16479bf62cf7790dd1c020e12696dcdf94d117fc033956265076c725a8f",
          "sha1": "5206cb7080d41e0433b9cb12b5c3ed8e437c7dcc",
          "md5": "99d4f2eed17c3b08be85917d52319ffb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-transcoder-svg-2.2.1-sources.jar",
          "url": "echosvg-transcoder-svg-2.2.1-sources.jar",
          "size": 55964,
          "sha512": "90e1d7b0bd7da3fce426cd94c0ec07db380d38f5daa6fc8dce106cfb55e11d7a1fef199cae64c411ca2917598dd460d8a92e6cb569788d75584991b5bef03efe",
          "sha256": "04703071c9e0f677adb1813dbd5447c160c198d1c8badaf5ba6e87cbb02b00a8",
          "sha1": "f93ef4ae49f7769e5b785151debb09b60cc961b4",
          "md5": "98a9dac515e8601e8a4cadfe34536f4d"
        }
      ]
    }
  ]
}
