{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-anim",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-anim-0.1.jar",
          "url": "echosvg-anim-0.1.jar",
          "size": 506165,
          "sha512": "7784d697f3fd7ef344a6aeb685d9025396257c9d8dc81bc245857840d359d31f7cf20e70bf6f292dc7f34edb16bf48fdd77b93c292ef481289a8d58b54705425",
          "sha256": "7dbd9149936fc8c31ac33a324328211ddcd0cc909f4857252dadf504fbeac1b7",
          "sha1": "3c71de7b9b89536bcbb4fc39bfa4b255619af2d5",
          "md5": "887ebe6384c978ab824ee8390a34c6ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-anim-0.1.jar",
          "url": "echosvg-anim-0.1.jar",
          "size": 506165,
          "sha512": "7784d697f3fd7ef344a6aeb685d9025396257c9d8dc81bc245857840d359d31f7cf20e70bf6f292dc7f34edb16bf48fdd77b93c292ef481289a8d58b54705425",
          "sha256": "7dbd9149936fc8c31ac33a324328211ddcd0cc909f4857252dadf504fbeac1b7",
          "sha1": "3c71de7b9b89536bcbb4fc39bfa4b255619af2d5",
          "md5": "887ebe6384c978ab824ee8390a34c6ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-anim-0.1-sources.jar",
          "url": "echosvg-anim-0.1-sources.jar",
          "size": 377662,
          "sha512": "e7b62164b353e07dbbb4b4df1cf9f51e33fc227d147b2401c88d7042fc91c49c6b5f41ddbda0e29b19b8e7fa4a2be795770ec749614e19a7e71da9d28a627e06",
          "sha256": "da8f2edf4e9a4ba9d299105511441fb2046119971a7072f98721b2e3f1fd2e59",
          "sha1": "91dafaaf36b2a25b669bca78de51394007cb12f6",
          "md5": "d158189c1c058aadc93e32878fa6434d"
        }
      ]
    }
  ]
}
