{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-anim",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "xml-apis",
          "module": "xml-apis-ext",
          "version": {
            "requires": "1.3.04"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-anim-0.1.jar",
          "url": "echosvg-anim-0.1.jar",
          "size": 506186,
          "sha512": "492025a8f2a5ba7a00d0effd894af62171b61ac330a9bf9883900cbf09887b87853dac802687b9e5c23a41be1687ce51ac22c0759b70c5d26242377e46e7d4ff",
          "sha256": "54cf49b1d9ecada3d67298b7b395ff74d15cd0c97ac6f6ca5ca19662c3e88cf0",
          "sha1": "d45d25bf7d7adbe99c5076c4e9d56e217e02ddb8",
          "md5": "c30c91b06cf1a0ac0a0e88ff3290c230"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-svg-dom",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "xml-apis",
          "module": "xml-apis-ext",
          "version": {
            "requires": "1.3.04"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-anim-0.1.jar",
          "url": "echosvg-anim-0.1.jar",
          "size": 506186,
          "sha512": "492025a8f2a5ba7a00d0effd894af62171b61ac330a9bf9883900cbf09887b87853dac802687b9e5c23a41be1687ce51ac22c0759b70c5d26242377e46e7d4ff",
          "sha256": "54cf49b1d9ecada3d67298b7b395ff74d15cd0c97ac6f6ca5ca19662c3e88cf0",
          "sha1": "d45d25bf7d7adbe99c5076c4e9d56e217e02ddb8",
          "md5": "c30c91b06cf1a0ac0a0e88ff3290c230"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-anim-0.1-sources.jar",
          "url": "echosvg-anim-0.1-sources.jar",
          "size": 377604,
          "sha512": "9f4aeb5cef325a77eb1da0047c09a6835f2383b92ce6f180cc87b871b575461e26e6bd435deae8fcc0b8fac694aba279b1949db4ae5382b239cb7c0095cb1223",
          "sha256": "88800f9495787081aca7b680ad35b918fe4c17b2f3a48c3f994396d834f796b6",
          "sha1": "3ff5775b6242509b860b71de3104cc53c1826227",
          "md5": "a4743ad32f84deb7b01453ce63ce27c2"
        }
      ]
    }
  ]
}
