{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "smil-api",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "smil-api-1.0.jar",
          "url": "smil-api-1.0.jar",
          "size": 6171,
          "sha512": "790ca5b2bdfed6daf15bda97f3c0d03e5d239a9758eca1b2c771977e26ed72f015b8add4ac4c0e5062d23618630ef21f72bfc5440990fc93500eeddced255b8a",
          "sha256": "8476bf8db349cd8be3c273c0d5385c321777f44d50fc67bdcdd3c6224b06a9de",
          "sha1": "9e7d671b665c4b2a68e0e9db12bc59b67c315e2f",
          "md5": "6cfc8da92a994368dcc3e62a9131d71b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smil-api-1.0.jar",
          "url": "smil-api-1.0.jar",
          "size": 6171,
          "sha512": "790ca5b2bdfed6daf15bda97f3c0d03e5d239a9758eca1b2c771977e26ed72f015b8add4ac4c0e5062d23618630ef21f72bfc5440990fc93500eeddced255b8a",
          "sha256": "8476bf8db349cd8be3c273c0d5385c321777f44d50fc67bdcdd3c6224b06a9de",
          "sha1": "9e7d671b665c4b2a68e0e9db12bc59b67c315e2f",
          "md5": "6cfc8da92a994368dcc3e62a9131d71b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smil-api-1.0-sources.jar",
          "url": "smil-api-1.0-sources.jar",
          "size": 7015,
          "sha512": "2201ce4e559801ebcbaf7a85a16498b3822e465e6982a564de02a888a96ba330d86bf58ec9c3bf1eb9d6980164b255a62a54ad39ca463ed1e07469cb62c6949d",
          "sha256": "bd119aaa55dde73955609950ffb8aed4512d9ed70ebaf9d9d61667e1db644dbe",
          "sha1": "d3eb99199ef98c1876bd532811f72f4061e1ecd9",
          "md5": "2d0e32b659f07b3339ca606828609c04"
        }
      ]
    }
  ]
}
