# Examples CI workflow
#
# Verifies that the Maven repository is correctly set to be used
# by downstream Java 8 applications.

name: Examples

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  check:
    runs-on: ubuntu-latest

    name: Java Examples check

    steps:
      # Check-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v5

      - name: Setup JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      # Check the build
      - name: Test the build
        run: ./gradlew test

      # Upload test artifact
      - name: Upload test output
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test-output
          path: |
            build/reports/tests/
          retention-days: 15
          overwrite: true
