{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-svg-dom",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svg-dom-1.2.2.jar",
          "url": "echosvg-svg-dom-1.2.2.jar",
          "size": 74982,
          "sha512": "c71360cb367196191c7fa8a8207d16564d5e1c2c2604e25951ae9f3059dc851b0efa3d1850a3a10ce5821ec11710c67d11a72e171fc47056b4b4e94b7ca0c296",
          "sha256": "c32edd3baa0bee532e20f48d725edc862b421f5d38940c8860ffc1e644d6b040",
          "sha1": "e69c4569097ae78314cff688574c4be1c13f3179",
          "md5": "54f26b3cecb720fc2aca9aa0f769eb49"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-dom",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-parser",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-svg-dom-1.2.2.jar",
          "url": "echosvg-svg-dom-1.2.2.jar",
          "size": 74982,
          "sha512": "c71360cb367196191c7fa8a8207d16564d5e1c2c2604e25951ae9f3059dc851b0efa3d1850a3a10ce5821ec11710c67d11a72e171fc47056b4b4e94b7ca0c296",
          "sha256": "c32edd3baa0bee532e20f48d725edc862b421f5d38940c8860ffc1e644d6b040",
          "sha1": "e69c4569097ae78314cff688574c4be1c13f3179",
          "md5": "54f26b3cecb720fc2aca9aa0f769eb49"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-svg-dom-1.2.2-sources.jar",
          "url": "echosvg-svg-dom-1.2.2-sources.jar",
          "size": 70134,
          "sha512": "746b407158b94bdbb24d2573810af8c3c55a9e1d270d25aa4580ec37ae5417e3a38cd6ae10a809e8e2c5d544879c79cba183874d63d67f98963ad8ee546645de",
          "sha256": "8113130779c40d0554fc38143b0857be069d989f19509471a9f136a64817e213",
          "sha1": "9b3fed65cde9bbf8537e4a91578c07d48f6ca94f",
          "md5": "cf32c1d9227ef60cb36fc35897109faf"
        }
      ]
    }
  ]
}
