{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-gvt",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-gvt-0.1.jar",
          "url": "echosvg-gvt-0.1.jar",
          "size": 195875,
          "sha512": "f5405964acba0513329d7a1fea282c255461390aca980d1fb2cacfbf7d1b6d236a7ddbffa522b232f0c520a6980451685b6f0fb5ae4c7321d141033e2d75fd57",
          "sha256": "dba30a49503e258dcc15098a16e18dfd59ac7d34a843e950a03c5008a61da171",
          "sha1": "3492b0a10413ceaf4422b79e80cd99c13e8bab19",
          "md5": "c4f20222a117e0c28415a16213497374"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-gvt-0.1.jar",
          "url": "echosvg-gvt-0.1.jar",
          "size": 195875,
          "sha512": "f5405964acba0513329d7a1fea282c255461390aca980d1fb2cacfbf7d1b6d236a7ddbffa522b232f0c520a6980451685b6f0fb5ae4c7321d141033e2d75fd57",
          "sha256": "dba30a49503e258dcc15098a16e18dfd59ac7d34a843e950a03c5008a61da171",
          "sha1": "3492b0a10413ceaf4422b79e80cd99c13e8bab19",
          "md5": "c4f20222a117e0c28415a16213497374"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-gvt-0.1-sources.jar",
          "url": "echosvg-gvt-0.1-sources.jar",
          "size": 199730,
          "sha512": "a14e47fb698a553b238f70eaaf17920ec00cda6198829cffd8633b5bd94ee87365242f9c7ccaf2b979da387fad653ffb5dc657760bc10788f22226e917ff8fb3",
          "sha256": "333f87afe4fceca485f70eda3e7c026b65e8f8dec27afedaee10498351f25184",
          "sha1": "7e619f21e502b8792586970c090af91918c67df1",
          "md5": "bb699ce18320575ef0b5c2fbdd01f50c"
        }
      ]
    }
  ]
}
