{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sf.carte",
    "module": "echosvg-gvt",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-gvt-0.1.2.jar",
          "url": "echosvg-gvt-0.1.2.jar",
          "size": 195550,
          "sha512": "5fe70fe82ed73fa5e74b4e6556601ab2f995d153e4276dbd53938d4e0cb867696c3a6ff4c1ba26ae064781bc92eb2380457930fbee5d8dbcc764a0cf83129fc7",
          "sha256": "b6066d5aad85df5f2752a9eaa3b0b30e47e9235cab56294580d224784e8829e9",
          "sha1": "4fd2556eb78a43324d6cea850df023d0d2f44340",
          "md5": "2341bbad4b13664fb06caf4202bcfa58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sf.carte",
          "module": "echosvg-awt-util",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.sf.carte",
          "module": "echosvg-util",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "echosvg-gvt-0.1.2.jar",
          "url": "echosvg-gvt-0.1.2.jar",
          "size": 195550,
          "sha512": "5fe70fe82ed73fa5e74b4e6556601ab2f995d153e4276dbd53938d4e0cb867696c3a6ff4c1ba26ae064781bc92eb2380457930fbee5d8dbcc764a0cf83129fc7",
          "sha256": "b6066d5aad85df5f2752a9eaa3b0b30e47e9235cab56294580d224784e8829e9",
          "sha1": "4fd2556eb78a43324d6cea850df023d0d2f44340",
          "md5": "2341bbad4b13664fb06caf4202bcfa58"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "echosvg-gvt-0.1.2-sources.jar",
          "url": "echosvg-gvt-0.1.2-sources.jar",
          "size": 201236,
          "sha512": "bab1ad2113d69979a25adde55301e93897588d2ddb4d25a710880c84f3505d656579bfef04bbf202e7150628ed8cd4861849de37445e8bf28a4c580d4e97b851",
          "sha256": "98fb35a6a7a2df37be098ce25148497b4e6caef49683951c7e0a5b49171300d2",
          "sha1": "8e0a262e9c6d7c0bd63bedfa5df2ff9536b271ec",
          "md5": "03f52f9869d530486dd2cf45b9d46650"
        }
      ]
    }
  ]
}
